### ISSUE TITLE
make print optional for 'summary' of objects 

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/adegenet#10]
Roman Lustrik [roman.lustrik@biolitika.si]
[Reply] [Reply All] [Forward]
Actions
To:
Jombart, Thibaut

02 February 2015 12:58
You replied on 02/02/2015 13:04.
Dear mr. Jombart,

we have been using adegenet for our analyses for some time and it has become an invaluable tool in our daily routine.
The summary method prints various statements through cat and print which produces a verbose output in e.g. a simulation environment. So far we have been catching the messages through sink(), but we would be grateful if you would consider making output printing optional. I can think of integrating a "verbose" argument that turns off printing or using message() which can be caught through suppressMessages().

Cheers,
Roman

**Comment by romunov** [comment]
What would be the best option to implement this? Make a branch, test it and then you can merge it to the master?

**Comment by zkamvar** [comment]
Yup!

Make a branch. Add the thing. Make a pull request. All is well. :)

**Comment by thibautjombart** [comment]
+1 to that. github really makes our lives easier =D

**Comment by romunov** [comment]
Almost got this, still need to sort out documentation (trying to document the summary function since I've added a `verbose` argument).

**Comment by thibautjombart** [comment]
Cool.

**Comment by thibautjombart** [comment]
@romunov release of 2.0.0 coming soon, so good time to make a pull request if the patch is ready. No worries otherwise, that can come any time.

**Comment by romunov** [comment]
I was holding it off until I had the roxygen2 docs ready but I hit a wall so I'll just release the function and edit the existing .Rd file.

**Comment by romunov** [comment]
While I'm at it, should I clean the code for explicit calls to some slots, like `x@pop` -> `pop(x)`?

**Comment by zkamvar** [comment]
Reopening this. Some old code got leaked in and the tests for summary aren't passing anymore:

```R

1. Error: Diploid summaries work -----------------------------------------------
no slot of name "pop.names" for this object of class "genind"
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls, message = function(c) invokeRestart("muffleMessage"), 
       warning = function(c) invokeRestart("muffleWarning"))
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: summary(nancycats, verbose = FALSE) at test_summary.R:6
5: summary(nancycats, verbose = FALSE)
6: .local(object, ...)
```

**Comment by zkamvar** [comment]
I'll fix it.

**Comment by thibautjombart** [comment]
I have just sent emails and tweets about adegenet 2.0.0 being clean / ready
for testing for developers depending on it. Please only push changes which
can pass the check, otherwise fork & pull request.

As an alternative, I'm happy to create a separate branch for the devel post
2.0.0 - let me know if needed?

**Comment by romunov** [comment]
I think creating a branch for a "feature" and merge once it passes the checks is a sensible strategy.

**Comment by zkamvar** [comment]
Best way to do this is to use a pull request from that branch. That way, Travis can do checking on the merge.

**Comment by thibautjombart** [comment]
Yes, +1 to pull request

**Comment by romunov** [comment]
I did a `test("adegenet")` on the `exp_basicMethods` branch and test for summary passed. It stopped at `xvalDapc`.

**Comment by romunov** [comment]
The branch passes the checks. I suspect it's ready to be merged at some point.

**Comment by thibautjombart** [comment]
I just created a new branch 'newfeatures' - will create a separate issue to
discuss this. I've done the merge and testing, will push when OK.

**Comment by thibautjombart** [comment]
See this about branches:
https://github.com/thibautjombart/adegenet/issues/64

I have merged exp_basicMethods into newfeatures. Check passes. @romunov would you like to add something into the ChangeLog? If the new version is backward compatible then let's merge it into the master.

**Comment by romunov** [comment]
I think the change log is OK. Merge away.

**Comment by thibautjombart** [comment]
Done
