### ISSUE TITLE
label individuals in dapc result

### ISSUE THREAD

**Issue by romunov** [thibautjombart/adegenet#100]
Hi,

a user [Carlos Pecoraro has asked about labeling individuals when plotting `dapc` result](http://lists.r-forge.r-project.org/pipermail/adegenet-forum/2015-October/001332.html). I think this would be done nicely using vegan's `orditorp` ([my gist about it](https://gist.github.com/romunov/4f6e05cf721829eb2eaa)). What do you guys think?

**Comment by thibautjombart** [comment]
I like it! New option for `scatter.dapc` + pull request? ;)

**Comment by romunov** [comment]
Aye, probably soon.
