### ISSUE TITLE
Request for next CRAN release

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#102]
I'm wondering when the next CRAN release will be. There are some significant improvements and bug fixes that have occurred. Additionally, those of us over at http://nescent.github.io/popgenInfo/ are attempting to polish things up for our publication and we're trying to make sure that we are working with current package versions by the end of the year. 

I know CRAN can be a pain. :confused:

**Comment by thibautjombart** [comment]
Heya - sorry for taking long to reply, was travelling, and will soon be on holiday. I won't have time to make a release in the meantime, but I don't want to be slowing things down either.. Would you like to do it?

**Comment by zkamvar** [comment]
No worries. I've been working on my qualifying exams. I can certainly take care of the release soon. You will probably still get an email from CRAN asking if it's okay for me to submit it.

**Comment by thibautjombart** [comment]
Cool!
I'm officially on summer holiday now, yayyyy! Off to BVI tomorrow, can't
wait! =D
Good luck with stuff!
Cheers
Thibaut

**Comment by zkamvar** [comment]
:tropical_drink:

**Comment by zkamvar** [comment]
bump :bowtie:

**Comment by thibautjombart** [comment]
Oh.. yes, there was that.
Shall we?

**Comment by zkamvar** [comment]
:+1:

**Comment by thibautjombart** [comment]
OK, adding it on my TODO list.

**Comment by thibautjombart** [comment]
Cross your fingers, pray, behead chickens whilst mumbling in ancient tongs: 2.0.1 finally submitted to CRAN.

**Comment by thibautjombart** [comment]
Kurt Hornik
15:12 (9 minutes ago)

to me, CRAN 
>>>>> Thibaut Jombart writes:

Thanks, on CRAN now.

Best

**Comment by thibautjombart** [comment]
Amen.

**Comment by zkamvar** [comment]
:rooster: :hocho: :chicken: :skull: 

ALL HAIL HORNIK!
