### ISSUE TITLE
tab can't return frequencies for P/A genpop objects

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#105]
Example:

```r
x <- read.table(system.file("files/AFLP.txt", package = "adegenet"))
aflp <- df2genind(x, type = "PA", ploidy = 1, pop = c(rep(1, 4), rep(2, 3)))
tab(genind2genpop(aflp), freq = TRUE)
## Error in FUN(newX[, i], ...) : arguments must have same length 
```

This comes down to the [line here](https://github.com/thibautjombart/adegenet/blob/c92d3234c35bb97e097e7901fecd42d2d686b42a/R/handling.R#L122) where it attempts to do a tapply using a NULL `loc.fac` slot. I'll take care of this bug and write a test.

**Comment by thibautjombart** [comment]
thanks for the fix!
