### ISSUE TITLE
'mc.cores' > 1 is not supported on Windows

### ISSUE THREAD

**Issue by knausb** [thibautjombart/adegenet#109]
Hello,

I have a function 'vcfR2genelight' which I'm using to convert an object from a package I'm working on called vcfR to genlight objects. This function calls adegenet::as.genlight on a matrix of genotypes to create the genlight object. On Windows this currently throws an error:

    >     x <- adegenet::as.genlight(t(x))
    Error in mclapply(1:nrow(input$gen), function(i) new("SNPbin", as.integer(input$gen[i,  : 
      'mc.cores' > 1 is not supported on Windows

This appears to be because Windows does not support forking. In trying to find a solution I found:

http://lists.r-forge.r-project.org/pipermail/adegenet-forum/2013-July/000681.html

But that did not appear to resolve the issue. I've also made an attempt with:

    x <- adegenet::as.genlight(t(x), n.cores=1)

With the hope I could pass that information on. But it generated the same error. I feel there should be a way for Windows users to set mc.cores to 1 but can't figure it out. Any suggestions? Or is there something I've overlooked?

If you want to handle this within adegenet perhaps something like:

    if( .Platform$OS.type == "windows" ){
      n.cores = 1
    }

might provide a solution?

Thank you for any help!
Brian

**Comment by thibautjombart** [comment]
Hi there,
I like the suggestion. Fork & pull request? ;)
Cheers
Thibaut

**Comment by thibautjombart** [comment]
Fixed at ad5602
