### ISSUE TITLE
read.genepop does return individual names

### ISSUE THREAD

**Issue by andersgs** [thibautjombart/adegenet#117]
Hello Thibaut. Great package, really useful. 

The new read.genepop() does not return individual names. It seems that the df2genind call at the end is missing the ind.names parameter:

     res <- df2genind(X = X, pop = pop, ploidy = 2, ncode = ncode)

Simple fix would be to:

    res <- df2genind(X = X, pop = pop, ploidy = 2, ncode = ncode, ind.names = ind.names)

Thank you.

Anders.

**Comment by thibautjombart** [comment]
Hi Anders,

I don't think genepop file store individual labels actually.

Cheers


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>

**Comment by romunov** [comment]
Small world. I'm importing a genepop file and we noticed the same behavior. I checked the [genepop documentation](http://genepop.curtin.edu.au/help_input.html) on the file and it would appear individual names are optional. In fact, last individual name defines population name.

Here's an example from the website.

```
------------- The file starts here ---------------- 
Microsat on Chiracus radioactivus, a pest species 
     Loc1, Loc2, Loc3, Y-linked, Loc4 
POP 
AA8, 0405 0711 0304 0000      0505 
AA9, 0405 0609 0208 0000      0505 
A10, 0205 0609 0101 0000      0305 
A11, 0405 0606 0102 0000      0504 
A12, 0202 0609 0105 0000      0507 
A13, 0505 0909 0107 0000      0505 
A14, 0202 0609 0207 0000      0503 
A15, 0405 0609 0101 0000      0505 
Pop
AF, 0000 0000 0000 0000      0505 
AF, 0205 0307 0102 0000      0505 
AF, 0202 0609 0202 0000      0505 
AF, 0205 0909 0000 0000      0505 
AF, 0205 0307 0202 0000      0505 
AF, 0505 0303 0102 0000      0505 
AF, 0205 0700 0000 0000      0505 
AF, 0505 0900 0000 0000      0405 
AF, 0205 0600 0000 0000      0505 
AF, 0505 0606 0202 0000      0505 
pop 
C45, 0505 0606 0202 0000      0505 
C45, 0505 0909 0202 0000      0505 
C45, 0505 0306 0202 0000      0505 
C45, 0505 0909 0102 0000      0405 
C45, 0205 0303 0202 0000      0505 
C45, 0205 0909 0202 0000      0405 
------------- The file ends here -------------------
```

**Comment by thibautjombart** [comment]
Ha, this is why I hate this format..

The example above is a good example of terrible practice. We basically
have, in the same field, two different types of information recorded. The
best I could offer would be handling individual labels whenever they are
unique, but that wouldn't help with this example.



--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>

**Comment by romunov** [comment]
The function [already isolates](https://github.com/thibautjombart/adegenet/blob/master/R/import.R#L628) individual names but they're not used. They're replaced by [numbers](https://github.com/thibautjombart/adegenet/blob/master/R/import.R#L638). This can be solved in two ways. Either changing line [638](https://github.com/thibautjombart/adegenet/blob/master/R/import.R#L638) or add argument `ind.names` to line [651](https://github.com/thibautjombart/adegenet/blob/master/R/import.R#L651).

If we decide to change this function, I would vote for the first option.

**Comment by thibautjombart** [comment]
Yes, we could decide to condition
https://github.com/thibautjombart/adegenet/blob/master/R/import.R#L638 on
the duplication of individual labels, and use them if there is no duplicate.


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>

**Comment by romunov** [comment]
And it brings us to #116. :)

**Comment by thibautjombart** [comment]
Yup. Bootstrap is a particular case though. As a rule, I would really like
to avoid tolerating label duplication anywhere.


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>

**Comment by romunov** [comment]
I've made a [push to a branch](https://github.com/thibautjombart/adegenet/tree/read.genepop_with_individual_names). I tested this one nancycats and my own file and it appears to work.

**Comment by thibautjombart** [comment]
Great, thanks


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>

**Comment by andersgs** [comment]
Thank you Roman and Thibaut. Yeah, I know it is an edge case, but it is an important one for me: github.com/andersgs/irelr.

I have tried running it with my proposed solution, and because it calls df2genind, it will automatically issue the warning and substitute the names for row numbers if there are duplicates.

Best. Anders.

**Comment by romunov** [comment]
Can we merge the changes to master, then?

**Comment by thibautjombart** [comment]
Err..I can't see any pull request?
;)


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>

**Comment by andersgs** [comment]
Thank you.
