### ISSUE TITLE
writing structure files

### ISSUE THREAD

**Issue by romunov** [thibautjombart/adegenet#118]
Is there a plan to implement a function that will write files to be imported by Structure? I noticed there's some code [from 2010](http://lists.r-forge.r-project.org/pipermail/adegenet-forum/2010-April/000099.html) and I also implemented one in our [lab package](https://github.com/romunov/zvau/blob/master/R/writeStructure.R) (which may not be 100% reliable ATM) so we wouldn't start from scratch.

**Comment by thibautjombart** [comment]
Not for now, and it is not in line with current movements aiming to do most
popgen in R.
STRUCTURE would not be my pick in any case, but BAPS would be an option.
Not sure what inputs need to be though, but it must be documented
somewhere, and I already work with Jukka on other topics.


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>
