### ISSUE TITLE
Incorrect matrix and zeroes in genind object.

### ISSUE THREAD

**Issue by emsd** [thibautjombart/adegenet#121]
Hi there, 

My problem is similar to #101, and #95, but I dont have any "."

I am converting a structure file to a genind.

all_loci_hyb<-read.structure("1hyb7k.stru", row.marknames=1, onerowperind=FALSE, n.ind=161, n.loc=3996, col.lab=1, col.pop=2, NA.char=0, ask=FALSE)

The data has 3,9996 SNP loci and 161 individuals. Each locus has 2 alleles. 
But the matrix @tab is: 161 x 7923. 
It should be 161*7,992

Also the number of zeroes (NA) in the data is incomplete. 
sum(is.na(all_loci_hyb$tab))
Adegenet answer is: 195,962, 
But in the structure file there are 197,654, so there are 1,692 zeros not recognized. 

Any tips will be appreciated!!

**Comment by romunov** [comment]
Can you provide the structure file as well? Without it, this would probably be a little more than a wild goose chase, unfortunately.

**Comment by emsd** [comment]
Thanks, I really appreciate your help!!



On Thu, Dec 17, 2015 at 3:57 AM, Roman Luštrik <notifications@github.com>
wrote:

> Can you provide the structure file as well? Without it, this would
> probably be a little more than a wild goose chase, unfortunately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thibautjombart/adegenet/issues/121#issuecomment-165434686>
> .
>



-- 
Eva Salas
PhD student
University of California Santa Cruz and California Academy of Sciences
http://evasalas.weebly.com/

**Comment by emsd** [comment]
Please let me know if you cant open the file

**Comment by thibautjombart** [comment]
I suspect the missing character is actually "0", so maybe you should try:

all_loci_hyb<-readstructure("1hyb7kstru", rowmarknames=1,
onerowperind=FALSE, nind=161, nloc=3996, collab=1, colpop=2, NAchar="0",
ask=FALSE)

Does that help?


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>
