### ISSUE TITLE
Library(adehabitat) causes R to crash and close

### ISSUE THREAD

**Issue by mgiresi** [thibautjombart/adegenet#123]
When I try to load (adehabitat), R crashes with a number of errors, see below:

> library(adehabitat)
> Loading required package: tkrplot
> Loading required package: tcltk

 **\* caught segfault ***
address 0x998, cause 'memory not mapped'

Traceback:
 1: structure(.External(.C_dotTclObjv, objv), class = "tclObj")
 2: .Tcl.objv(.Tcl.args.objv(...))
 3: tcl("load", file, "Rplot")
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(tcl("load", file, "Rplot"), error = function(e) warning("loading Rplot failed",     call. = FALSE))
 8: fun(libname, pkgname)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(fun(libname, pkgname), error = identity)
13: runHook(".onLoad", env, package.lib, package)
14: loadNamespace(package, c(which.lib.loc, lib.loc))
15: doTryCatch(return(expr), name, parentenv, handler)
16: tryCatchOne(expr, names, parentenv, handlers[[1L]])
17: tryCatchList(expr, classes, parentenv, handlers)
18: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
19: try({    ns <- loadNamespace(package, c(which.lib.loc, lib.loc))    env <- attachNamespace(ns, pos = pos, deps)})
20: library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc)
21: .getRequiredPackages2(pkgInfo, quietly = quietly)
22: library(adehabitat)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by zkamvar** [comment]
This is not an *adegenet* issue. You will want to contact the maintainer of *adehabitat* to resolve this issue: Clement Calenge <clement.calenge at oncfs.gouv.fr>

FWIW, The results page on CRAN shows that it's only failing on OSX: https://cran.r-project.org/web/checks/check_results_adehabitat.html

Additionally, I tried to build older versions, but they all fail in the same way. 

Good luck,
Zhian

**Comment by thibautjombart** [comment]
Actually, we need to change the use of adehabitat, even though this is not an adegenet problem. From the (absolutely insane) loading msg below (which has been there for the last couple of years):

```
THE PACKAGE adehabitat IS NOW DEPRECATED!!!!!!!
 It is dangerous to use it, as bugs will no longer be corrected.
It is now recommended to use the packages adehabitatMA, adehabitatLT, adehabitatHR, and adehabitatHS.
These 4 packages are the future of adehabitat.
 They have a vignette explaining in detail how they can be used.
They implement more methods than adehabitat
They are based on the more common and more clever spatial classes implemented in sp.
Bugs are corrected frequently.
Really, avoid to use the classical adehabitat, unless you have a very good reason for it.

*****THIS IS THE VERY LAST WARNING*****
 This is the last version of adehabitat submitted to CRAN (at the time of writing: 2015-03-27).
 THE NEXT VERSION OF adehabitat WILL JUST BE A VIRTUAL PACKAGE LOADING ALL THE PACKAGES DESCRIBED ABOVE.
```

**Comment by mgiresi** [comment]
I'm not  clear as to why the package needs to be loaded at all.  SPCA works
without it.

**Comment by thibautjombart** [comment]
adehabitat is no longer used in the package.
