### ISSUE TITLE
IUPAC ambiguity codes and DAPC

### ISSUE THREAD

**Issue by janinemelanie** [thibautjombart/adegenet#124]
Hi everyone,

probably a stupid question, but I just want to be sure. Does the package adegenet correctly interpret IUPAC ambiguity codes in sequence alignments? 

Thanks a lot for your help.

**Comment by thibautjombart** [comment]
Sequences are not stored by adegenet, but by other packages - ape, seqinr. When converting these data into genind you can specify which characters are to be treated as alleles. See `?DNAbin2genind`.
