### ISSUE TITLE
"'mc.cores' > 1 is not supported on Windows" - "Genlight Object" - "find.cluster"

### ISSUE THREAD

**Issue by DaniloLyra** [thibautjombart/adegenet#126]
Hi, I can't run the function "find.cluster" with my "genlight" object. I wanna know if it can be fixed?

```r
> library("adegenet")
> packageDescription("adegenet", fields = "Version")
[1] "2.0.1"
> dat <- list(toto=c(1,1,0,0), titi=c(NA,1,1,0), tata=c(NA,0,3, NA))
> x <- new("genlight", dat)
> x
 /// GENLIGHT OBJECT /////////

 // 3 genotypes,  4 binary SNPs, size: 6.6 Kb
 3 (25 %) missing data

 // Basic content
   @gen: list of 3 SNPbin

 // Optional content
   @ind.names:  3 individual labels
   @other: a list containing: elements without names 

> grp <- find.clusters(x, max.n.clust=40)
Error in mclapply(levels(fac.block), function(lev) x[, which(fac.block ==  : 
  'mc.cores' > 1 is not supported on Windows 
```

**Comment by zkamvar** [comment]
Can you post the result of `devtools::session_info()`?

**Comment by DaniloLyra** [comment]
Hi, yes. 

> devtools::session_info()
Session info ----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, mingw32             
 ui       RStudio (0.99.489)          
 language (EN)                        
 collate  Portuguese_Brazil.1252      
 tz       America/Sao_Paulo           
 date     2016-02-08                  

Packages --------------------------------------------------------------------------------------
 package    * version date       source        
 ade4       * 1.7-3   2015-11-22 CRAN (R 3.2.3)
 adegenet   * 2.0.1   2015-11-23 local         
 ape          3.4     2015-11-29 CRAN (R 3.2.3)
 assertthat   0.1     2013-12-06 CRAN (R 3.2.2)
 boot         1.3-17  2015-06-29 CRAN (R 3.2.2)
 cluster      2.0.3   2015-07-21 CRAN (R 3.2.2)
 coda         0.18-1  2015-10-16 CRAN (R 3.2.2)
 colorspace   1.2-6   2015-03-11 CRAN (R 3.2.2)
 DBI          0.3.1   2014-09-24 CRAN (R 3.2.2)
 deldir       0.1-9   2015-03-09 CRAN (R 3.2.2)
 devtools   * 1.10.0  2016-01-23 CRAN (R 3.2.3)
 digest       0.6.9   2016-01-08 CRAN (R 3.2.3)
 dplyr        0.4.3   2015-09-01 CRAN (R 3.2.2)
 ggplot2      2.0.0   2015-12-18 CRAN (R 3.2.3)
 gtable       0.1.2   2012-12-05 CRAN (R 3.2.2)
 htmltools    0.3     2015-12-29 CRAN (R 3.2.3)
 httpuv       1.3.3   2015-08-04 CRAN (R 3.2.3)
 igraph       1.0.1   2015-06-26 CRAN (R 3.2.3)
 lattice      0.20-33 2015-07-14 CRAN (R 3.2.2)
 LearnBayes   2.15    2014-05-29 CRAN (R 3.2.2)
 magrittr     1.5     2014-11-22 CRAN (R 3.2.2)
 MASS         7.3-44  2015-08-30 CRAN (R 3.2.2)
 Matrix       1.2-2   2015-07-08 CRAN (R 3.2.2)
 memoise      1.0.0   2016-01-29 CRAN (R 3.2.3)
 mgcv         1.8-8   2015-10-24 CRAN (R 3.2.2)
 mime         0.4     2015-09-03 CRAN (R 3.2.2)
 munsell      0.4.2   2013-07-11 CRAN (R 3.2.2)
 nlme         3.1-122 2015-08-19 CRAN (R 3.2.2)
 permute      0.9-0   2016-01-24 CRAN (R 3.2.3)
 plyr         1.8.3   2015-06-12 CRAN (R 3.2.3)
 R6           2.1.2   2016-01-26 CRAN (R 3.2.3)
 Rcpp         0.12.3  2016-01-10 CRAN (R 3.2.3)
 reshape2     1.4.1   2014-12-06 CRAN (R 3.2.2)
 rstudioapi   0.3.1   2015-04-07 CRAN (R 3.2.2)
 scales       0.3.0   2015-08-25 CRAN (R 3.2.2)
 seqinr       3.1-3   2014-12-17 CRAN (R 3.2.3)
 shiny        0.13.0  2016-01-12 CRAN (R 3.2.3)
 sp           1.2-1   2015-10-18 CRAN (R 3.2.2)
 spdep        0.5-92  2015-12-22 CRAN (R 3.2.3)
 stringi      1.0-1   2015-10-22 CRAN (R 3.2.2)
 stringr      1.0.0   2015-04-30 CRAN (R 3.2.2)
 vegan        2.3-3   2016-01-12 CRAN (R 3.2.3)
 xtable       1.8-0   2015-11-02 CRAN (R 3.2.2)
>

**Comment by thibautjombart** [comment]
Can you try:
```r
find.clusters(x, max.n.clust=40, parallel=FALSE)
```
?

**Comment by DaniloLyra** [comment]
Yes! Thanks!

> packageDescription("adegenet", fields = "Version")
[1] "2.0.1"
> dat <- list(toto=c(1,1,0,0), titi=c(NA,1,1,0), tata=c(NA,0,3, NA))
> (x <- new("genlight", dat))
 /// GENLIGHT OBJECT /////////

 // 3 genotypes,  4 binary SNPs, size: 6.6 Kb
 3 (25 %) missing data

 // Basic content
   @gen: list of 3 SNPbin

 // Optional content
   @ind.names:  3 individual labels
   @other: a list containing: elements without names 

> grp <- find.clusters(x, max.n.clust=50, parallel=FALSE)
Choose the number PCs to retain (>=1)

**Comment by DaniloLyra** [comment]
Problem solved. Thanks.
