### ISSUE TITLE
Issue github release and send announcement to R-SIG-GENTICS

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#127]
Since the gods have spoken and adegenet is now on CRAN (#102), I've drafted a github release (https://github.com/thibautjombart/adegenet/releases/) for the 2.0.1 tag. If it's okay with y'all, I'll publish it and send out a blurb on R-SIG-GENETICS.

**Comment by thibautjombart** [comment]
Great idea, please go ahead !

**Comment by zkamvar** [comment]
:100:

**Comment by romunov** [comment]
I blink and I miss it. Good job ya all.

**Comment by thibautjombart** [comment]
=D
