### ISSUE TITLE
genlight constructor: 8 simultaneous processes spawned

### ISSUE THREAD

**Issue by knausb** [thibautjombart/adegenet#128]
Hello,

I have a function that calls as.genlight(). When I use:

    R CMD check my.package --as-cran

I get the error:

    8 simultaneous processes spawned

(I have a quad core processor, so with hyperthreading I have a maximum of 8 cores.) The [CRAN repository policy](https://cran.r-project.org/web/packages/policies.html) indicates that running a package should never use more than 2 threads in order to preserve CRAN computing resources.

A possible solution would be to set the default behaviour of as.genlight() to use one thread. This would also address #110. If that sounds reasonable I could look into it next week and if successful create a pull request. Does this sound reasonable?

P.S. Congrats on the recent release!

**Comment by thibautjombart** [comment]
That sounds perfect indeed. I agree, we should default to no-multithreading. If you can fix and pull-request that'd be brilliant!

**Comment by knausb** [comment]
Well... I think I've discovered that this is a little more complicated than I anticipated. But I have a new proposal that I think will work.

My original proposal was to add a parameter to the as function:

    as.genlight(object=my.matrix, n.cores=1)

My understanding of how this is done is through the function setAs. But I don't think this has the flexibility to add another parameter. At least, I couldn't figure it out.

As an alternate proposal, we could use getOptions("mc.cores"). Within the initialize function for genlight we can query its value. If NULL we can set it to 1. If not NULL we can set n.cores based on it. We can also test that it does not exceed parallel::detectCores(). And lastly, query the operating system and set to 1 if "windows." In hindsight I've convinced myself that this is a better proposal than my first because if this behaviour were adopted throughout the package it would allow one step thread management instead of having to parameterize each multi-threaded function.

I've attempted this on my local version of adegenet and it appears to work. But it appears to break the tests. And because I see changing options as non-intuitive I feel this would need to be documented. So I thought I'd check in to see if there were opinions on this proposal before I invest more time.

Thanks!

**Comment by romunov** [comment]
Hvala za porocilo. Imas morda "odlocbo" ZRSVNja? Ce ne, bom jaz zaprosil,
da mi posljejo, ker me res zanika kako so argentirali ta poseg.

lp,
Roman

**Comment by thibautjombart** [comment]
I think we should just change the behaviour of parallel=TRUE to
parallel=FALSE by default. It doesn't work on windows, and causes problems
on linux clusters too.

Cheers
Thibaut


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
https://github.com/thibautjombart
Twitter: @TeebzR <https://twitter.com/TeebzR>

**Comment by knausb** [comment]
Setting mc.cores appears to be as easy as:

    options("mc.cores" = 1)

This should be platform independent and should work in a cluster environment. But it doesn't appear in line with the philosophy of how adegenet currently approaches multi-threading. Thibaut's answer seems most appropriate in that it preserves this style.

For the purposes of my package, it appears I should use the 'new' method instead of 'as.' The new method already allows for the number of cores to be specified.

I think Thibaut meant to set n.cores=1. Or perhaps I just don't understand his proposal. I'll create a pull request. But you may want to put some critical thought into whether I've accomplished what you've suggested.

Thanks!

**Comment by thibautjombart** [comment]
Hi there, 
not exactly, I meant to disable the use of parallel by default. In many places we had:
`parallel=require(parallel)` which are probably safer as `parallel=FALSE`. I'm about to push a patch on this.

**Comment by thibautjombart** [comment]
Done as of 8f9ea43

**Comment by knausb** [comment]
Oops, I do not feel I closed this appropriately because I failed to validate that the fix addressed the issue. I have just installed e8d0fa0b22a87cd0d34e5b31e784da02e36a698b and rerun:

    R CMD check my_package.tar.gz --as-cran

And I no longer see the error reporting multiple processes. I have now validated that the fix addressed this issue.

Thank you!

**Comment by thibautjombart** [comment]
Great, thanks!


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
https://github.com/thibautjombart
Twitter: @TeebzR <https://twitter.com/TeebzR>
