### ISSUE TITLE
problem in `df2genind` when alleles encoding contain a .

### ISSUE THREAD

**Issue by jgx65** [thibautjombart/adegenet#132]
I stumbled on a little bug in df2genind when some alleles encoding contain a dot:

```{r}
dat<-data.frame(pop=c(1,1,2,2),loc1=c("1/1","1/2","1.1/2","2/2"),loc2=c("1/1","1/2","1/2","2/2"))
(datgi<-df2genind(dat[,-1],sep="/",pop=dat[,1]))
```

If the dot is replaced by e.g. a dash, no problems:

```{r}
dat<-data.frame(pop=c(1,1,2,2),loc1=c("1/1","1/2","1_1/2","2/2"),loc2=c("1/1","1/2","1/2","2/2"))
(datgi<-df2genind(dat[,-1],sep="/",pop=dat[,1]))
```
Any chance to either fix it or warn that dots should not enter allele encoding?

**Comment by zkamvar** [comment]
Which is the more desirable outcome? 

- [ ] throw error and let user fix it
- [ ] throw warning and replace dot with underscore

There's currently a mechanism to do this with locus names, but not with alleles.

**Comment by EricArcher** [comment]
I vote for "throw warning and replace dot with underscore". This would work unless the underscore causes other issues, like it is already being used as a separator. In which case, maybe replacing with something ugly like a # would make the replacement obvious and unlikely to cause other conflicts...

**Comment by thierrygosselin** [comment]
I had the same issue last week and now change the dot to `:` to avoid potential problems with underscore.

**Comment by thibautjombart** [comment]
My vote goes to option 2: send a warning and replace with underscore

**Comment by zkamvar** [comment]
I've addressed this so that underscores are still allowable separators.

| input | fix |
|--------|-----|
| 1/1.1 | 1/1_1 |
| 1_1.1 | 1_1p1 |

**Comment by thibautjombart** [comment]
Cool. Pull request? ;)

**Comment by zkamvar** [comment]
Whoops. Already on master.

**Comment by thibautjombart** [comment]
Perfect!


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
https://github.com/thibautjombart
Twitter: @TeebzR <https://twitter.com/TeebzR>
