### ISSUE TITLE
Have genind and genlight objects "remember" strata

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#133]
Currently genind and genlight objects have the `setPop()` method, which allows the user to specify a specific combination of strata to use for the population argument. However, the information of what strata was used is not retained. There might be room for a slot called strataform or something goofy like that to store the formula used to create the strata.

**Comment by thibautjombart** [comment]
Sounds good to me. Using the attribute of the strata may be easier to avoid breaking things too much? At any rate I'd be keen to avoid having to change all genind objects distributed with the package, or breaking compatibility with current genind structure. What do you think?

**Comment by zkamvar** [comment]
> At any rate I'd be keen to avoid having to change all genind objects distributed with the package, or breaking compatibility with current genind structure. What do you think?

Ah yes, the incompatibility issue. That would be a good thing to avoid. Serves me right for suggesting things when I'm not properly caffeinated :coffee:. Giving it a second thought, this is something that isn't direly necessary, and would be more trouble than it's worth ¯\_(ツ)_/¯
