### ISSUE TITLE
Unable to install adegenet for R version 3.2.2

### ISSUE THREAD

**Issue by Adisha05** [thibautjombart/adegenet#135]
Unable to install adegenet. Tried from the source too but without any luck.
install.packages("adegenet", dep=TRUE)
Installing package into ‘/public/abc/R/x86_64-redhat-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://mirrors.ebi.ac.uk/CRAN/src/contrib
Warning message:
package ‘adegenet’ is not available (for R version 3.2.2)

**Comment by zkamvar** [comment]
This seems to be an error that's related to your mirror. What happens when you try

```r
install.packages("adegenet", dep = TRUE, repo = "https://cran.r-project.org")
```

**Comment by Adisha05** [comment]
still the same error
install.packages("adegenet", dep = TRUE, repo = "https://cran.r-project.org")
Installing package into ‘/public/abc/R/x86_64-redhat-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://cran.r-project.org/src/contrib
Warning message:
package ‘adegenet’ is not available (for R version 3.2.2)

**Comment by zkamvar** [comment]
what happens if you try http instead of https?

**Comment by Adisha05** [comment]
if i try http instead of https, I get these warning messages:
1: In install.packages("adegenet", dep = TRUE, repo = "http://cran.r-project.org") :
  installation of package ‘dplyr’ had non-zero exit status
2: In install.packages("adegenet", dep = TRUE, repo = "http://cran.r-project.org") :
  installation of package ‘adegenet’ had non-zero exit status
3: In install.packages("adegenet", dep = TRUE, repo = "http://cran.r-project.org") :
  installation of package ‘pegas’ had non-zero exit status
4: In install.packages("adegenet", dep = TRUE, repo = "http://cran.r-project.org") :
  installation of package ‘hierfstat’ had non-zero exit status

**Comment by zkamvar** [comment]
Perhaps you are behind a firewall? At this point, I'm not convinced that this is an issue with adegenet specifically. It looks like you are unable to install packages in general. If you can, try installing a random package (e.g. "stringr") and see if you get the same errors. If you do, I would try google or stackoverflow.

**Comment by Adisha05** [comment]
@zkamvar Thankyou so much for prompt replies! It was indeed an permission issue. The server guy fixed it.Done!
