### ISSUE TITLE
make spca a generic, with method for df, matrix, genind, genpop

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/adegenet#143]
From the adegenet forum:

> Dear all,
> 
> The function na.replace seems to have disappear from the last version of ADEGENET 2.0.1.
> 
> Now, one can use scaleGen()  or tab() to replace missing data by the “mean”, for example. However  > the returned object is a frequency table. It seems that the spca() function does not accept frequencies since adegenet 2.0.0.  What is the recommended procedure to replace missing data by the mean and conduct a sPCA? 
> 
> Furthermore, I am using the jitter function to put some noise around my coordinates. It worked very well in the former version. In this new version, the sPCA tells me that it has found duplicates. I have checked the coordinates with noise, and there are none. Not sure what’s going on.
> 
> Is there any similar report from other user?
> 
> I am looking forward you advices.
> 
> Thanks in advance 
> 
> Michael

**To do:** we need to be able to use spca on basic data.frames etc. Generic + methods will do.

**Comment by vmikk** [comment]
> Furthermore, I am using the jitter function to put some noise around my coordinates. It worked very well in the former version. In this new version, the sPCA tells me that it has found duplicates. I have checked the coordinates with noise, and there are none. Not sure what’s going on.

This is because a very aggressive behaviour of xyTable(xy) in chooseCN.R ([here](https://github.com/thibautjombart/adegenet/blob/e43f675f36d8770eee659481fd3ce2d7c5b0f2e3/R/chooseCN.R#L113)).
It will mark non-identical coordinates as duplicates and even adding a small noise will not help.
I faced the same problem and when I was sure that there are no duplicates of my coordinates I just modified chooseCN and forced DUPLICATE.XY to be always TRUE.

**Comment by romunov** [comment]
What do you suggest, do we follow some "existing template" from e.g. `dapc`?

**Comment by thibautjombart** [comment]
Yes, that was the plan. If you wanna give it a shot, brilliant, otherwise no worries I'll do it. 
@vmikk `xyTable` takes a `digits` argument which we could use. This said, the current behavior is sensible. For graphs 1-4, duplicate coordinates are a problem. Adding random noise will mean the graph itself will change, and so will any further result, including tests of spatial autocorrelation. Other graphs may be better in such cases.

**Comment by romunov** [comment]
@thibautjombart Just checking. `spca` is currently implemented in S3. Do we port it to S4?

**Comment by thibautjombart** [comment]
No, let's stick to S3 for now - simpler. Dz'at mean you're on it?
;)


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
https://github.com/thibautjombart
Twitter: @TeebzR <https://twitter.com/TeebzR>

**Comment by romunov** [comment]
Yes, I'm slowly working through the code, checking what needs to be "ported".

**Comment by thibautjombart** [comment]
I would do as in `dapc`:
- have a generic S3 
- have the method effectively implemented for `matrix`
- have a `data.frame` method dispatching to the `matrix` method
- for `genind` / `genpop`, extract data using `tab(...)` (with extra arguments to pass to `tab`) and dispatch to the `matrix` method

makes sense?

**Comment by romunov** [comment]
I'll look into this ASAP.

**Comment by thibautjombart** [comment]
:+1:

**Comment by romunov** [comment]
We need to make a decision on what kind of data will be accepted from data.frame. More specifically, how do we implement what to look for in a data.frame? So far I have a few ideas:

* ask user to provide only the subset of loci
* ask user to provide loci and coordinate columns - have prescribed coordinate names, like x/y
* ask user to provide loci and coordinate columns - have an extra argument to specify coordinate column names
* have a formula interface for data.frames. Using something like `formula(. ~ x + y)` we could use to extract coordinates from the data.frame. Very elegant solution, but having this only for data.frames may be confusing to R novice?

On a side not, I will have to implement a `scaleGen` method for `matrix`, too. :)

**Comment by thibautjombart** [comment]
I had not seen this. I would keep it simple, along the lines of what is done for dapc. data.frames are expected to be numeric values only and coerced to a numeric matrix. The dispatching will be done only on the first argument, not on the spatial coordinates or connection network.

**Comment by romunov** [comment]
Sorry for dragging this so long, but it's been extremely busy in the last few months. I dug into the code again and hit a snag.

In `spca`, there is a bit which scales the data (line [79 of scale.R](https://github.com/thibautjombart/adegenet/blob/master/R/scale.R#L79)). This can be only done if [ploidy is known](https://github.com/thibautjombart/adegenet/blob/master/R/handling.R#L75). Would it make sense to introduce yet another parameter - `freq`?

Sorry to be very nit-picky about this ( :) ), but I think we should think carefully about this for backwards compatibility and comparability for `genind` and `genpop` and also keep things slim down the line.

**Comment by thibautjombart** [comment]
No worries, I haven't had time for this myself. 
It's not such a big problem. Again, we can just use the same approach as for the DAPC:
https://github.com/thibautjombart/adegenet/blob/master/R/dapc.R

1. matrix method, the basic one, will be matrix + spatial info as input

2. data.frame method converts to matrix

3. the genind method will extract a matrix of allele frequencies `tab(x, freq = TRUE, NA.method="mean")` and then feed this to the matrix method (1)
 
4. same for genpop method

Makes sense?

**Comment by thibautjombart** [comment]
With a tweak: `center = TRUE` and `scale = FALSE` by default for `genind` and `genpop` objects, and `center = TRUE` and `scale = TRUE` by default for `matrix` and `data.frame`

**Comment by thibautjombart** [comment]
Done
