### ISSUE TITLE
users report missing argument for scaleGen

### ISSUE THREAD

**Issue by romunov** [thibautjombart/adegenet#144]
Stephen Attwood reported an error in help files for ˙`scaleGen`. It turns out that the method argument has been omitted in version [1.3-8](https://cran.r-project.org/src/contrib/Archive/adegenet/adegenet_1.3-8.tar.gz). @thibautjombart do you remember the logic for omitting this argument? Perhaps we could adjust the documentation (it's not clear to me what tutorial Stephen had in mind) to avoid any further collisions?

> Dear All
> 
> I am having a problem using scaleGen, so I tried going back to the adegenet tutorial and I get the same error:
> 
> data(microbov)
> obj <- genind2genpop(microbov)
> X1 <- scaleGen(obj)
> X2 <- scaleGen(obj,met="bin")
> Error in .local(x, ...) : unused argument (met = "bin")
> 
> I get the same error with my own data (I also tried method = "binary", method = "bin", etc)
> 
> X1 is as expected, but X2 is obviously not assigned
> 
> I have the following packages loaded:
> library(ade4)
> library(adegenet)
> library(spdep)
> library ("OpenStreetMap")
> library(ape)
> 
> Using adegenet 2.0.2 and R version 3.2.5 (2016-04-14); platform x86_64-pc-linux-gnu
> 
> If someone could suggest what I might have overlooked, that would be a great help - I am probably missing a package somewhere. I thought it would be a common problem, but I haven't found it on Google - perhaps the solution is so simple. At the moment it is eluding me.
> 
> Thank you.
> 
> Stephen

**Comment by thibautjombart** [comment]
Yes, this argument has been removed as it was not useful.
