### ISSUE TITLE
structure to genind not working, population labels not identified

### ISSUE THREAD

**Issue by AliciaAG** [thibautjombart/adegenet#146]
Hello!

I want to use adegenet with my microsatellite data base, but I stuck in the very first step!
when I try to convert my structure file into a genind object

![captura de pantalla 2016-06-27 12 56 03](https://cloud.githubusercontent.com/assets/17458245/16377579/18936b3a-3c67-11e6-81b7-4ab853607096.png)
 
the population labels are not read. It appear the individual labels instead. 

![captura de pantalla 2016-06-27 12 57 51](https://cloud.githubusercontent.com/assets/17458245/16377592/3418deee-3c67-11e6-8582-ce3f37802ef8.png)

I don't know what I am doing wrong -or how can I add the population labels later on (I have 150 populations)-, on the other hand, I' dont think I understand what "pop" means in 
read.structure(file, n.ind = NULL, n.loc = NULL, onerowperind = NULL,
               col.lab = NULL, col.pop = NULL, col.others = NULL,
               row.marknames = NULL, NA.char = "-9", **pop** = NULL, sep = NULL,
               ask = TRUE, quiet = FALSE)

... please, help, this is very frustrating!
Thank you in advance!
A.

**Comment by romunov** [comment]
See argument `col.pop`. In your case, I suspect it should be `col.pop = 1`.

Argument `pop` is designed if you already have population grouping (i.e. from SPCA or some other method).

**Comment by AliciaAG** [comment]
Thank you for your answer romunov, but I'm afraid that my column for the population labels is the column 2, the individual labels are placed in column 1. Maybe I should use consecutive numbers for the populations? or not include text in the individual labels? The first shortcut is my .str document, so it looks like this. The individual labels are text "inxxxx" and the population labels number of three digits, not consecutive, not ordered.

**Comment by romunov** [comment]
How you label shouldn't matter. I made a mistake by reading your `genind2df` output. Have you tried using `col.pop = 2` with satisfactory results?

**Comment by AliciaAG** [comment]
col.pop = 2 is what I did, it doesn't work. Maybe my .str file is not well written? it is a .prn file and I simply deleted the ".prn" part and write ".str" intead. The alleles are read, and the -9 values are replaced by NA, but the individual labels are placed as "pop" and the number of pops seems to be only one
![captura de pantalla 2016-06-27 16 16 35](https://cloud.githubusercontent.com/assets/17458245/16382442/16874a68-3c81-11e6-8727-787481f6ce37.png)

**Comment by romunov** [comment]
This is taking forever. Can you post a few lines of the file here so we can play around on our own?

**Comment by AliciaAG** [comment]
Of course! 
locus9   locus15   locus21   locusD3   locus24   locus20   Locus17   locus19
  in140      906        81        -9       133       205       105        97       128        -9
  in140      906        81        -9       133       205       107        99       128        -9
  in142      907        81        -9       133       205       105        97       128        -9
  in142      907        81        -9       133       205       105        97       128        -9
  in144      132        78       105       142       196        91        97       146       151
  in144      132        78       105       142       202        91        97       149       151
  in149      081        78       105       133       199        91        97       128       151
  in149      081        78       105       133       202        91        97       146       151
  in156      001        78        -9        -9       196        -9        97       131       163
  in156      001        78        -9        -9       199        -9        97       140       184
  in158      153        78       105       124       202        -9        97       146       151
  in158      153        78       105       124       202        -9        97       146       157
  in170      082        -9        97        -9       202        -9        97       131       157
  in170      082        -9        97        -9       208        -9        97       131       163
  in173      084        78        -9        -9       196        -9        97       128       154
  in173      084        78        -9        -9       196        -9        97       128       160
  in178      098        78        -9        -9       196        -9        97       128       157
  in178      098        78        -9        -9       199        -9        97       128       157
  in181      099        -9        -9        -9       196        -9        97       128       157
  in181      099        -9        -9        -9       196        -9        97       128       163
  in184      099        78       103        -9       196        91        97       128       151
  in184      099        78       103        -9       199        91        97       143       157
  in187      103        78        -9        -9       196        -9        97       128       148
  in187      103        78        -9        -9       202        -9        97       128       154
  in193      105        78       109       124       196        -9        97       146       154
  in193      105        78       109       124       196        -9        97       149       154
  in217      170        78       103       133       208        91        97       146       151
  in217      170        90       103       133       208        93        97       146       151

**Comment by AliciaAG** [comment]
objS <- read.structure("InPsinP.str", n.ind = 739, n.loc = 8, onerowperind = FALSE, 
                       col.lab = 1, col.pop = 2, row.marknames = 1, NA.char = "-9")

**Comment by AliciaAG** [comment]
Hello!

the scripts is still not working:S Everytime I have a warning message that says that labels are repeated, and still I don't find the way to include the population labels. I tried with a document where the alleles per locus where in a single row per sample, so "onerowperind = TRUE" (also I made it manually, by answering the questions that appear step by step in case it is not specified), and still the warning mesage appears.

objS <- read.structure("sinPop.str", n.ind = 739, n.loc = 8, onerowperind = TRUE, 
+                        col.lab = 1, col.pop = FALSE, col.others = FALSE, row.marknames = 1, NA.char = "-9")

 Converting data from a STRUCTURE .stru file to a genind object... 

Warning message:
In df2genind(X = X, pop = pop, ploidy = 2, sep = sep, ncode = ncode) :
  duplicate labels detected for some individuals; using generic labels
> genind2df(objS, sep="|")
     locus9 locus15 locus21 locusD3 locus24 locus20 Locus17 locus19
001 081|081    <NA> 133|133 205|205 105|107 097|099 128|128    <NA>
002 081|081    <NA> 133|133 205|205 105|105 097|097 128|128    <NA>
003 078|078 105|105 142|142 196|202 091|091 097|097 146|149 151|151
004 078|078 105|105 133|133 202|199 091|091 097|097 128|146 151|151
005 078|078    <NA>    <NA> 196|199    <NA> 097|097 131|140 163|184




I have also tried to make a genind object without the population labels (but still I have this warning message I pasted above) and convert it to a data frame and add a label with the population afterwards but when I have an error message also... 

pop(objS) <-rep (c('a','b'),700:38)
Error in rep(c("a", "b"), 700:38) : invalid 'times' argument

I'm quite desperated, please help!
A

**Comment by romunov** [comment]
@AliciaAG sorry this took so long. I'm busy at work and with a construction project on my plate at home, there's little time for "fun and games". :)

I tried importing your data and it would seem it goes through fine? I'm using adegenet version 2.0.2.

```r
library(adegenet)
xstring <- "ind mypop locus9 locus15 locus21 locusD3 locus24 locus20 Locus17 locus19
in140 906 81 -9 133 205 105 97 128 -9
in140 906 81 -9 133 205 107 99 128 -9
in142 907 81 -9 133 205 105 97 128 -9
in142 907 81 -9 133 205 105 97 128 -9
in144 132 78 105 142 196 91 97 146 151
in144 132 78 105 142 202 91 97 149 151
in149 081 78 105 133 199 91 97 128 151
in149 081 78 105 133 202 91 97 146 151
in156 001 78 -9 -9 196 -9 97 131 163
in156 001 78 -9 -9 199 -9 97 140 184
in158 153 78 105 124 202 -9 97 146 151
in158 153 78 105 124 202 -9 97 146 157
in170 082 -9 97 -9 202 -9 97 131 157
in170 082 -9 97 -9 208 -9 97 131 163
in173 084 78 -9 -9 196 -9 97 128 154
in173 084 78 -9 -9 196 -9 97 128 160
in178 098 78 -9 -9 196 -9 97 128 157
in178 098 78 -9 -9 199 -9 97 128 157
in181 099 -9 -9 -9 196 -9 97 128 157
in181 099 -9 -9 -9 196 -9 97 128 163
in184 099 78 103 -9 196 91 97 128 151
in184 099 78 103 -9 199 91 97 143 157
in187 103 78 -9 -9 196 -9 97 128 148
in187 103 78 -9 -9 202 -9 97 128 154
in193 105 78 109 124 196 -9 97 146 154
in193 105 78 109 124 196 -9 97 149 154
in217 170 78 103 133 208 91 97 146 151
in217 170 90 103 133 208 93 97 146 151"

writeLines(text = xstring, con = "gendata_pop_integer.stru")

objS <- read.structure("gendata_pop_integer.stru", n.ind = 14, n.loc = 8, onerowperind = FALSE, 
                       col.lab = 1, col.pop = 2, NA.char = "-9", ask = FALSE)

 Converting data from a STRUCTURE .stru file to a genind object... 

pop(objS)

 [1] 906 907 132 081 001 153 082 084 098 099 099 103 105 170
Levels: 906 907 132 081 001 153 082 084 098 099 103 105 170
```
