### ISSUE TITLE
Allele counts for diploid organisms

### ISSUE THREAD

**Issue by lilnet** [thibautjombart/adegenet#147]
I am trying to extract allele counts for each population by converting a genind to a genpop file using `genind2genpop`

What I obtained was
```
Population	3_11.01	3_11.02	6_12.02	6_12.01	7_10.02	7_10.01	
1	3	33	31	5	24	12
2	0	2	2	0	2	0
3	0	2	2	0	1	1
```
For some reason the alleles are separated into 2 parts.
Is there anyway to get allele counts of the allele as a whole instead of in 2 separate parts?

Many thanks!

**Comment by romunov** [comment]
Hi,

here's one way of summing frequencies over loci. The output below shows frequencies for all alleles or sums them.

```r
library(tidyr)

xy <- read.table(text = "Population  3_11.01 3_11.02 6_12.02 6_12.01 7_10.02 7_10.01 
1   3   33  31  5   24  12
                 2   0   2   2   0   2   0
                 3   0   2   2   0   1   1", header = TRUE, check.names = FALSE)


xy <- gather(xy, key = loci, value = freq, -Population)
xy$loci <- gsub("\\.[[:digit:]]*$", "", xy$loci)

aggregate(freq ~ loci + Population, FUN = c, data = xy)

  loci Population freq.1 freq.2
1 3_11          1      3     33
2 6_12          1     31      5
3 7_10          1     24     12
4 3_11          2      0      2
5 6_12          2      2      0
6 7_10          2      2      0
7 3_11          3      0      2
8 6_12          3      2      0
9 7_10          3      1      1

aggregate(freq ~ loci + Population, FUN = sum, data = xy)

  loci Population freq
1 3_11          1   36
2 6_12          1   36
3 7_10          1   36
4 3_11          2    2
5 6_12          2    2
6 7_10          2    2
7 3_11          3    2
8 6_12          3    2
9 7_10          3    2
```

**Comment by lilnet** [comment]
Hi romunov,

Thank you so much for suggesting the above, its great!
Although would it be possible to sum the frequencies by populations as follows - with one column per locus. As the downstream program would require such an input.
```
Population  3_11.01 3_11.02 6_12.02 6_12.01 7_10.02 7_10.01 
1   3   33  31  5   24  12
2   0   2   2   0   2   0
3   0   2   2   0   1   1
```

**Comment by romunov** [comment]
Does the output you present relate to your question? Are you after something like this?

```r
xya <- aggregate(freq ~ loci + Population, FUN = sum, data = xy)
spread(xya, key = loci, value = freq)

  Population 3_11 6_12 7_10
1          1   36   36   36
2          2    2    2    2
3          3    2    2    2
```

**Comment by lilnet** [comment]
Yes! I was looking for such a presentation.
The presentation of the output is specifically for another R program that requires it. So you could say indirectly it pertains to my question. Just that my dataset is a huge one consisting of ~20k loci, so manually calculating it isn't possible.
