### ISSUE TITLE
Using snpposi.plot to represent SNP density along a chromosome

### ISSUE THREAD

**Issue by HugoROliveira** [thibautjombart/adegenet#151]
Greetings:

I have typed 14442 SNP along wheat’s chromosome 3B. I want to use snpposi.plot to represent SNP density along the chromosome but smoothing it out, to visualise areas of the chromosome with high or low marker density, but keeping the nucleotide numbering in the figure. 
My data has two columns, one with the SNP number and the other with its numeric position in the chromosome (as shown below) 

> data <- read.table ("Chromosome3B.txt", header=TRUE)
> subdata<-data[1:5, 1:2]
> subdata

  SNPNumber Position
1         1   217861
2         2   217864
3         3   396049
4         4   396078
5         5   396093

Or

> str(data)
> 'data.frame':   14442 obs. of  2 variables:
>  $ SNPNumber: int  1 2 3 4 5 6 7 8 9 10 ...

I turned the second column into a vector

> vector<-data[,"Position"]

But when I try to plot it (considering a chromosome size of 900Mb) I get the following error message.

>  snpposi.plot(vector, 900000000)
> Error: cannot allocate vector of size 3.4 Gb

Help, please?

Thank you so much.

Hugo

**Comment by thibautjombart** [comment]
Good point. Should be improved as of revision bae29c8
