### ISSUE TITLE
error if no xy provided in /spca.R

### ISSUE THREAD

**Issue by RaSieb** [thibautjombart/adegenet#152]
Hey Thibaut
Thanks again for the great teaching last week! 
I think I found an error in spca.R while trying to use spatial weightings (matWeight argument) instead of xy coordinates (for network analyses). The function stops if no xy argument or obj$other$xy is provided, which should not be necessary with the matWeight (and cn) argument if I understand right.

Thanks

Raphi Sieber

**Comment by thibautjombart** [comment]
Well, it is not required in theory but used to plot the sPCA objects, so
required in practice.


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
https://github.com/thibautjombart
Twitter: @TeebzR <https://twitter.com/TeebzR>
