### ISSUE TITLE
Vignettes not packaged with adegenet

### ISSUE THREAD

**Issue by plantarum** [thibautjombart/adegenet#155]
Hi,

I notice that you're no longer distributing your vignettes as part of adegenet, but linking to them separately. They appear to be up-to-date and detailed, is there a reason you don't include them with the package? It would be nice to have them installed for times when I'm working offline.

Thanks!

Tyler

**Comment by thibautjombart** [comment]
Hi Tyler, 

CRAN was complaining about the doc taking too much space, so all the vignettes have been removed and are now distributed separately from the package.

Best
Thibaut

**Comment by plantarum** [comment]
Too bad! Still, it's great that you have provided such detailed docs.

Thanks,

Tyler
