### ISSUE TITLE
use a file connection for fasta2DNABin

### ISSUE THREAD

**Issue by rodney757** [thibautjombart/adegenet#162]
It would be nice if we could pass in a file connection to the fasta2DNABin method. Currently it only supports a file path

**Comment by thibautjombart** [comment]
Should be a fairly minor change. Do you have a specific use-case in mind / example we can work with? Or did you want to PR this?

**Comment by KlausVigo** [comment]
Hi @rodney757,  have you checked if `read.FASTA()` from ape would work in your case? @thibautjombart I am not sure if `read.FASTA` is still less memory efficient, but it is a lot faster. 

`
> library(ape)
> library(adegenet)

> myPath <- system.file("files/usflu.fasta",package="adegenet")
> 
> system.time(x1 <- fasta2DNAbin(myPath, quiet=TRUE))
   user  system elapsed 
  1.640   0.004   1.644 
> system.time(x2 <- fasta2DNAbin(myPath, quiet=TRUE, chunkSize=500))
   user  system elapsed 
  0.256   0.000   0.258 
> system.time(x3 <- as.matrix(read.FASTA(myPath)))
   user  system elapsed 
  0.000   0.000   0.002 
> 
> # The only distance is that fasta2DNAbin returns taxa names with leading white space.  
> 
> dimnames(x1)[[1]] <- trimws(dimnames(x1)[[1]])
> all.equal(x1, x3)
[1] TRUE
`

**Comment by rodney757** [comment]
@KlausVigo read.FASTA doesn't seem to support file connections either.

@thibautjombart My use case is accessing a fasta file within a zip. I would rather not unzip the file first, and prefer to just read the file. I can obtain a connection using

    unz("myZip.zip", "myFasta.fasta")

I'll see if I can find some time to make these changes

**Comment by thibautjombart** [comment]
OK, as it is rather specific (yet useful) I'll let you have a go and PR it if you have time. If you make the change, please add yourself in the DESCRIPTION as contributor after Klaus.
