### ISSUE TITLE
polyploid sPCA plot failure

### ISSUE THREAD

**Issue by chadsmith123** [thibautjombart/adegenet#169]
I have a polyploid data set with different ploidy levels for different samples (leafcutter ant fungus).

When plotting the spca object I get "arguments imply differing number of rows" and a multispati "There are only 21 positive factors" error. The eigenvalues decomposition plot does not appear. 

No error is reported when ploidy=5 is set for all samples. Removal of the first (UGM070310-06) or last (UGM070420-02) sample in the dataset also does not result in an error. I tried a subset of 20 samples that also included these two individuals and no error was produced. 

Thank you for your time, I'd love to use your program for this dataset!

[fung_boot_test_dput.txt](https://github.com/thibautjombart/adegenet/files/742688/fung_boot_test_dput.txt)

**Comment by thibautjombart** [comment]
Sorry about the delay. The sPCA has changed in the devel version - it is now a generic with methods for `genind`, `data.frame`, `matrix`. It should work with your data without issues, but if not please just post a reproducible example.

**Comment by thibautjombart** [comment]
Hi there, 
any development here? I will close this issue if not.
