### ISSUE TITLE
problem creating genlight object

### ISSUE THREAD

**Issue by alexandracarrier** [thibautjombart/adegenet#170]
Hello, I've encountered an issue when trying to create a genlight object:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘nLoc’ for signature ‘"try-error"’
In addition: Warning message:
In mclapply(1:nrow(input$gen), function(i) new("SNPbin", as.integer(input$gen[i,  :
  190 function calls resulted in an error

I have 190 individuals with SNP data as numeric values.

Command I use:
snp_genlight <- new("genlight", gen = locus, ind.names = ind, loc.names = loc, chromosome = chr)

I can't figure what is the problem... Thank you for your help.

Alexandra

[dapc.RData.zip](https://github.com/thibautjombart/adegenet/files/752729/dapc.RData.zip)

**Comment by romunov** [comment]
I am curious how was this solved?

**Comment by alexandracarrier** [comment]
Sorry, it was actually an error from me. My SNPs data which are stored in «locus» contained «-1» to represent missing data. I changed it to NAs instead and it worked.
