### ISSUE TITLE
FST on genlight object

### ISSUE THREAD

**Issue by guillaume-rs** [thibautjombart/adegenet#174]
Hi,

I would like to do FSTs analysis on a big set of SNPs.
I have loaded my data on a genlight object, but I can't find the way to do FST calculation for each SNP.
Is there a way to do that?

Thanks in advance,

Guillaume

**Comment by thibautjombart** [comment]
Did you close the issue because you found out a solution, lost interest, or decided to post of the forum?

**Comment by guillaume-rs** [comment]
I posted it on the forum.

2017-04-04 14:52 GMT+02:00 Thibaut Jombart <notifications@github.com>:

**Comment by thibautjombart** [comment]
Cool thx
