### ISSUE TITLE
adegenet/devtools installation error

### ISSUE THREAD

**Issue by JoseAAndres** [thibautjombart/adegenet#178]
I am working on the assignment of supplementary individuals to one of my previous DAPC analyses. Because the know issues with the predict.dapc of the repository version (2.0.1) I'd like to use the devol version of Adegenet. Unfortunately, my compilation fails because of the following error:  
invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLin site:lists.r-forge.r-project.org/pipermail/adegenet-forum/

ERROR: compilation failed for package ‘adegenet’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/adegenet’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/adegenet’

Following Thibaut's recommendations I did try installing devtools/devol-Adegenet  from my Xquartz (i.e. X11) using a vanilla R (3.4.0) session. Unfortunately, I still get the same error (attached file lines 25-26, lines 104-109).
Any suggestions?

**Comment by thibautjombart** [comment]
Can you please copy-paste the full output of
```
devtools::install_github("thibautjombart/adegenet")
```
and 
```
devtools::session_info()
```

**Comment by JoseAAndres** [comment]
Sorry,
I guess I forgot to attach the file... this is all I got.
[Devtools?devAdegenet_install.txt](https://github.com/thibautjombart/adegenet/files/952679/Devtools.devAdegenet_install.txt)
Let me know if you need anything else.

**Comment by knausb** [comment]
Have you tried:

http://tips.tutorialhorizon.com/2015/10/01/xcrun-error-invalid-active-developer-path-library-developer-commandline-tools-missing-xcrun/

**Comment by JoseAAndres** [comment]
I did have xcode-select version 2345.1 already installed. However in an act of faith I decided to re-install it. Wow, magic! I cannot really explain why, but it worked. I have already re-assigned all my individuals. Thanks!!

**Comment by thibautjombart** [comment]
Great, good to hear. Thanks for posting the issue - it may be useful to others.
