### ISSUE TITLE
Getting an error running haplogen 

### ISSUE THREAD

**Issue by shivamd** [thibautjombart/adegenet#179]
In the examples provided,

```
dat <- haploGen(seq.l=1e4, repro=function(){sample(1:4,1)}, gen.time=1, t.max=3)
```
Running the above, gives the following error. 

```
Error in as.matrix.DNAbin(as.DNAbin(character(0))) : 
  DNA sequences in list not of the same length.
```

Am I missing something?

**Comment by zkamvar** [comment]
This looks like it's originating in the ape package. From my limited knowledge of the haploGen function, it looks like it creates an empty DNAbin object to store the results in and converts it to a matrix.

My guess is that this USED to work up until 5 months ago, when ape 4.0 came out and a piece of code was changed to use a more efficient function ([original code], [changed code]):


```diff
-s <- unique(unlist(lapply(x, length)))
+s <- unique(lengths(x, use.names = FALSE))
```

@emmanuelparadis, do you know what would cause `as.matrix.DNAbin(as.DNAbin(character(0)))` to fail?

[original code]: https://github.com/cran/ape/blame/650e3dfdde5de98680ea96e0e3bc6e30f52a51b2/R/DNA.R#L109
[changed code]: https://github.com/cran/ape/blame/6f7033d8327bcce6c8a279fe7fffe84bfb1252ca/R/DNA.R#L111

**Comment by emmanuelparadis** [comment]
The two pieces of code behave differently in this situation:

```r
R> x <- as.DNAbin(character(0))
R> unlist(lapply(x, length))
[1] 0
R> lengths(x)
integer(0)
```
And the 2nd result makes sense since there is no list in the data:

```r
R> lengths(list(x))
[1] 0
```
This seems to give inconsistent behaviour though:

```r
R> x <- woodmouse[1, , drop = TRUE]
R> x
1 DNA sequence in binary format stored in a vector.

Sequence length: 965 

Base composition:
    a     c     g     t 
0.304 0.262 0.129 0.306
R> unlist(lapply(x, length))
[1] 965
R> lengths(x)
  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
.....
[963] 1 1 1
```
I'm going to have a closer look at it.

**Comment by emmanuelparadis** [comment]
Things seem a bit complicated. The problem is that `is.vector` does not return TRUE if there a class attribute (as explained in `?is.vector`). In practice, vectors of class "DNAbin" are rarely encountered, so this problem rarely arises. This may need some careful examination of all code related to DNA seqs in ape.

One solution on adegenet's side would be to use:

```r
as.matrix.DNAbin(as.DNAbin(matrix(character(0), 0, 0)))
```

**Comment by zkamvar** [comment]
Hi, I've created a patch for this in #180, but note that conversion to igraph appears to be broken at this moment.
