### ISSUE TITLE
New version of compoplot no longer takes character vectors for colors

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#186]
in adegenet 2.1.0, compoplot has change the `col` argument to `col.pal` and takes a palette function for generating colors. I have a function that will parse a character vector or a function with the population names here: https://github.com/grunwaldlab/poppr/blob/ae6cf80dde47775adf972e8c0e4a0966ccdad40b/R/internal.r#L1549-L1567

If we copy this function to adegenet, it can be used such that the user can specify either a color palette or a vector without error.

**Comment by thibautjombart** [comment]
Sounds cool to me. Want to PR it? ;)

**Comment by zkamvar** [comment]
Sure!
