### ISSUE TITLE
Error message with read.PLINK and extract.PLINKmap #94

### ISSUE THREAD

**Issue by tjsmyser** [thibautjombart/adegenet#188]
Thibaut,

I am reading through the comments described for issue #94, as I am encountering the same problems, but I do not seem to understand the solution. I am working with HD SNP data generated from a commercial Illumina bead array. I have successfully imported my genotypes into adegenet by first converting my *.ped and *.map files in PLINK, exporting a *.raw file, and then importing the *.raw file (code listed below) into adegenet.

a = read.PLINK("ASM_RefSet_RAW.raw", parallel = FALSE) 
I seem to be unable to import the corresponding chromosome and position information. I have attempted to use the following code without success. Any suggestions you may have would greatly be appreciated.

a = read.PLINK("ASM_RefSet_RAW.raw", parallel = FALSE, map.file = "ASM_RefSet_RAW.map")
Error message received =

Warning message:
In matrix(txt, ncol = 4, byrow = TRUE) :
  data length [29375] is not a sub-multiple or multiple of the number of rows [7344]
I have also tried:

chr_position = extract.PLINKmap("ASM_RefSet_RAW.map")
Error message received =

Error in factor(txt[ord, 1]) : object 'ord' not found
In addition: Warning message:
In matrix(txt, ncol = 4, byrow = TRUE) :
  data length [29375] is not a sub-multiple or multiple of the number of rows [7344]

I also imported my *.map file into PLINK and then exported the *.map file with --recode. The following code appear to work with no error messages returned, yet when I query the chromosome information with “ head(other(a),100) ” R returns NA for $chromosome and $position.

a = read.PLINK("ASM_RefSet_RAW.raw", parallel = FALSE, map.file = "MAP.map")

Again, any suggestions you may have would be greatly appreciated,
Tim

**Comment by thibautjombart** [comment]
This should be fixed via 4992cfa0f91a56f5b28ba84b168bbb3ebd7fb630

**Comment by thibautjombart** [comment]
As issue  #94 is fixed, I am assuming this one is too; re-open if not
