### ISSUE TITLE
Unable to install package adegenet

### ISSUE THREAD

**Issue by jgwieringa** [thibautjombart/adegenet#190]
I have been working with adegenet for a while in R on ubuntu 16.04. I ran into some computer issues and had to reinstall ubuntu and all programs. After doing so, I am unable to install adegenet in R. I have attempted to reinstall R multiple times with different suggestions on the way to do so. I have turned off the firewall on my computer, tested on multiple different networks and multiple different ubuntu computers. I am able to install on windows computers though. I then attempted to download the tar.gz adegenet but it is not compatible with current versions of R. I then attempted to install other packages and am able to do so, such as ggplot2 and ade4. I was wondering if you had any input as to what could be causing this issue.

Here are the error messages at the end:

/usr/lib/R/etc/Makeconf:159: recipe for target 'foreign-graphml.o' failed
make: *** [foreign-graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/jamin/R/x86_64-pc-linux-gnu-library/3.4/igraph’
ERROR: dependency ‘igraph’ is not available for package ‘adegenet’
* removing ‘/home/jamin/R/x86_64-pc-linux-gnu-library/3.4/adegenet’

The downloaded source packages are in
	‘/tmp/RtmpvmuCiy/downloaded_packages’
Warning messages:
1: In install.packages("adegenet") :
  installation of package ‘igraph’ had non-zero exit status
2: In install.packages("adegenet") :
  installation of package ‘adegenet’ had non-zero exit status

**Comment by thibautjombart** [comment]
Hi there, 
it is rather odd. Which version of R are you using?
can you try:
```
install.packages("igraph")
install.packages("adegenet", dep = TRUE)
```

**Comment by jgwieringa** [comment]
I am using R version 3.4.1. Although this was attempted with 3.2.3 prior to updating as well.

I attempted both commands you left and received the following:

install.packages ("igraph"):
/usr/lib/R/etc/Makeconf:159: recipe for target 'foreign-graphml.o' failed
make: *** [foreign-graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/jamin/R/x86_64-pc-linux-gnu-library/3.4/igraph’

The downloaded source packages are in
	‘/tmp/RtmpLhP1te/downloaded_packages’
Warning message:
In install.packages("igraph") :
  installation of package ‘igraph’ had non-zero exit status

install.packages("adegenet", dep = TRUE):
The downloaded source packages are in
	‘/tmp/RtmpLhP1te/downloaded_packages’
Warning messages:
1: In install.packages("adegenet", dep = TRUE) :
  installation of package ‘tkrplot’ had non-zero exit status
2: In install.packages("adegenet", dep = TRUE) :
  installation of package ‘igraph’ had non-zero exit status
3: In install.packages("adegenet", dep = TRUE) :
  installation of package ‘adehabitat’ had non-zero exit status
4: In install.packages("adegenet", dep = TRUE) :
  installation of package ‘adegenet’ had non-zero exit status
5: In install.packages("adegenet", dep = TRUE) :
  installation of package ‘pegas’ had non-zero exit status
6: In install.packages("adegenet", dep = TRUE) :
  installation of package ‘hierfstat’ had non-zero exit status

**Comment by romunov** [comment]
This is an `igraph` issue first. Perhaps you could try installing it straight off of [GitHub](https://github.com/igraph/rigraph)?

**Comment by thibautjombart** [comment]
Hm.. it looks like an issue with other packages, not adegenet-specific. I'm installing R 3.4.1 to see what's up

**Comment by thibautjombart** [comment]
May be related to https://stackoverflow.com/questions/45318188/getting-error-in-function-igraph-write-graph-graphml-while-installing-igrap

**Comment by jgwieringa** [comment]
I was able to install igraph from github, however adegenet is still showing a non-zero exit status after attempted installation.

**Comment by romunov** [comment]
With what error?

**Comment by jgwieringa** [comment]
Here is everything:

> install.packages("adegenet")
Installing package into ‘/home/jamin/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/src/contrib/adegenet_2.0.1.tar.gz'
Content type 'application/x-gzip' length 1634386 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package ‘adegenet’ ...
** package ‘adegenet’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c GLfunctions.c -o GLfunctions.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c adesub.c -o adesub.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c monmonier-utils.c -o monmonier-utils.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sharedAll.c -o sharedAll.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c snpbin.c -o snpbin.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o adegenet.so GLfunctions.o adesub.o monmonier-utils.o sharedAll.o snpbin.o -L/usr/lib/R/lib -lR
installing to /home/jamin/R/x86_64-pc-linux-gnu-library/3.4/adegenet/libs
** R
** data
** inst
** preparing package for lazy loading
Warning: S3 methods ‘[.fun_list’, ‘[.grouped_df’, ‘all.equal.tbl_df’, ‘anti_join.data.frame’, ‘anti_join.tbl_df’, ‘arrange.data.frame’, ‘arrange.default’, ‘arrange.grouped_df’, ‘arrange.tbl_df’, ‘arrange_.data.frame’, ‘arrange_.tbl_df’, ‘as.data.frame.grouped_df’, ‘as.data.frame.rowwise_df’, ‘as.data.frame.tbl_cube’, ‘as.data.frame.tbl_df’, ‘as.table.tbl_cube’, ‘as.tbl.data.frame’, ‘as.tbl.tbl’, ‘as.tbl_cube.array’, ‘as.tbl_cube.data.frame’, ‘as.tbl_cube.matrix’, ‘as.tbl_cube.table’, ‘as_data_frame.grouped_df’, ‘as_data_frame.tbl_cube’, ‘auto_copy.tbl_cube’, ‘auto_copy.tbl_df’, ‘cbind.grouped_df’, ‘collapse.data.frame’, ‘collect.data.frame’, ‘common_by.NULL’, ‘common_by.character’, ‘common_by.default’, ‘common_by.list’, ‘compute.data.frame’, ‘copy_to.DBIConnection’, ‘copy_to.src_local’, ‘default_missing.data.frame’, ‘default_missing.default’, �� [... truncated]
Error in library.dynam(lib, package, package.lib) : 
  shared object ‘dplyr.so’ not found
ERROR: lazy loading failed for package ‘adegenet’
* removing ‘/home/jamin/R/x86_64-pc-linux-gnu-library/3.4/adegenet’

The downloaded source packages are in
	‘/tmp/RtmpM88BJR/downloaded_packages’
Warning message:
In install.packages("adegenet") :
  installation of package ‘adegenet’ had non-zero exit status
>

**Comment by romunov** [comment]
For some reason some dependencies have not been met. Try installing `dplyr`.

**Comment by thibautjombart** [comment]
Current checks suggest this is not the rule:
https://cran.r-project.org/web/checks/check_results_adegenet.html
I can install *adegenet* fine on R-3.4.1 on my version of Ubuntu 17.04

**Comment by jgwieringa** [comment]
I am not sure what happened among all of that, but if I downloaded dplyr from github, adegenet will now install. Thank you all for the help. I appreciate it greatly. There must be a bug in dplyr that wasn't fixed in the CRAN mirror yet.

**Comment by thibautjombart** [comment]
Great

**Comment by zkamvar** [comment]
FWIW I've noticed issues installing packages when new versions of dependencies are updated. In this case, the package *tibble* (imported by *dplyr*) was updated yesterday. 

You are also using a local mirror, and these can be a few hours to a few days late in updating packages. You may want to try using the RStudio cloud as a repo source

```r
install.packages("adegenet", repos = "https://cran.rstudio.com")
```

Glad to hear that the issue was solved! 👍
