### ISSUE TITLE
export_to_mvmapper add to R help

### ISSUE THREAD

**Issue by jrdupuis** [thibautjombart/adegenet#195]
Add a couple lines to the R help page so that the final write.csv step is included after "head(out)" in each of the two examples (dapc and spca). Basically, this would make it more-or-less match the help page of our deployed version of the web app: 
http://ctahr-peps.colo.hawaii.edu/help

**Comment by jrdupuis** [comment]
Also, we've moved around the main repo to our main project page, so the R help page also needs to be updated. The "Details" and "See Also" sections should read:

mvmapper can is available at: https://popphylotools.github.io/mvMapper/

**Comment by thibautjombart** [comment]
Done via 0ce20ccd1235b8600851588ccd4a413ea2d2ca38
The function still returns the `data.frame` but now also by default write result to a .csv file.
URL updated too.
