### ISSUE TITLE
export_to_mvmapper link update

### ISSUE THREAD

**Issue by jrdupuis** [thibautjombart/adegenet#196]
One more url in the R help page needs to be changed from: 

`mvmapper can be found at: https://github.com/genomeannotation/mvMapper`    (in the "details" section)

to:

`mvmapper is available at: https://popphylotools.github.io/mvMapper/`

**Comment by thibautjombart** [comment]
Done via ff2ba9374d4575812ef42c552b55f53eeb67ea01
