### ISSUE TITLE
`spca_randtest` in devel package

### ISSUE THREAD

**Issue by snook91901** [thibautjombart/adegenet#198]
[oc_spca.gz](https://github.com/thibautjombart/adegenet/files/1360733/oc_spca.gz)
Hi,

I'm trying to get to the bottom of an error running the new spca_randtest function in the development package. 

The error I receive is:
Error in 1:nrow(obj) : argument of length 0

I looked to see if the the nrow function worked on either the spca object or the genind obj that I ran the spca on:

>nrow(oc_spca)
NULL

>nrow(oc.gid)
NULL

I also attempted to run spca_randtest on the example spca data, spcaIllus, and was successful.

Can anyone venture a guess as to what's happening here? Copy of code is below and spca object is attached

Thanks,
David

## SPCA rand_test
```{r OC, eval = F}
oc_spca<-spca(oc.gid, xy = xy_oc_jitter)
oc_rand<-spca_randtest(oc_spca, nperm = 10)
```
>Error in 1:nrow(obj) : argument of length 0

[oc.Rdata.gz](https://github.com/thibautjombart/adegenet/files/1360750/oc.Rdata.gz)

**Comment by thibautjombart** [comment]
I cannot reproduce your spca as `oc.gid` is missing. However your spca is the problem. The component `$tab` is missing.

**Comment by snook91901** [comment]
Thanks. This took care of my issue.
