### ISSUE TITLE
release 2.1.0

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/adegenet#199]
@zkamvar I am using this to list stuff to do before release

- [x] pass check 
- [x] register C routines
- [x] register S3methods
- [x] test tuto basics
- [x] test tuto dapc
- [x] test tuto spatial -> fixed
- [x] test tuto genomics
- [x] test tuto strata
- [x] test tuto snapclust
- [x] check https://github.com/thibautjombart/adegenet/issues/200 -> fixed

... ?

**Comment by zkamvar** [comment]
- [ ] register C routines

Other than that, I think that's about it for this release. All other corner cases can be fixed later and released as a patch.

**Comment by thibautjombart** [comment]
@zkamvar C routines were registered already. Some S3method weren't and have been added. Passing the check on current stable now; being checked on rocker/r-devel 
I will also check that the tutorials are still compiling okay.
Anything else?

**Comment by thibautjombart** [comment]
C routines fixed at 78125368ad0618886b58ef66d2b2c6afb51c5dd8

**Comment by thibautjombart** [comment]
See https://github.com/thibautjombart/adegenet/issues/201 for `rupica`. I'm on it.

**Comment by thibautjombart** [comment]
Submitted!

**Comment by thibautjombart** [comment]
Done! On CRAN now. Current devel is now officially 2.1.1
Thanks team @zkamvar =D
