### ISSUE TITLE
Remove *.o and *.so files from src

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#2]
The *.o and *.so files prevent installation from source using `install_github("thibautjombart/adegenet/pkg")`.

Here's the error msg:

    Error in dyn.load(dllfile) :
      unable to load shared object '/Users/zhian/Documents/adegenet/pkg/src/adegenet.so':
      dlopen(/Users/zhian/Documents/adegenet/pkg/src/adegenet.so, 6): no suitable image found.  Did find:
	    /Users/zhian/Documents/adegenet/pkg/src/adegenet.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

removing these files will allow installation for users who have a C compiler.

**Comment by zkamvar** [comment]
Fixed in ba7e5ff17edf272849c925a10c1d0214e6b364b5

**Comment by thibautjombart** [comment]
Awesome, thanks for the fix!
Cheers
Thibaut

**Comment by romunov** [comment]
I'm curious, would putting `*.o` and `*.so` files in `.Rbuildignore` also work?

**Comment by thibautjombart** [comment]
Never used it but I would think so.
I was actually considering using it to put the content of pkg/ at the root,
and ignore the 'tutorials' folder.

**Comment by thibautjombart** [comment]
Feel free to try if you fancy ;)

**Comment by romunov** [comment]
I would vote +1 for putting package into the root of `/adegenet` and add `tutorials` in one of the folders in the package. Using `.Rbuildignore` will ignore this folder during compiling/checking. I use that for test cases and sandbox folders.

**Comment by thibautjombart** [comment]
Yes, and then we can use Travis to monitor the package! Sorted.
Zhian, do you want to give it a go or shall I?

**Comment by zkamvar** [comment]
I can certainly give it a go. I'll pull a new branch to test things out.

**Comment by thibautjombart** [comment]
Uups sorry it's done - I got excited ;)

**Comment by thibautjombart** [comment]
Also added a readme and Travis.
