### ISSUE TITLE
Reading population info in read.structure

### ISSUE THREAD

**Issue by Daxide** [thibautjombart/adegenet#200]
I tried to convert the HGDP file into genind object and then into genpop but I get an object with only 1 population, instead of 50+ pops.

Using the HGDP file: 
[https://rosenberglab.stanford.edu/data/huangEtAl2011/HuangEtAl_2011-GenetEpi.zip ](url)
Following the instructions on the manual, I tried to assign correct labels based on the Readme file (https://rosenberglab.stanford.edu/data/huangEtAl2011/huangEtAl2011snpdata_readme)
`Mydata=read.structure("unphased_HGDP+India+Africa_2810SNPs-regions1to36.stru", onerowperind = FALSE,col.lab = 8,col.pop = 2,row.marknames = 1,n.ind = 1107, n.loc = 2810, ask = FALSE)
Mydata_pop=genind2genpop(Mydata)
`

However, I get a file with only 1 population. 

head(Mydata_pop)
/// GENPOP OBJECT /////////

 // 1 population; 2,810 loci; 7,217 alleles; size: 1.5 Mb

 // Basic content
   @tab:  1 x 7217 matrix of allele counts
   @loc.n.all: number of alleles per locus (range: 2-4)
   @loc.fac: locus factor for the 7217 columns of @tab
   @all.names: list of allele names for each locus
   @ploidy: ploidy of each individual  (range: 2-2)
   @type:  codom
   @call: .local(x = x, i = i, j = j, drop = dro

This is obviously wrong since there are 50+ populations.

**Comment by thibautjombart** [comment]
I cannot reproduce this issue. I have:
```
> library(adegenet)
Loading required package: ade4

   /// adegenet 2.1.0 is loaded ////////////

   > overview: '?adegenet'
   > tutorials/doc/questions: 'adegenetWeb()' 
   > bug reports/feature requests: adegenetIssues()


> Mydata=read.structure("unphased_HGDP+India+Africa_2810SNPs-regions1to36.stru", onerowperind = FALSE,col.lab = 8,col.pop = 2,row.marknames = 1,n.ind = 1107, n.loc = 2810, ask = FALSE) 

 Converting data from a STRUCTURE .stru file to a genind object... 

Warning message:
In df2genind(X = X, pop = pop, ploidy = 2, sep = sep, ncode = ncode) :
  duplicate labels detected for some individuals; using generic labels
> Mydata
/// GENIND OBJECT /////////

 // 1,107 individuals; 2,810 loci; 7,217 alleles; size: 32.1 Mb

 // Basic content
   @tab:  1107 x 7217 matrix of allele counts
   @loc.n.all: number of alleles per locus (range: 2-4)
   @loc.fac: locus factor for the 7217 columns of @tab
   @all.names: list of allele names for each locus
   @ploidy: ploidy of each individual  (range: 2-2)
   @type:  codom
   @call: read.structure(file = "unphased_HGDP+India+Africa_2810SNPs-regions1to36.stru", 
    n.ind = 1107, n.loc = 2810, onerowperind = FALSE, col.lab = 8, 
    col.pop = 2, row.marknames = 1, ask = FALSE)

 // Optional content
   @pop: population of each individual (group size range: 6-45)
> Mydata_pop=genind2genpop(Mydata)


Mydata_pop=genind2genpop(Mydata)

 Converting data from a genind to a genpop object... 

...done.

> 
> Mydata_pop
/// GENPOP OBJECT /////////

 // 63 populations; 2,810 loci; 7,217 alleles; size: 3.3 Mb

 // Basic content
   @tab:  63 x 7217 matrix of allele counts
   @loc.n.all: number of alleles per locus (range: 2-4)
   @loc.fac: locus factor for the 7217 columns of @tab
   @all.names: list of allele names for each locus
   @ploidy: ploidy of each individual  (range: 2-2)
   @type:  codom
   @call: genind2genpop(x = Mydata)

 // Optional content
   - empty -
> 
```

**Comment by thibautjombart** [comment]
Maybe update to current devel version of adegenet and try again?

**Comment by Daxide** [comment]
Ok it works. I had to update the R version from 3.4.1 to 3.4.2 and
re-install adegenet. I thought I already had adegenet devel so I guess it's
the R update that did the trick! Thanks for you rhelp!

Davide

**Comment by thibautjombart** [comment]
Great
