### ISSUE TITLE
Snapclust - NaNs produced for $proba

### ISSUE THREAD

**Issue by SheaML** [thibautjombart/adegenet#221]
Hello,

I'm following up on my email yesterday to the listserv. Snapclust runs and converges successfully, but only NaNs are produced for the membership probabilities. I thought it might have to do with missing data, but the example .vcf (attached) has no missing data. Thanks again for having a look. 

Example input:
[myvcf.vcf.zip](https://github.com/thibautjombart/adegenet/files/1679650/myvcf.vcf.zip)

Example code:
```
library(vcfR)
library(adegenet)
TRS.G100<-read.vcfR("myvcf.vcf")
TRS.G100.genind<-vcfR2genind(TRS.G100)
snapclust(TRS.G100.genind,k=2)
```

**Comment by thibautjombart** [comment]
Thanks for the example. I am looking into this. This is a numerical precision problem, and not so trivial as it might seem. I am working on a fix now. Besides group membership probabilities, results should be alright.

**Comment by thibautjombart** [comment]
Some details on what's happening; because of the large dataset, the log-likelihood values (summed over loci) grow larger than the computer can accommodate:
```
  oberonS6_SML158 ornatus1_JJW627 ornatus1_JJW628p1 ornatus2_JJW671p1
1        6567.238        4150.080          4379.029          4481.868
2        3720.171        6797.265          6957.091          6849.421
  ornatus2_JJW672 ornatus3_JJW673 ornatus3_JJW676p1 ornatus4_JJW677p1
1        4566.624        4346.029          4386.338          4554.345
2        7254.575        7168.371          7274.206          7334.296
  ornatus5_NM167p1 ornatus5_NM173p1 ornatus6_NM175p1 ornatus6_NM178p1
1         4391.679         4256.970         4475.760         4755.459
2         7155.643         7046.313         7223.796         7392.320
  ornatusJAM_JAM652 ornatusS1_SML128 ornatusS1_SML129 ornatusS2_SML132
1          4020.500         4037.702         4321.740          4338.85
2          6670.609         6461.361         6941.619          7046.76
  ornatusS3_SML134 ornatusS3_SML136
1         4341.298         4253.111
2         7085.348         6878.461
```
needs to be exponentiated to compute group membership probabilities, which here gives:
```
  oberonS6_SML158 ornatus1_JJW627 ornatus1_JJW628p1 ornatus2_JJW671p1
1             Inf             Inf               Inf               Inf
2             Inf             Inf               Inf               Inf
  ornatus2_JJW672 ornatus3_JJW673 ornatus3_JJW676p1 ornatus4_JJW677p1
1             Inf             Inf               Inf               Inf
2             Inf             Inf               Inf               Inf
  ornatus5_NM167p1 ornatus5_NM173p1 ornatus6_NM175p1 ornatus6_NM178p1
1              Inf              Inf              Inf              Inf
2              Inf              Inf              Inf              Inf
  ornatusJAM_JAM652 ornatusS1_SML128 ornatusS1_SML129 ornatusS2_SML132
1               Inf              Inf              Inf              Inf
2               Inf              Inf              Inf              Inf
  ornatusS3_SML134 ornatusS3_SML136
1              Inf              Inf
2              Inf              Inf
```
And proba are then not defined. The workaround does the following:
- find the min and max values to allow for log-likelihoods given the computer precision
- if needed, rescale log-likelihoods on this new range (done for each individual separately)
- issue a message if this happens and approximates group membership probas

**Comment by SheaML** [comment]
Thanks Thibaut, good luck with the troubleshooting. I can confirm that the
group assignments make sense.

**Comment by thibautjombart** [comment]
Should be fixed via:
8d23c9284ef13c8c8430b03e11a098ac0db532e3

Can you give it a try? 
```
devtools::install_github("thbautjombart/adegenet")
library(adegenet)
...
```

**Comment by SheaML** [comment]
Indeed, I get membership probabilities now, and the warning message re:
large dataset syndrome.

Thanks!

**Comment by thibautjombart** [comment]
Good. I uncovered another issue but fixed now.

**Comment by jdpalacio** [comment]
Hi Thibaut,

I have same issue here, I am getting the "large dataset syndrome"

Two scenarios:
1. With few number of samples (27) but a lot of markers (~13k), I got the warming, but still it brings the membership probability, but just after one interaction...

2. For several samples (423) and a lot of markers (~18k), I got the membership probability for most of them, but not for all (77).

BTW, I am having computational issues running structure with 50k burnin and 100k MCMC... 

Thanks a lot Thibaut for adegenet suit of tools!

**Comment by zkamvar** [comment]
Thinking out loud here, but I wonder if this could be iterated over random subsets or windows of loci. This would solve the large K issue and give you a way of representing the uncertainty.

**Comment by thibautjombart** [comment]
I like this idea. This was actually the last concern of one of the referees, and something I had suggested too. There will be issues though, such as matching group labels etc. But could be interesting, and probably material for a paper too.

**Comment by Erythroxylum** [comment]
Hi Thibaut,

Thanks for producing the adegenet package! Are there plans to address this problem with summation of log-likelihoods issues in future versions?
