### ISSUE TITLE
repool and hybridize assume ploidy vector of length 1. Problem with df2genind

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#23]
Coming from the repool examples:

```r
zebler <- hybridize(temp$Salers, temp$Zebu, n=40)
Error in `colnames<-`(`*tmp*`, value = c("167", "171", "173", "175", "177",  : 
  length of 'dimnames' [2] not equal to array extent
In addition: Warning messages:
1: In if (x1@ploidy%%2 != 0) stop("not implemented for odd levels of ploidy") :
  the condition has length > 1 and only the first element will be used
2: In if (x2@ploidy != x1@ploidy) stop("not implemented for genotypes with different ploidy levels") :
  the condition has length > 1 and only the first element will be used
```

Repooling populations. 

```r
repool(temp$Somba, temp$Zebu)
 Error in df2genind(tab, pop = pop, ploidy = x[[1]]@ploidy, type = x[[1]]@type) : 
  Not enough information to convert data: please indicate the separator (sep=...) or the number of characters coding an allele (ncode=...) 
```

**Comment by thibautjombart** [comment]
I'm on it.

**Comment by thibautjombart** [comment]
Repool example works fine for me as of c54e6423e9f9432
See: 
```r
> ?repool
>   data(microbov)
     temp <- seppop(microbov)
     names(temp)
    
  data(microbov)
>      temp <- seppop(microbov)
>      names(temp)
 [1] "Borgou"          "Zebu"            "Lagunaire"       "NDama"          
 [5] "Somba"           "Aubrac"          "Bazadais"        "BlondeAquitaine"
 [9] "BretPieNoire"    "Charolais"       "Gascon"          "Limousin"       
[13] "MaineAnjou"      "Montbeliard"     "Salers"         
>     
>   ## hybridize salers and zebu -- nasty cattle
     zebler <- hybridize(temp$Salers, temp$Zebu, n=40)
     zebler
   
  ## hybridize salers and zebu -- nasty cattle
>      zebler <- hybridize(temp$Salers, temp$Zebu, n=40)
>      zebler

   #####################
   ### Genind object ### 
   #####################
- genotypes of individuals - 

S4 class:  genind
@call: hybridize(x1 = temp$Salers, x2 = temp$Zebu, n = 40)

@tab:  40 x 373 matrix of genotypes

@ind.names: vector of  40 individual names
@loc.names: vector of  30 locus names
@loc.nall: number of alleles per locus
@loc.fac: locus factor for the  373 columns of @tab
@all.names: list of  30 components yielding allele names for each locus
@ploidy:  2
@type:  codom

Optional contents: 
@pop:  factor giving the population of each individual
@pop.names:  factor giving the population of each individual

@other: - empty -

>    
>    nastyCattle <- repool(microbov, zebler)
     nastyCattle
   nastyCattle <- repool(microbov, zebler)
>      nastyCattle

   #####################
   ### Genind object ### 
   #####################
- genotypes of individuals - 

S4 class:  genind
@call: repool(microbov, zebler)

@tab:  744 x 373 matrix of genotypes

@ind.names: vector of  744 individual names
@loc.names: vector of  30 locus names
@loc.nall: number of alleles per locus
@loc.fac: locus factor for the  373 columns of @tab
@all.names: list of  30 components yielding allele names for each locus
@ploidy:  2
@type:  codom

Optional contents: 
@pop:  factor giving the population of each individual
@pop.names:  factor giving the population of each individual

@other: - empty -
```

**Comment by thibautjombart** [comment]
Forget - new version was installed for the wrong R version ':-/

**Comment by thibautjombart** [comment]
The problem was deeper than just a ploidy issue. Columns were reordered after the levels of x@loc.fac, which should be exactly equal to x@loc.names, but were not. Seppop seems the culprit (other issue raised, I'm on it too). New procedure should be more fool-proof for malformed objects.

**Comment by gclongo** [comment]
I'm getting an similar error trying to use repool. I searched the forum and this seemed to be the most similar issue I could find. 

I have a large genid with 2107 loci, 544 individuals, and 31 populations. Certain populations are missing loci that are found in other populations.

I want to run some analyses on specific populations in subgroups so I first use

> ling_pops <- seppop(obj)

This seems to perform as expected as every pop has the correct number of loci (2107) although many pops have missing data for lots of loci. 

I also ran seppop with the drop flag to see it that drops loci from pops when they are absent and it does

> Ling_pops_dt <- seppop(obj, drop=TRUE)

loci counts per population range from 1289 to 2072

I am having an issue trying to repool populations specifically with low loci counts and it seems like it has to do with missing data creating a new ploidy? I get the following warning when running repool

> cluster_2 <- repool(ling_pops$SOCA_LOS_OB, ling_pops$SOCA_SBA_SBC, ling_pops$SOCA_SDG)

In df2genind(tab, ploidy = newPloidy, type = x[[1]]@type, sep = "/") :
  entirely non-type marker(s) deleted
  
Has anybody had this issue and figured out a way to deal with it?

**Comment by zkamvar** [comment]
Hi,

You are trying to repool populations that have low loci counts. During the repool, loci with entirely missing data are dropped because that's the default behavior of df2genind. 

What you are seeing is normal behavior. The reason you are seeing  `df2genind(tab, ploidy = newPloidy, type = x[[1]]@type, sep = "/")` is because when R throws a warning, it will tell you what command generated the warning. In this case, since the final part of repool involves calling df2genind, you are seeing that call. No ploidies are harmed in repool.

**Comment by gclongo** [comment]
Hi Zhian,

Thank for you for such a quick reply. What you said makes senses.

However when I try to repool cluster_1, which now has fewer loci, with a subset of other populations from `obj` that did not have missing loci, I am denied.

> cluster_1_2 <- repool(cluster_2, cluster_1)
Error in table(temp) : all arguments must have the same length

Is there an obvious work around I'm missing or is this not possible.

Again, thanks for such a quick reply. Much appreciated.

**Comment by zkamvar** [comment]
The reason why repool fails here is because you are missing loci in cluster_1, and repool needs all alleles to match exactly. 

Is there a reason why you don't want to repool all of these at once?

**Comment by gclongo** [comment]
Gotcha. Well I wanted to run analyses on cluster 1 and 2 independently and then on them combined but now its clear that I can just repool separately. Thanks for your help!
