### ISSUE TITLE
seploc used arguments

### ISSUE THREAD

**Issue by tunaloveheart** [thibautjombart/adegenet#233]
Hey All 

Just trying to use the seploc function and testing it on microbov. 

seploc(microbov, block.size=600, random=TRUE)
Error in .local(x, ...) : 
  unused arguments (block.size = 600, random = TRUE)

Am I doing something wrong? The documentation lists these arguments. 

I am using adegenet_2.1.1

Regards
D

**Comment by zkamvar** [comment]
Hello,

`microbov` is a genind object containing 704 cattle genotyped over 30 SSR loci. The arguments `block.size` and `random` do not work for genind objects. If you remove these arguments, the function will work.

To elaborate a bit more: Adegenet uses two different data classes (called S4 objects) to store genetic data, genind and genlight. The genind class consists of a matrix of allele counts while the genlight class is optimized to handle thousands of SNP markers, storing the data in a more compressed form. 

The function `seploc()` works for both of these objects, but has different arguments based on what object you have. When you see the help page, it will show you what arguments are available for seploc on genind objects:

```r
     ## S4 method for signature 'genind'
     seploc(x,truenames=TRUE,res.type=c("genind","matrix"))
     ## S4 method for signature 'genpop'
     seploc(x,truenames=TRUE,res.type=c("genpop","matrix"))
     ## S4 method for signature 'genlight'
     seploc(x, n.block=NULL, block.size=NULL, random=FALSE,
            parallel=FALSE, n.cores=NULL)
```

Hope that helps!

Zhian

**Comment by zkamvar** [comment]
Seeing as there is no response, I'll assume that the issue can be closed.
