### ISSUE TITLE
CATS

### ISSUE THREAD

**Issue by rdecamp** [thibautjombart/adegenet#237]
Hi, here are some suggestions for the showmekittens() function:
- Classic compilation of cats knocking things down: https://www.youtube.com/watch?v=izRZxhqfk0Y
-  Oriental Shorthair Honking: https://www.youtube.com/watch?v=2J1ynsuWcNQ
- A kitty with a special meow: https://www.youtube.com/watch?v=w7x_lWJNnNg
- Scared Goblin makes a funny noise: https://www.youtube.com/watch?v=LtNrf4wsy_U
- Not cats per se, but two boys from the Paris Boy's Choir meowing is enough to brighten anyone's day: https://www.youtube.com/watch?v=gMdn0ezJxUE

**Comment by thibautjombart** [comment]
Brilliant! :) 

Would you like to PR these? If so, can you please also add yourself as a contributor to the `DESCRIPTION` file?

**Comment by rdecamp** [comment]
Hi! I added myself as a contributor in the description file, anything else I need to do?

**Comment by thibautjombart** [comment]
Good. And yes, left to do:
- add the URLs to the function
- make a pull request
Thanks! ;)
