### ISSUE TITLE
Remove dependency on genetics / re-implement HWE test

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/adegenet#24]
I think current dependency is merely for HWE test, which is easy enough to re-implement / remove. Need to check if pegas or hierfstat implements it with @emmanuelparadis and @jgx65 . If so, just move the feature from adegenet -> pegas / hierfstat

**Comment by emmanuelparadis** [comment]
pegas has `hw.test` accepting all levels of ploidy

**Comment by thibautjombart** [comment]
Sounds great. I'll have a look!

**Comment by thibautjombart** [comment]
//following from https://github.com/thibautjombart/adegenet/issues/20#issuecomment-86343846
**HW test in adegenet & pegas**

In practice that means we would move HWE.test.genind to pegas. Options I can see:
1) move HWE.test.genind to pegas: 
    - pro: backward compatibility and no feature loss for the user as long as pegas is used with adegenet
    - cons: you end up with two procedures in pegas for HWE
2) remove HWE.test.genind, modify hw.test to replicate functionalities
    - pro: clearer for the user, just one function to use; hw.test gains new functionalities (and may also become a generic? though it doesn't have to)
    - cons: no backward compatiblity

I think I am leaning towards 2) more. If adegenet's new version starts from a clean slate, then loosing a function or two is not the end of the world. I'm happy to modify pegas's function too. Only changes include i) genind inputs (trivial with your as.loci) ii) have the option of separate tests for different populations. 

@emmanuelparadis What do you think?

**Comment by emmanuelparadis** [comment]
I agree that 1) is not ideal cause the generic HWE.test() is defined in genetics. So let's go for 2). Maybe it's best to make hw.test() generic so you'll implement more easily the specificities of genind objects.

**Comment by thibautjombart** [comment]
If good for you, this is good for me. Shall I fork/pull request and let you
know when I have something working?

**Comment by emmanuelparadis** [comment]
Yes.

**Comment by zkamvar** [comment]
Noticed these notes in check:

```r
genind2genotype : f2: no visible global function definition for
  ‘as.genotype’
genind2genotype: no visible global function definition for
  ‘makeGenotypes’
```

Should we remove this function as we are not going to be depending on genetics anymore?

**Comment by thibautjombart** [comment]
Yes, this is still on my todo list, but taking the WE off ;)

**Comment by thibautjombart** [comment]
Done as of ef3d5a09e67a205
