### ISSUE TITLE
scatter dapc clustering issues

### ISSUE THREAD

**Issue by nperry44** [thibautjombart/adegenet#240]
Hello,
I've been trying to do a PCA on a set of data that I've been working with. However, when I run the PCA, the outputted graph just shows the three clusters. I would like it to show the thirty individuals around the clusters that they are a part of. The code I have written is:

```r
obj4 <- read.structure("/home/nblock/Documents/Willet_practice/Tringa_semipalmatus_adegenet_all.stru", n.ind=30)
grp <- find.clusters(obj4, max.n.clust = 4)
##Retaining 29 PCs, 2 clusters
dapc14 <- dapc(obj4, grp$grp)
##Retaining 29 PCs, 2 discriminant
scatter(dapc14)
```

So, I want to keep the clusters, but I also want to show the individuals.
Thanks!

**Comment by zkamvar** [comment]
Hello,

A point of clarification: DAPC is not PCA. If you haven't done so, I would suggest reading the DAPC tutorial: https://github.com/thibautjombart/adegenet/wiki/Tutorials

DAPC is sensitive to over-fitting, so if you choose clusters with 29 PCs and retain 29 PCs for DAPC, then it's going to perfectly discriminate between the clusters and the within-group variance will be dwarfed by the between-group variance. 

What you probably want is to use `dudi.pca()` and `s.class()` to calculate and plot your principal components:

``` r
suppressPackageStartupMessages(library('adegenet'))
data(nancycats)
nan <- nancycats[pop = 11:15]
clust <- find.clusters(nan, n.pca = 100, n.clust = 3)
clust
#> $Kstat
#> NULL
#> 
#> $stat
#> NULL
#> 
#> $grp
#> N125 N126 N127 N128 N129 N130 N131 N132 N133 N246 N247 N271 N298 N299 N300 
#>    2    2    2    2    2    2    2    2    2    2    2    2    3    3    3 
#> N301 N302 N303 N304 N310 N134 N135 N136 N137 N138 N139 N140 N164 N165 N166 
#>    3    3    1    1    1    1    2    2    2    2    2    2    1    1    1 
#> N167 N168 N169 N170 N171 N172 N173 N174 N175 N176 N193 N194 N195 N196 N197 
#>    1    1    1    1    1    1    1    1    1    1    3    3    3    3    1 
#> N198 N199 N200 N201 N202 N203 N206 N207 N209 N210 N211 N212 N204 N227 N228 
#>    3    3    3    3    2    2    2    1    3    3    3    1    2    1    1 
#> N229 N230 N231 N232 N233 N234 N235 N236 N182 N183 N184 N185 N186 N269 N270 
#>    1    1    2    1    1    2    2    2    2    2    2    2    2    2    2 
#> Levels: 1 2 3
#> 
#> $size
#> [1] 26 33 16
nanpc <- dudi.pca(df = tab(nan, NA.method = "mean"), scannf = FALSE, nf = 100)
# Map the groups found via PCA
s.class(nanpc$li, fac = clust$grp, col = funky(5))
```

![](https://i.imgur.com/iNHiSLy.png)

``` r
# Map the populations
s.class(nanpc$li, fac = pop(nan), col = funky(5))
```

![](https://i.imgur.com/6vaVNHo.png)

Created on 2018-07-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by nperry44** [comment]
Is there a way to label each principle component so I can see which matches each sample?

**Comment by zkamvar** [comment]
> Is there a way to label each principle component so I can see which matches each sample?

Do you mean label each sample? The principle components are the axes of the graph and don't map to samples. The samples map to principle components.

If you want to label each sample, then you should use the `s.label()` function after `s.class()`

```r
s.label(nanpc$li, add.plot = TRUE)
```
