### ISSUE TITLE
Simulating DNA sequences with given mutation rate

### ISSUE THREAD

**Issue by jphill01** [thibautjombart/adegenet#241]
I'm wondering if there is any interest in developing a general function that simulates DNA sequences of a given number, basepair length and mutation rate.

Something like (very rudimentary):

    sim.seqs <- function(num.seqs, length.seqs, theta) {

    nucl <- as.DNAbin(c("a", "c", "g", "t")) # define DNA alphabet
    res <- replicate(length.seqs, sample(nucl, size = num.seqs, replace = TRUE)) # create the sequences
    res <- res[sample(nrow(res), size = num.seqs, replace = TRUE), ] # duplicate some sequences (without specifying mu)
    class(res) <- "DNAbin" # coerce to class DNAbin

    }

theta would be the population mutation rate (4Nmu), where N is effective population size (or perhaps just num.seqs), mu is the per generation (forward) mutation rate.

It could start off by generating a single ancestral sequence (or maybe pulling a random one from GenBank or BOLD for a particular species).

The output of such a function would conveniently be a DNAbin object for direct analysis with the 'ape' and/or 'pegas' R packages.

I know of no such R functions or packages that can accomplish this (without, say, simulating a stochastic coalescent birth-death process and generating a phylogenetic tree).

**Comment by jphill01** [comment]
Thanks! Do you know where I can find the source code for rDNAbin? I am not able to download version 5.1-4 from the ape website. I imagine though that the code is much like the first two lines of my rudimentary code above.

**Comment by emmanuelparadis** [comment]
See this link:

http://ape-package.ird.fr/ape_installation.html#versions

I've just uploaded ape 5.1-5 and updated the NEWS file:

http://ape-package.ird.fr/NEWS

**Comment by jphill01** [comment]
Thanks again. Any idea what substitution models will be implemented (p-distancs, Jukes-Cantor, Kimora-2-Parameter, etc.) and when this might occur?

**Comment by emmanuelparadis** [comment]
Generally in population genetics, the time frame is short so that multiple mutations/substitutions are not a problem when comparing sequences (hence the infinite alleles model). That said, simulating under JC69 or K80 model is as easy a under an uncorrected (infinite alleles) model. There is an implementation of these in phangorn with the function simSeq (though this requires a tree).

**Comment by jphill01** [comment]
Here is Thibaut's haploGen() implementation of DNA sequence generation according to a K2P substitution model (tweaked a little at the beginning and end):

sim.seqs <- function(num.seqs, length.seqs, mu.transi, mu.transv) {
    nucl <- as.DNAbin(c("A", "C", "G", "T"))
    transiset <- list("A" = as.DNAbin("G"), 
                           "C" = as.DNAbin("T"),
                           "G" = as.DNAbin("A"), 
                           "T" = as.DNAbin("C"))
    transvset <- list("A" = as.DNAbin(c("C", "T")),
                             "C" = as.DNAbin(c("A", "G")),
                             "G" = as.DNAbin(c("C", "T")),
                             "T" = as.DNAbin(c("A", "G")))
    
    res <- sample(nucl, size = length.seqs, replace = TRUE) # generate a random DNA sequence
    
    ## create transitions 
    transi <- function(res){
      unlist(transiset[as.character(res)])
    }
    
    ## create transversions
    transv <- function(res){
     sapply(transvset[as.character(res)], sample, 1)
    }
    
    seq.dupli <- function(res) { 
      
      ## transitions ##
      n.transi <- rbinom(n = 1, size = length.seqs, prob = mu.transi) # total number of transitions
      if (n.transi > 0) {
        idx <- sample(length.seqs, size = n.transi, replace = FALSE)
        seq[idx] <- transi(seq[idx])
      }
      
      ## transversions ##
      n.transv <- rbinom(n = 1, size = length.seqs, prob = mu.transv) # total number of transversions
      if (n.transv > 0) {
        idx <- sample(length.seqs, size = n.transv, replace = FALSE)
        res[idx] <- transv(res[idx])
      }

      res
    }
    
    res <- as.matrix.DNAbin(res)
    res <- t(matrix(rep(seq.dupli(res), num.seqs), ncol = num.seqs, byrow = TRUE))
    
    class(res) <- "DNAbin"
}



The issue is that the above code doesn't seem to work: it does generate completely random sequences BUT not under a K2P model. Basically, each site is segregating, which is not what one would want. This is verified by collapsing res into unique haplotypes:

    h <- sort(haplotype(res), decreasing = TRUE, what = "frequencies")
    rownames(h) <- 1:nrow(h)
    h # this is equal to num.seqs

I thought this might be a way forward for rDNAbin(), once the bugs are worked out of course.

Any idea why the above code is behaving oddly?


Thanks.

**Comment by emmanuelparadis** [comment]
Maybe the purpose of the original code was to generate SNPs, so all sites are by definition polymorphic?

**Comment by jphill01** [comment]
I checked the actual alignment generated by haploGen() in MEGA and only a few sites are variable; so, this means there is a error in my own code above which I will work to fix.

**Comment by jphill01** [comment]
I think you can close this issue now. The error has been fixed. Many thanks.

**Comment by jphill01** [comment]
Hi Thibaut/Emmanuel,

I have working to write some R code (based on haploGen()) for the general simulation of DNA sequences under various models of nucleotide substitution. 

    library(pegas)

    sim.seqs <- TRUE 
    num.seqs <- 100 # number of sequences to generate
    length.seqs <- 800 # length of generated  sequences
    subst.model <- "JC69" # substitution model, here it's Jukes-Cantor
    mu.rate <- 1e-4 # per-generation mutation rate

## Simulate DNA sequences ##
  
    if (sim.seqs == TRUE) {
      nucl <- as.DNAbin(c('a','c','g','t'))
      
      if ((subst.model == "JC69") || (subst.model == "K80")) {
        res <- sample(nucl, size = length.seqs, replace = TRUE) # each nucl occurs with prob = 0.25
        }
      
      if ((subst.model == "F81") || (subst.model == "HKY85")) {
        if (sum(nucl.freq) != 1) {
          stop("Nucleotide frequencies must sum to 1")
          }
        res <- sample(nucl, size = length.seqs, replace = TRUE, prob = nucl.freq)
      }
      
      if ((subst.model == "JC69") || (subst.model == "F81")) {
        
        mu.set <- list('a' = as.DNAbin('c'),
                       'a' = as.DNAbin('g'),
                       'a' = as.DNAbin('t'),
                       'c' = as.DNAbin('a'),
                       'c' = as.DNAbin('g'),
                       'c' = as.DNAbin('t'),
                       'g' = as.DNAbin('a'),
                       'g' = as.DNAbin('c'),
                       'g' = as.DNAbin('t'),
                       't' = as.DNAbin('a'),
                       't' = as.DNAbin('c'),
                       't' = as.DNAbin('g'))
        
        muts <- function(res) {
          unlist(mu.set[as.character(res)])
        }
        
        duplicate.seq <- function(res) {
          num.muts <- rbinom(n = 1, size = length.seqs, prob = mu.rate) # total number of substitutions
          if (num.muts > 0) {
            idx <- sample(length.seqs, size = num.muts, replace = FALSE)
            res[idx] <- muts(res[idx])
          }
          res
        }
      
      }
      
      if ((subst.model == "K80") || (subst.model == "HKY85")) {
        
        transi.set <- list('a' = as.DNAbin('g'), 
                           'c' = as.DNAbin('t'),
                           'g' = as.DNAbin('a'), 
                           't' = as.DNAbin('c'))
        transv.set <- list('a' = as.DNAbin(c('c', 't')),
                           'c' = as.DNAbin(c('a', 'g')),
                           'g' = as.DNAbin(c('c', 't')), 
                           't' = as.DNAbin(c('a', 'g')))
        
        transi <- function(res) {
          unlist(transi.set[as.character(res)])
        }
        
        transv <- function(res) {
          sapply(transv.set[as.character(res)], sample, 1)
        }
        
        duplicate.seq <- function(res) {
          num.transi <- rbinom(n = 1, size = length.seqs, prob = transi.rate) # total number of transitions
          if (num.transi > 0) {
            idx <- sample(length.seqs, size = num.transi, replace = FALSE)
            res[idx] <- transi(res[idx])
          }
          
          num.transv <- rbinom(n = 1, size = length.seqs, prob = transv.rate) # total number of transversions
          if (num.transv > 0) {
            idx <- sample(length.seqs, size = num.transv, replace = FALSE)
            res[idx] <- transv(res[idx])
          }
          res
        }
      }
    
      res <- matrix(replicate(num.seqs, duplicate.seq(res)), byrow = TRUE, nrow = num.seqs)
      
      class(res) <- "DNAbin"
    
      write.dna(res, file = "res.fas", format = "fasta")
    
      assign("N", dim(res)[[1]], envir = .GlobalEnv)
      h <- sort(haplotype(res), decreasing = TRUE, what = "frequencies")
      rownames(h) <- 1:nrow(h)
      assign("Hstar", dim(h)[[1]], envir = .GlobalEnv)
      assign("probs", lengths(attr(h, "index")) / N, envir = .GlobalEnv)
    
    }

The output I get is strange. 

The haplotype distribution is very skewed.

h

    Haplotypes extracted from: res 

    Number of haplotypes: 13 
          Sequence length: 800 

    Haplotype labels and frequencies:

       1     2     3     4     5     6     7     8     9     10     11     12     13 
      88   1      1     1      1     1     1      1      1       1       1       1      1 


Any idea on how to modify the code so that the haplotype distribution is random?

For instance something like

h

    Haplotypes extracted from: res 

    Number of haplotypes: 13 
          Sequence length: 800 

    Haplotype labels and frequencies:

       1     2     3     4     5     6     7     8     9     10     11     12     13 
      48   20   13   10   1     1     1      1      1       1       1       1      1 

I appreciate any suggestions you may have. 
I hope it will be a way forward for others who are also looking to simulate some DNA sequences.
