### ISSUE TITLE
data format 

### ISSUE THREAD

**Issue by taniachavarria79** [thibautjombart/adegenet#251]
Hello,

I was wondering if I can see the data matrix nancycats to arragement my data in a similar way. When I convert my tab delimited to a genind object it takes the first column with the information with the loci number as an individual and the column with the individual numbers as a loci.

Thanks

**Comment by romunov** [comment]
Can you paste header (first few rows and columns) of your data and the code you're using to convert the data?

**Comment by taniachavarria79** [comment]
Hello,

Here I send you the header and this is the code I am using. Thanks so much.

obj <- df2genind(dat, sep = NULL, ncode = NULL, ind.names = NULL,
          loc.names = NULL, pop = dat$pop, NA.char = NA, ploidy = 1,
          type = c("codom"), strata = NULL, hierarchy = NULL)

________________________________

**Comment by zkamvar** [comment]
Hi, 

The first two columns of your data have the individual names and the population names. You need to subset your data frame to not include them in df2genind. 

Like this:

obj <- df2genind(dat[, -(1:2)], sep = NULL, ncode = NULL, ind.names = dat$ind,
loc.names = NULL, pop = dat$pop, NA.char = NA, ploidy = 1,
type = c("codom"), strata = NULL, hierarchy = NULL)

**Comment by taniachavarria79** [comment]
Thanks so much!

________________________________
