### ISSUE TITLE
Adegenet crashes, can't reinstall

### ISSUE THREAD

**Issue by plantarum** [thibautjombart/adegenet#252]
Trying to load `adegenet` fails with the following error:

> R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

    > setwd('/home/tws/research/rwd/')
    > library(adegenet)
    Loading required package: ade4
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Mutex creation failed

    Process R:2 aborted at Thu Dec 20 11:35:27 2018

I tried to reinstall it from a fresh session:

> R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

    > setwd('/home/tws/research/rwd/')
    > install.packages("adegenet")
    Installing package into ‘/usr/local/lib/R/site-library’
    (as ‘lib’ is unspecified)
    trying URL 'https://cloud.r-project.org/src/contrib/adegenet_2.1.1.tar.gz'
    Content type 'application/x-gzip' length 1696189 bytes (1.6 MB)
    ==================================================
    downloaded 1.6 MB

    * installing *source* package ‘adegenet’ ...
    ** package ‘adegenet’ successfully unpacked and MD5 sums checked
    ** libs
    gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-SeMDKP/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c GLfunctions.c -o GLfunctions.o
    gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-SeMDKP/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c adesub.c -o adesub.o
    gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-SeMDKP/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
    gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-SeMDKP/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c monmonier-utils.c -o monmonier-utils.o
    gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-SeMDKP/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sharedAll.c -o sharedAll.o
    gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-SeMDKP/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c snpbin.c -o snpbin.o
    gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o adegenet.so GLfunctions.o adesub.o init.o monmonier-utils.o sharedAll.o snpbin.o -L/usr/lib/R/lib -lR
    installing to /usr/local/lib/R/site-library/adegenet/libs
    ** R
    ** data
    ** inst
    ** byte-compile and prepare package for lazy loading
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Mutex creation failed
    Aborted

    The downloaded source packages are in
	    ‘/tmp/Rtmp9X4iLw/downloaded_packages’
    Warning message:
    In install.packages("adegenet") :
      installation of package ‘adegenet’ had non-zero exit status

I have been able to load adegenet previously, perhaps there's an update to one of the system libraries is now incompatible? Any suggestions how to fix this?

Best,

Tyler

Debian Linux
R version 3.5.1
adegenet 2.1.1, packaged 2018-02-02
gcc (Debian 8.2.0-12) 8.2.0
libc6 2.28-2

**Comment by zkamvar** [comment]
I found this by searching "Mutex creation failed" on DuckDuckGo: http://debian.2.n7.nabble.com/Bug-915321-Mutex-creation-failed-td4427885.html

I hope it helps. 

Since this is not an adegenet-specific error, I will close this issue.

**Comment by thibautjombart** [comment]
Thanks for the update.
