### ISSUE TITLE
read.loci() silently deleting samples on import

### ISSUE THREAD

**Issue by barretp** [thibautjombart/adegenet#253]
I have a large microsat dataset (2776 individuals/17 loci). When I import it using read.loci(), it seems to be selectively deleting samples without any warnings. When sorted by sample ID, it removes ~70 individuals, which come from 2 adjacent(ly named) populations, plus a third that is the midpoint of the dataset. When sorted in other ways, it removes additional individuals, seemingly at random, again with no warnings. 

Importing it as a dataframe using read.csv() returns the correct number of samples regardless of sample order. 

[adegenet_Troubleshooting.docx](https://github.com/thibautjombart/adegenet/files/2791471/adegenet_Troubleshooting.docx)

**Comment by emmanuelparadis** [comment]
`read.loci` is in [pegas](https://github.com/emmanuelparadis/pegas), so I'm closing this issue and opening one [here](https://github.com/emmanuelparadis/pegas/issues/40).
