### ISSUE TITLE
Error when running hybridize

### ISSUE THREAD

**Issue by Sergi-Taboada** [thibautjombart/adegenet#262]
Hi Thibaut,

I am trying to generate hybrids using the hybridize function in adegenet. For that I am using SNPs derived from ddRADseq. I am using two closely related species of sponges.

The function seemed to work fine with a dataset of individuals and was generating hybrids as expected.

However, when trying to generate hybrids with other subsets of data I recurrently have the same error popping up.

Here it is the details of the code I am using:

```
x <- read.genepop("populations.snps.gen")
x
```

/// GENIND OBJECT /////////
  
  // 40 individuals; 1,931 loci; 3,862 alleles; size: 1.5 Mb

// Basic content
@tab:  40 x 3862 matrix of allele counts
@loc.n.all: number of alleles per locus (range: 2-2)
@loc.fac: locus factor for the 3862 columns of @tab
@all.names: list of allele names for each locus
@ploidy: ploidy of each individual  (range: 2-2)
@type:  codom
@call: read.genepop(file = "populations.snps.gen")

```
pops<-c(rep("Phirondellei", times=23), rep("Probusta", times=17))
pop(x)<-pops
pop(x)
```

#We separate genotypes per populations using the 'seppop' function (everything looks fine here): 
```
n.pop <- seppop(x)
n.pop
names(n.pop)
```

#We create two genind objects, one per species (everything looks fine here):
```
Phirond <- n.pop$Phirondellei
Probus <- n.pop$Probusta
```
/// GENIND OBJECT /////////

 // 23 individuals; 1,931 loci; 3,862 alleles; size: 1.2 Mb

 // Basic content
   @tab:  23 x 3862 matrix of allele counts
   @loc.n.all: number of alleles per locus (range: 2-2)
   @loc.fac: locus factor for the 3862 columns of @tab
   @all.names: list of allele names for each locus
   @ploidy: ploidy of each individual  (range: 2-2)
   @type:  codom
   @call: .local(x = x, i = i, j = j, treatOther = ..1, quiet = ..2, drop = drop)

/// GENIND OBJECT /////////

 // 17 individuals; 1,931 loci; 3,862 alleles; size: 1.1 Mb

 // Basic content
   @tab:  17 x 3862 matrix of allele counts
   @loc.n.all: number of alleles per locus (range: 2-2)
   @loc.fac: locus factor for the 3862 columns of @tab
   @all.names: list of allele names for each locus
   @ploidy: ploidy of each individual  (range: 2-2)
   @type:  codom
   @call: .local(x = x, i = i, j = j, treatOther = ..1, quiet = ..2, drop = drop)

#We create a hybrid genind object using the two genind objects created before (we create hybrids from the two original species)

`Phybrid <- hybridize(Phirond, Probus, n=50, pop = "Phybrid")`

**Error in rmultinom(n, ploidy/2, v) : NA in probability vector**

Any idea about what might be happening? I tried to find similar problems in the adegenet-forum and here but could not spot anything similar.

Thanks in advance,
Sergi.

**Comment by eachambers** [comment]
Hi Sergi,

I'm having the exact same error with the hybridize function; did you ever happen to figure this out?

Anne

**Comment by zkamvar** [comment]
It is difficult for me to guess at what is happening without more information about your data, but the error is coming from here: https://github.com/thibautjombart/adegenet/blob/b8b7b3b1cf3081dc43f85b8d6794f89f161fa084/R/hybridize.R#L122-L134

You might try running the following to see if any alleles are missing completely from your populations:

```r
Phi <- tab(genind2genpop(Phirond, pop = factor(rep(1, nInd(Phirond)), freq = TRUE)
Pro <- tab(genind2genpop(Probus), pop = factor(rep(1, nInd(Probus)), freq = TRUE)

anyNA(Phi)
anyNA(Pro)
```

For example, this is what comes up with the nancycats data set, which has a completely missing locus for population 17: 

``` r
suppressPackageStartupMessages(library(adegenet))  
    data(nancycats)  
    res <- tab(genind2genpop(nancycats[pop = 17, loc = 3:4]), freq = TRUE) 
#> 
#>  Converting data from a genind to a genpop object... 
#> 
#> ...done.
    print(res) # missing data in a single locus 
#>     fca43.133 fca43.135 fca43.137 fca43.139 fca43.141  fca43.143 fca43.145
#> P17         0 0.2307692         0 0.3846154 0.1153846 0.07692308 0.1923077
#>     fca43.147 fca43.149 fca43.157 fca45.116 fca45.118 fca45.120 fca45.122
#> P17         0         0         0       NaN       NaN       NaN       NaN
#>     fca45.126 fca45.128 fca45.130 fca45.132 fca45.134
#> P17       NaN       NaN       NaN       NaN       NaN
    anyNA(res)      
#> [1] TRUE
```

<sup>Created on 2021-09-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I will attempt to fix this and see if that addresses your problem.

**Comment by zkamvar** [comment]
When #317 is merged, this fix will appear on the devel release of adegenet, which you can test out by installing it from my r-universe:

```r
# Enable this universe
options(repos = c(
    zkamvar = 'https://zkamvar.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages('adegenet')
```
