### ISSUE TITLE
Cannot load adegenet

### ISSUE THREAD

**Issue by gibedini** [thibautjombart/adegenet#269]
I am trying to lad adegenet but get this message:

Error: package or namespace load failed for ‘adegenet’:
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found

I am running R Studio 1.1.419, R version 3.5.2 (2018-12-20), under Mac OSX 10.13.4, and would much appreciate any help, thank you

Gianni

**Comment by KlausVigo** [comment]
Hi @gibedini! 
Which version of `adegenet` are you using? The R version is already a over a year old you may want to  / should update it. Also the error messages seem not have to do anything directly with `adegenet`. It seems you try to load some other packages as  `group_map` is in `dplyr` but is not used inside `adegenet`. And  there seems also an issue that the `sf` package may not properly installed, which is also not needed for running `adegenet`.  
Cheers, 
Klaus

**Comment by gibedini** [comment]
Thank you Klaus!
I think the problem was the sf package which indeed was not installed. In the meantime I have downloaded an updated version of R and will try again with adegenet.
Best regards
Gianni

> Il giorno 27 gen 2020, alle ore 11:48, Klaus Schliep <notifications@github.com> ha scritto:
> 
> Hi @gibedini!
> Which version of adegenet are you using? The R version is already a over a year old you may want to / should update it. Also the error messages seem not have to do anything directly with adegenet. It seems you try to load some other packages as group_map is in dplyr but is not used inside adegenet. And there seems also an issue that the sf package may not properly installed, which is also not needed for running adegenet.
> Cheers,
> Klaus
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

*********************
Prof. Gianni Bedini
Dipartimento di Biologia - unità di Botanica, Università di Pisa
via Derna 1, I-56126 Pisa, Italia
tel. +39 050 2211 314
e-mail gianni.bedini@unipi.it
ORCID: 0000-0002-4802-0057
Editor of Atti della Società Toscana di Scienze Naturali, Memorie, Serie B 
(http://www.stsn.it/it/memorie-serie-b.html)
Co-editor of Wikiplantbase: http://bot.biologia.unipi.it/wpb/toscana/; bot.biologia.unipi.it/wpb/sardegna/; bot.biologia.unipi.it/wpb/liguria/; bot.biologia.unipi.it/wpb/sicilia/.

**Comment by asumann** [comment]
Hi,

I am also having a similar error:

> library("poppr")
Loading required package: adegenet
Loading required package: ade4
Error: package or namespace load failed for ‘adegenet’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘sf’
Error: package ‘adegenet’ could not be loaded

I am using the latest version of R on Mac v10.14.6. What could be the problem here?

Many thanks,
Asuman

**Comment by romunov** [comment]
@asumann have you tried `install.packages("sf")` and restarting R session?

**Comment by asumann** [comment]
> @asumann have you tried `install.packages("sf")` and restarting R session?

Thanks, that worked!

> install.packages("sf")

  There is a binary version available but the source version is later:
   binary source needs_compilation
sf  0.8-0  0.8-1              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) No

It worked when I answer No. Then, I was also able to load adegenet package.

Many thanks again!!

**Comment by romunov** [comment]
My guess is that you may not have the proper toolchain to compile package from source, which is why sf installation may have failed (this is my guess). Installing from a binary bundle may have solved this.

I believe all the issues have been resolved. If not, feel free to add your comment.
