### ISSUE TITLE
issues installing adeneget

### ISSUE THREAD

**Issue by taniachavarria79** [thibautjombart/adegenet#272]
Hello,

I used adeneget three months ago and I did not have any problems. Now I want to re run some analysis and I been having problems with the installation.
I found this message:

Error: package or namespace load failed for ‘adegenet’ in library.dynam(lib, package, package.lib):
 DLL ‘sf’ not found: maybe not installed for this architecture?
In addition: Warning messages:
1: package ‘adegenet’ was built under R version 3.4.4 
2: S3 methods ‘$.bbox’, ‘$.crs’, ‘$.m_range’, ‘$.z_range’, ‘$<-.sf’, ‘[.sf’, ‘[.sfc’, ‘[<-.sfc’, ‘[[<-.sf’, ‘st_agr<-.sf’, ‘st_crs<-.sf’, ‘st_crs<-.sfc’, ‘st_geometry<-.data.frame’, ‘st_geometry<-.sf’, ‘Ops.crs’, ‘Ops.sfc’, ‘Ops.sfg’, ‘Ops.sgbp’, ‘aggregate.sf’, ‘as.data.frame.sf’, ‘as.data.frame.sfc’, ‘as.data.frame.sgbp’, ‘as.matrix.sfg’, ‘as.matrix.sgbp’, ‘c.sfc’, ‘c.sfg’, ‘cbind.sf’, ‘dim.sgbp’, ‘format.sfc’, ‘format.sfg’, ‘head.sfg’, ‘identify.sf’, ‘identify.sfc’, ‘is.na.bbox’, ‘is.na.crs’, ‘is.na.m_range’, ‘is.na.z_range’, ‘merge.sf’, ‘plot.sf’, ‘plot.sfc_CIRCULARSTRING’, ‘plot.sfc_GEOMETRY’, ‘plot.sfc_GEOMETRYCOLLECTION’, ‘plot.sfc_LINESTRING’, ‘plot.sfc_MULTILINESTRING’, ‘plot.sfc_MULTIPOINT’, ‘plot.sfc_MULTIPOLYGON’, ‘plot.sfc_POINT’, ‘plot.sfc_POLYGON’, ‘plot.sfg’, ‘print.bbox’, ‘print.crs’, ‘print.m_range’, ‘print.sf’, ‘print.sf_layers’, ‘print.sfc’, ‘print.sfg’, ‘print.sgbp’, ‘print.z_range’, ‘rbind.sf’, ‘rep.sfc’, ‘st_agr.character’, ‘st_agr.default’, ‘st_agr.factor’, ‘st_agr [... truncated] 

Thanks so much for your help

**Comment by zkamvar** [comment]
Hello, this is similar to https://github.com/thibautjombart/adegenet/issues/269.

I would suggest to reinstall sf and adegenet.

**Comment by taniachavarria79** [comment]
it works thanks so much
