### ISSUE TITLE
"entirely non-type individual(s) deleted" warning is unclear

### ISSUE THREAD

**Issue by plantarum** [thibautjombart/adegenet#274]
Hi,

I just got this warning message when using `df2genind`:

```
entirely non-type individual(s) deleted
```

It took me a while to figure out; I think it means that I have some individuals with no scored loci, and they have been dropped. That's correct, and I'm happy to get a warning when this happens. However, the wording is not clear, particularly the phrase "non-type individual".

If I have interpreted the warning correctly, perhaps you might consider rewording it as:

```
Individuals with no scored loci have been removed
```

Or something similar?

Thanks,

Tyler

**Comment by zkamvar** [comment]
I think that's a good idea. I'll try to make this change soon, but do poke me if you don't hear anything about it in a while.

**Comment by plantarum** [comment]
Great, thanks!

**Comment by poecile-palustris** [comment]
Good evening! 

Could you please tell me is there a way to disable ignoring such samples?
Thank you in advance!

Best regards,
Poecile

**Comment by zkamvar** [comment]
At the moment, ther is no way to disable this. Individuals that have no genotypes cannot be analyzed
