### ISSUE TITLE
we should be able to enter distance through an argument

### ISSUE THREAD

**Issue by romunov** [thibautjombart/adegenet#279]
Function [`chooseCN` asks for user input on `type = 5`](https://github.com/thibautjombart/adegenet/blob/master/R/chooseCN.R#L204). We should make this function accept additional arguments so that the user can enter values via a script. Right now the function could not be knitted in i.e. a markdown document because it waits for user input.

I'm thinking of adding `...` argument to the function and then checking for correct argument names for respective type.

**Comment by zkamvar** [comment]
This is only triggered if the user does not supply the `d1` or `d2` arguments in the function call. Is this not the behavior you see?
