### ISSUE TITLE
Negative BIC values from find.clusters

### ISSUE THREAD

**Issue by mep19** [thibautjombart/adegenet#291]
Hi - I've been using DAPC to look at structure in presumably "neutral" and putative "outlier" SNP data sets.   Most perform as would be expected but one data set produces a BIC graph in which all the values are negative and decreasing with increasing clusters.  I'm wondering what this might mean?

Dataset:
> NL_outliers_gi
***** Object of Class vcfR *****
200 samples
6 CHROMs
6 variants
Object size: 0.1 Mb
0 percent missing data

Code:
grp<-find.clusters(NL_outliers_gi,  pca.select = "percVar",perc.pca=99, max.n.clust = 50, choose.n.clust = TRUE)

Plot:
![Plot_ValueofBIC](https://user-images.githubusercontent.com/38697395/90127652-6ab27a00-dd5d-11ea-9ce7-d30101938947.png)

Any advice you have would be really helpful!

**Comment by zkamvar** [comment]
There are several things that can cause this, which have been answered previously in the adegenet forum:

https://lists.r-forge.r-project.org/pipermail/adegenet-forum/2011-June/000303.html

Relevant snippet:

> Odd shapes of the decrease of BIC can occur for several reasons. The possible explanations I can think of are:
> a) there are no clearly identifiable clusters in the data.
>
> b) there are clusters to be identified, but not enough information to disentangle different values of k. In your case this seems very likely: there are few SNPs, and if half of them are specific to one individual they are not informative in terms of clusters.
>
> c) the method does not work for these data; k-means is very flexible, and I would be surprised to see it fail completely where other clustering methods would succeed. However, BIC is by no way the ultimate criterion for choosing k. It gave the best results on a set of simulations, it is fairly consistent statistically, but that's it. I would not be surprised to find some specific cases in which it would give poor results.
