### ISSUE TITLE
try compiler to speedup stuff

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/adegenet#30]
List of things to try:
- [x] df2genind
- [x] genind2df
- [ ] ??? (feel free to complete)

**Comment by thibautjombart** [comment]
```r
> genind2df2 <- cmpfun(genind2df)
> df2genind2 <- cmpfun(df2genind)
> system.time(x1 <- genind2df(eHGDP, sep="/"))
   user  system elapsed 
  7.359   0.216   7.522 
> system.time(x1 <- genind2df2(eHGDP, sep="/"))
   user  system elapsed 
  6.721   0.195   6.890 
> system.time(x1 <- genind2df(eHGDP, sep="/"))
   user  system elapsed 
  7.481   0.190   7.619 
> system.time(x2 <- genind2df2(eHGDP, sep="/"))
   user  system elapsed 
  7.048   0.177   7.180 
> all.equal(x1,x2)
[1] TRUE
> identical(x1,x2)
[1] TRUE
> system.time(y1 <- df2genind(x1, sep="/", ploidy=2))
   user  system elapsed 
 75.958   0.126  76.314 
> system.time(y2 <- df2genind2(x1, sep="/", ploidy=2))
   user  system elapsed 
 72.494   0.369  73.024 
```

**Comment by thibautjombart** [comment]
doesn't seem that impressive a boost; like to think code is well-optimized already..?

**Comment by zkamvar** [comment]
It looks like it. I noticed that there are a couple of `cbind.data.frame` calls in `genind2df`, but those are done once per scenario, and I don't know if pre-allocating the list/data.frame before hand would help anything.

**Comment by thibautjombart** [comment]
I need to check; do.call may speed things up there.

**Comment by thibautjombart** [comment]
Done a bit of optimization at 077e1fba7278b7e150
Further optimization would require recoding the function in a more vectorized way . Not sure it is worth the effort, while wait for it to be a problem.
