### ISSUE TITLE
Function for observed heterozygosity per pop?

### ISSUE THREAD

**Issue by courtiol** [thibautjombart/adegenet#301]
It would be good to have a function equivalent to `Hs()` for showing the observed heterozygosity per pop.
One simple option could be to combine existing functions such as `seppop()` + `summary()`:

``` r
library(adegenet)

data(nancycats, package = "adegenet")

Hs(nancycats)
#>       P01       P02       P03       P04       P05       P06       P07       P08 
#> 0.6157292 0.6852617 0.6890432 0.7334594 0.6190123 0.7112029 0.6410060 0.7144444 
#>       P09       P10       P11       P12       P13       P14       P15       P16 
#> 0.6556927 0.6666667 0.7614782 0.6425924 0.6614070 0.7638255 0.6900826 0.6712963 
#>       P17 
#> 0.6256279

Hexp <- function(x) {
  if (!"genind" %in% class(x)) stop("x must be a genind object!")
  unlist(lapply(seppop(x), function(pop) mean(summary(pop)$Hexp)))
}

Hexp(nancycats)  ## reproduces Hs correctly
#>       P01       P02       P03       P04       P05       P06       P07       P08 
#> 0.6157292 0.6852617 0.6890432 0.7334594 0.6190123 0.7112029 0.6410060 0.7144444 
#>       P09       P10       P11       P12       P13       P14       P15       P16 
#> 0.6556927 0.6666667 0.7614782 0.6425924 0.6614070 0.7638255 0.6900826 0.6712963 
#>       P17 
#> 0.6256279


Hobs <- function(x) {
  if (!"genind" %in% class(x)) stop("x must be a genind object!")
  unlist(lapply(seppop(x), function(pop) mean(summary(pop)$Hobs)))
}

Hobs(nancycats)
#>       P01       P02       P03       P04       P05       P06       P07       P08 
#> 0.5722222 0.5707071 0.6111111 0.6280193 0.5629630 0.6262626 0.5458554 0.6111111 
#>       P09       P10       P11       P12       P13       P14       P15       P16 
#> 0.7407407 0.6262626 0.6627394 0.5569986 0.6752137 0.6836601 0.7474747 0.6759259 
#>       P17 
#>       NaN
```

But, I guess that would work with `genind` objects while `Hs()` has been conceived for `genpop` objects, so perhaps something more consistent across classes would be preferred.

**Comment by jgx65** [comment]
try

```
library(hierfstat)
basic.stats(nancycats)$Hs
basic.stats$Ho

```

**Comment by courtiol** [comment]
Thanks but that's not equivalent to `Hs()` since it does the breakdown per locus.
Of course, one could use apply() to compute the means per pop from what you have shown, but the point was more to highlight that it is not available out of the box in adegenet...

**Comment by jgx65** [comment]
Do you really think a new function is necessary when `colMeans()` does the job you're looking for?

**Comment by courtiol** [comment]
For me no, but for students from, say, an applied master of conservation genetics, it is another mater.
They certainly don't know much R and no apply or colMeans.

So far, we were saying: to look at expected heterozygosity per pop use {adegenet} and use `Hs()`, and then 
I was sharing some code doing Hobs() but I would rather build on existing packages.

I felt uncomfortable is telling them to compute observed heterozygosity via `colMeans(basic.stats(ncats)$Hs,na.rm=TRUE)` from {hierfstat} because, trying to limit the number of packages to a minimum, we had managed to make a introductory course without using {hierfstat} (which a few years back was quite dormant.)
I was thus looking for solution in {adegenet} which already provided `Hs()`.

But I guess, based on what you said, we will stop using `adegenet::Hs()` and move to `hierfstat::basic.stats()` for all heterozygosity metrics.

I thus close the issue.
++

**Comment by jgx65** [comment]
just uploaded a new version of `hierfstat` on github, with wrappers `Hs`and `Ho` to produce mean populations gen diversities and observed heterozygosities respectively
