### ISSUE TITLE
New release to add missing doc on snapclust

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/adegenet#309]
The documentation of snapclust has been completed in the current github version of adegenet, but has not made it to CRAN yet. When possible, it would be great to push the current version to CRAN. Doc from the CRAN version reads:

> DESCRIPTION
> Do not use. We work on that stuff. Contact us if interested.

**Comment by zkamvar** [comment]
The deed is done and you can now bask in the warmth of a manpage that no longer warns people of nonexistent dragons.
