### ISSUE TITLE
Better handling of parallel computation (or lack of) for Windows users

### ISSUE THREAD

**Issue by courtiol** [thibautjombart/adegenet#313]
In some of the reading functions at least (but perhaps elsewhere too), `parallel::mclapply` is automatically called.
This creates issues on Windows since the OS does not support forking.

That happens if the user has the package {parallel} installed and if `n.cores` is not NULL.
In practice, these two conditions are most likely TRUE:  parallel is shipped with standard R installation and unless the user specifies  `n.cores` manually `n.cores <- parallel::detectCores()` is called.

So I see 3 main possible solutions:
- generate informative error message telling user to set `parallel = FALSE` to avoid the issue
- detect the OS and stop parallel processing by default for Windows user
- implement an alternative back end for parallel processing

The issue was reported to me by a university lecturer who rightly pointed out that most of her students are on Windows...

**Comment by zkamvar** [comment]
Agreed. This has been an annoyance for some time now and I'm all in favor of options 2 and 3 (option 1 is frustrating for users). In fact, the future package looks promising on the cross-platform parallel front: https://cran.r-project.org/package=future

That being said, we've been here before and tried to go with option 2: https://github.com/thibautjombart/adegenet/issues/109

I'll see what I can do, but I'm afraid I don't have much time for maintenance of this project these days, so it might be slow. 
If you make a pull request before I do, I'll gladly review it and add you as a contributor.

**Comment by courtiol** [comment]
To choose between option 2 (no parallel for Windows) and 3 (swapping parallel processing back end to something more general), we need to know if anyone is likely to do serious heavy duty work on a Windows machine...

If not, I would favor option 2 since sticking to mclapply is very efficient, does not imply to add new dependencies and to rewrite a lot of code.

I have no idea if some population genetics/genomics is ran on Windows server these days...

Does anyone reading that knows?

**Comment by zkamvar** [comment]
Hello, I have addressed this on the default branch of this repository. You can test it out for users on windows by having them install the devel version from my r-universe:


```r
# Enable this universe
options(repos = c(
    zkamvar = 'https://zkamvar.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages('adegenet')
```
