### ISSUE TITLE
PCoA plot problems 

### ISSUE THREAD

**Issue by laiajulianamu** [thibautjombart/adegenet#324]
Hi I am having the next issue when I run the pcoa plot, could you help me please. 

> gl.pcoa.plot(gl)

Starting gl.pcoa.plot 
  Processing genlight object with SNP data
Error in utils.check.datatype(glPca, accept = "glPca", verbose = verbose) : 
  Fatal Error: inappropriate object passed to function, found SNP expecting glPca

**Comment by zkamvar** [comment]
the `gl.pcoa.plot()` function takes a `glPca` object, which contains PC Analysis of a genlight object. You submitted a genlight object. You can create the PC analysis by using `gl_pca <- glPca(gl)` and then passing `gl_pca` to the `gl.pcoa.plot()` function
