### ISSUE TITLE
flags for genlight constructor not passed in rbind.genlight or cbind.genlight

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#34]
Using the example in the documentation:

```r
a <- new("genlight", list(toto=rep(1,10), tata=rep(c(0,1), each=5), titi=c(NA, rep(1,9)) ))
ara <- rbind(a,a) # Works
rbind(a, a, parallel = FALSE) 
## Error in rbind(deparse.level, ...) : 
##  some objects are not genlight objects 
```

**Comment by thibautjombart** [comment]
Fixed as of 68f3731cc5f63286cad6aef2baa365762851e2d3
The function was written as if ... was passed to the constructor, but it was implicitly assuming the ... contained exclusively genlight objects. Fixed now.
