### ISSUE TITLE
vcfR2genlight does not calculate loc.all field

### ISSUE THREAD

**Issue by frederikvand** [thibautjombart/adegenet#340]
Dear Thibaut,

When I use vcfR2genlight, the loc.all field is not calculated which gives issues gl.report.ld.map (dartR). Is it possible to integrate an extra field to request calculation of this fields? If not, is there an option to determine this post hoc? 

With kind regards,
Frederik

**Comment by zkamvar** [comment]
You will have to ask the developer for {vcfR} to add this field, the developers of {adegenet} have no control over the behaviour of that package's functions: https://github.com/knausb/vcfR/issues
