### ISSUE TITLE
scatter error

### ISSUE THREAD

**Issue by cfz1998** [thibautjombart/adegenet#352]
Hi! @zkamvar 

According to the tutorial for Discriminant Analysis of Principal
Components (DAPC). The scatter does not work well.
![image](https://github.com/thibautjombart/adegenet/assets/60096719/1775da28-4ccc-454e-b511-04be51d149e3)

``` R
library(adegenet)
library(vcfR)

x <- read.vcfR("my.vcf", verbose=F)
y <- vcfR2genind(x)


grp <- find.clusters(y, max.n.clust=100, n.clust = 3)
# 40 for PCA
dapc1 <- dapc(y, grp$grp, n.pca = 40, n.da = 4)
# scatter(dapc1)

scatter(dapc1)
```
May be the big number of pca.cent?
![image](https://github.com/thibautjombart/adegenet/assets/60096719/c04a35cd-9d62-453f-8011-83a6be8b7b2a)

Thank you for your reply!

**Comment by zkamvar** [comment]
```
grp <- find.clusters(y, max.n.clust=100, n.clust = 3)
# 40 for PCA
dapc1 <- dapc(y, grp$grp, n.pca = 40, n.da = 4)
# scatter(dapc1)
```

You are using the same number of Principle Components to train your model as you used to detect your clusters. You are overfitting the model. Reduce the number of principle components.

**Comment by cfz1998** [comment]
Hi! @zkamvar 
I got the same result when i reduced the number of principal components to detect your clusters.

![image](https://github.com/thibautjombart/adegenet/assets/60096719/d168ed11-2eb9-4530-8f66-5d4a1f41d3c2)

**Comment by zkamvar** [comment]
It's not an error. This means that you are comparing groups that are quite disparate.
