### ISSUE TITLE
Error in DAPC while selecting DAs

### ISSUE THREAD

**Issue by massub** [thibautjombart/adegenet#361]
I have been using adegent and DAPC for a while now and never had a problem but recently I am running into a problem. After find.cluster when I perform dapc after selecting the PCs to retain I get the following error before selecting the DAs to retain.

Error in lda.default(x, grouping, ...) :
   nrow(x) and length(grouping) are different

Why am I getting this error now, Please any help in this regard will be appreciated.

Thanks,

**Comment by zkamvar** [comment]
This was cross-posted to the poppr google group less than a day after this issue was opened and I have answered it there:

https://groups.google.com/g/poppr/c/GcUHO61SvMA/m/Dxxjq7x7AQAJ

Please refrain from cross-posting in the future, it fragments discussions and is time consuming for maintainers.
