### ISSUE TITLE
Create short vignette for strata

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#38]
This could largely be lifted from Section 2.1 of [poppr's Data import and manipulation vignette](http://cran.r-project.org/web/packages/poppr/vignettes/poppr_manual.pdf) with some tweaking.

**Comment by thibautjombart** [comment]
Hi there, 
for what it's worth, I'll be trying to do as much as possible today to push adegenet towards a release.

**Comment by zkamvar** [comment]
Got it. I did start the strata vignette a couple of weeks ago, but haven't done much else because it renders weird.
