### ISSUE TITLE
Quick issue (or maybe not an issue?)

### ISSUE THREAD

**Issue by mgiresi** [thibautjombart/adegenet#40]
I thought that "read.fstat" would import the file as a genind object. This doesn't happen (at least when I run "HWE.test" it says that the file isn't a genind object.  For running summary stats using functions (basic.stats, and allelic.richness), the analysis will run. But not with HWE.test.  This issue can be avoided by using the import2genind function instead of read.fstat.

**Comment by zkamvar** [comment]
By all means read.fstat should import the data as a genind object. I believe that HWE.test is being sunsetted in the new version. Can you run these two lines of code so that we can see what version of adegenet you're dealing with:

```r
devtools::session_info()
packageDescription("adegenet")
```

**Comment by mgiresi** [comment]
Hola,

Package: adegenet
*Version: 1.4-2*
Date: 2014/05/13
Title: adegenet: an R package for the exploratory analysis of genetic and
genomic data.
Author: Thibaut Jombart, Caitlin Collins, Peter Solymos, Ismail Ahmed,
Federico Calboli, Anne Cori
Maintainer: Thibaut Jombart <t.jombart@imperial.ac.uk>
Suggests: genetics, spdep, tripack, pegas, seqinr, adehabitat, parallel,
akima, maps, splancs, hierfstat
Depends: R (>= 2.14), methods, ade4
Imports: utils, stats, MASS, igraph, ape, shiny, ggplot2
URL: http://adegenet.r-forge.r-project.org/
Description: Classes and functions for genetic data analysis within the
multivariate framework.
Collate: classes.R basicMethods.R handling.R auxil.R setAs.R SNPbin.R
glHandle.R glFunctions.R glSim.R find.clust.R hybridize.R scale.R fstat.R
import.R seqTrack.R chooseCN.R
                    .....
License: GPL (>= 2)
LazyLoad: yes
Packaged: 2014-05-13 04:05:07 UTC; thibaut
NeedsCompilation: yes
Repository: CRAN
Date/Publication: 2014-05-13 07:44:32
Built: R 3.1.2; x86_64-apple-darwin13.4.0; 2015-01-10 04:59:49 UTC; unix

**Comment by mgiresi** [comment]
I suppose I should be smarter and use the newer version. Doh.

**Comment by zkamvar** [comment]
Well, `read.fstat` should read in a genind object in the old version. Can you send the error you get from HWE.test and your session info?

**Comment by mgiresi** [comment]
> Mcanis <- read.fstat("McanisOnly.dat") #works
> allelic.richness(Mcanis) #works
> basic.stats(Mcanis, diploid =TRUE, digits =3) #works
> HWE.test.genind(Mcanis,permut=TRUE,
nsim=1000,hide.NA=TRUE,res.type=c("full","matrix")) #error; not genind
object

*Error in HWE.test.genind(Mcanis, permut = TRUE, nsim = 1000, hide.NA =
TRUE,  :   x is not a valid genind object*

**Comment by mgiresi** [comment]
I'm off to play some footie. I'll be back.

**Comment by thibautjombart** [comment]
It is the validation procedure that poses a problem in this case.
Duplicated labels?

**Comment by jgx65** [comment]
Both 'hierfstat' and 'adegenet' have a function 'read.fstat', but (for the time being), only that from 'adegenet' will produce a genind object.  Could it be that you were using the 'read.fstat' function from 'hierfstat'? You can check by using 'adegenet::read.fstat'

**Comment by thibautjombart** [comment]
Nope, read.fstat in adegenet uses its own implementation, and internally relies on `df2genind` which I optimized recently.

**Comment by jgx65** [comment]
Not sure I see your point @thibautjombart . It seems that all the `hierfstat` functions used in @mgiresi commands work, but not those from `adegenet`. Hence my guess that she might be using the hierfstat version of `hierfstat::read.fstat`.  Is this stupid?

**Comment by thibautjombart** [comment]
No, my comment was stupid - I read too fast and thought your comment was
for me and from a different thread ':-/
That's very likely the origin of the error.

**Comment by thibautjombart** [comment]
I had forgotten about this issue.
Because of the dependencies hierfstat will be loaded after adegenet, so `hierfstat::read.fstat` will be used over `adegenet::read.fstat`
@mgiresi : you would need to use `adegenet::read.fstat("McanisOnly.dat")` to get a genind.
@jgx65 : if genind is to become the default class used in hierfstat, what do you want to do with  hierfstat::read.fstat?
