### ISSUE TITLE
Retaining original locus names

### ISSUE THREAD

**Issue by cryptic0** [thibautjombart/adegenet#46]
Version: 2.0

When importing a structure data set as a genind object, original locus names are discarded and replaced with generic names.  Adegenet does assign unique generic names and when markers removed due to being 'entirely nontype' etc, the generic names aren't reshuffled (which is good and very important).

But the fix we really need is retention of original names i.e. truenames.  This is particularly necessary for data sets with very large number of loci.  Linking generic names back to actual names is cumbersome.

> mygenind <- import2genind('input.str', onerowperind=F, n.ind=5, n.loc=10, col.lab=1, col.pop=2, ask=F)
>  mygenind

   #####################
   ### Genind object ### 
   #####################
- genotypes of individuals - 

S4 class:  genind
@call: read.structure(file = file, n.ind = 5, n.loc = 10, onerowperind = ..1, 
    col.lab = 1, col.pop = 2, ask = ..6, quiet = quiet)

@tab:  5 x 20 matrix of genotypes

@ind.names: vector of  5 individual names
@loc.names: vector of  20 locus names
@loc.nall: number of alleles per locus
@loc.fac: locus factor for the  20 columns of @tab
@all.names: list of  20 components yielding allele names for each locus
@ploidy:  2 2 2 2 2 2
@type:  codom

Optional contents: 
@strata: - empty -
@hierarchy:  - empty -
@pop:  factor giving the population of each individual
@pop.names:  character giving the name of each population
@other: - empty -

> mygenind@loc.names
"L0001" "L0002" "L0003" "L0004" "L0005" "L0006" "L0007" "L0008" "L0009" "L0010"

**Comment by romunov** [comment]
Must be `read.structure` thing, because I get, as of 2.0.0 

```
> nancycats@loc.names
     L1      L2      L3      L4      L5      L6      L7      L8      L9 
 "fca8" "fca23" "fca43" "fca45" "fca77" "fca78" "fca90" "fca96" "fca37" 
```

**Comment by cryptic0** [comment]
romunov: How do you import data?  Note that I am not using read.structure(), rather import2genind().

**Comment by romunov** [comment]
Doh, realized too late, sorry. :)

**Comment by cryptic0** [comment]
Romunov: How did you import nancycats data set?

**Comment by romunov** [comment]
I misread the question, sorry. I used the `data(nancycats)` argument. If I try to import it from /files folder, loci names end up L0001... Because in the raw file, the files have no loci names.

**Comment by zkamvar** [comment]
You must specify the row that contains the names of the markers with the flag `row.marknames`.

**Comment by cryptic0** [comment]
Bingo. That was the problem.  Thanks Zhian.
