### ISSUE TITLE
Installation problems on Yosemite 10.10.3

### ISSUE THREAD

**Issue by cryptic0** [thibautjombart/adegenet#49]
devtools::install_github('thibautjombart/adegenet')

ERROR: dependencies ‘ade4’, ‘spdep’ are not available for package ‘adegenet’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/adegenet’
Error: Command failed (1)
In addition: Warning messages:
1: In utils::install.packages(deps, dependencies = NA, Ncpus = threads) :
  installation of package ‘ade4’ had non-zero exit status
2: In utils::install.packages(deps, dependencies = NA, Ncpus = threads) :
  installation of package ‘spdep’ had non-zero exit status
>

**Comment by thibautjombart** [comment]
Can you try installing these packages first?
```r
install.packages(c("ade4","spdep")
```
etc. ?

**Comment by cryptic0** [comment]
I tried and those failed as well:  http://pastebin.com/nWNPJ9bq

**Comment by thibautjombart** [comment]
It looks like you are missing some linkers or compilers on your system for ade4 / spdep. This is not a package-specific issue. I am not a Mac user so unfortunately I can't help much. You probably want to install fortran, C, C++ compilers and relevant libraries. Alternatively, you would need to install Mac binaries.

**Comment by cryptic0** [comment]
I installed gfortran, xcode with commandline tools.  Then rebooted the mac, installed ade4 and spdep successfully, and then adegenet and poppr from github.  All is well now, thanks.

**Comment by thibautjombart** [comment]
Awesome!
