### ISSUE TITLE
Function to convert old data to version 2.0

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#51]
I don't know if this should be a function or simply just a gist, but to help people convert from adegenet 1.4 to 2.0, should we include a couple of converter functions that will add slots and reparse data to be in the right format?

I have a function called `data_replacer` [in this gist](https://gist.github.com/zkamvar/50c4a98e67aa2a697339) that will convert genind (and genclone) objects, but one would need to be created for genlight objects (not too hard, just adding hierarchy and strata slots). 

Again, should this be a formal set of functions or should we just point the users to a gist that they can download and run?

**Comment by romunov** [comment]
I think it doesn't really matter, as long as the user is clear that there's a migration process involved (explicit "warning", documented in the help file...). I would consider adding a generic function that detects object class and does the conversion and orphan it in 6-12 months.

**Comment by thibautjombart** [comment]
I think it is useful, and a welcome addition to the package. Back in the days I had created a function old2new, which is still around, and could just be updated?
https://github.com/thibautjombart/adegenet/blob/master/R/old2new.R

**Comment by zkamvar** [comment]
No reason not to update that function. I'll close this when I do that for the genind and genlight objects.

**Comment by thibautjombart** [comment]
Awesome, thanks!

**Comment by zkamvar** [comment]
I have added methods for genind and genlight. Were there any significant changes for genpop objects?

**Comment by thibautjombart** [comment]
Awesome, thanks!
genpop changes: just in the naming of the @tab: we dropped generic names
there too. All same otherwise.

**Comment by thibautjombart** [comment]
Sorry not being very active on github - still stranded in Sierra Leone.

**Comment by thierrygosselin** [comment]
For job or fun ?

for genepop imported files into adegenet, where are the individuals names stored, or they are not anymore ?

**Comment by zkamvar** [comment]
Done!
