### ISSUE TITLE
pairwise.fst() not working in 2.0.0

### ISSUE THREAD

**Issue by cryptic0** [thibautjombart/adegenet#52]
"mygenind" is a list containing multiple genind objects, each imported from an individual structure file.

myseploc <- seploc(mygenind, truenames=TRUE)

myfst <- lapply(myseploc, function(x) pairwise.fst(x))
This function has been moved to the package hierfstat. You can still use it in adegenet, but this version is deprecated.
Error in pairwise.fst(x) : x is not a valid genind object

Also tried:
library(parallel)
cl <- makeCluster(2)
clusterExport(cl, "pairwise.fst")
myfst <- parLapply(cl, myseploc, function(x) pairwise.fst(x))
Same deprecated version error as above.

myfst <-parLapply(cl, myseploc, function(x) pp.fst(x))
Error: incorrect number of dimensions

**Comment by thibautjombart** [comment]
Thanks for the report. Can you post a link to a RData of 'mygenind' so that we can reproduce the error?

**Comment by cryptic0** [comment]
Here is a link to the mygenind RData object: https://www.dropbox.com/sh/poijn4bfghpkbe4/AACjGBT_yCZ030EBpu1qZBjaa?dl=0

**Comment by zkamvar** [comment]
@cryptic0, I believe that this should fix your problem. Please check with your data. If it works, then kindly close this issue.

Thanks,
Zhian

**Comment by cryptic0** [comment]
Hi Zhian, 

How do I update adegenet to test this? I have the github installed version.

Thanks.

**Comment by cryptic0** [comment]
Updated adegenet with:
devtools::install_github('thibautjombart/adegenet')

## Load the RData object containing a list of genind objects
load('mygenind.RData', envir=parent_frame())

## Separate loci
> myseploc <- lapply(mygenind, function(x) seploc(x))

## Estimate pairwise Fst
> system.time(myfst <- lapply(myseploc, function(x) pairwise.fst(x)))
This function has been moved to the package hierfstat. You can still use it in adegenet, but this version is deprecated.
Error in pairwise.fst(x) : x is not a valid genind object
Timing stopped at: 0.001 0 0.002 

> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
Running under: OS X 10.8.5 (Mountain Lion)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] adegenet_2.0.0 ade4_1.6-2

**Comment by zkamvar** [comment]
You are attempting to run `pairwise.fst` on lists of loci. You need another `lapply`

**Comment by cryptic0** [comment]
I am not sure if I understand.  Are you perhaps suggesting that seploc is a list within list (i.e. nested list) and a single lapply function will not work?  Can you show an example?  Also, why do I still get the 'x is not a valid genind object error'?

**Comment by thibautjombart** [comment]
I don't understand this:
```r
myseploc <- lapply(mygenind, function(x) seploc(x))
```
Why lapply over a genind object? 
I think you need e.g.
```r
myseploc <- seploc(mygenind)
```
Then you won't have to handle a list of lists.

**Comment by cryptic0** [comment]
Hi Thibaut,

That lapply is needed because mygenind itself it a list of many genind
objects.

> seploc2 <- seploc(mygenind)
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘seploc’ for signature
‘"list"’

Thanks
V

**Comment by thibautjombart** [comment]
Then Zhian is right, you need nested lapply, because you have a list of lists of genind objects (seploc returns a list).
Here's an example using Hs:
```r
> library(adegenet)
Loading required package: ade4
   ==========================
    adegenet 2.0.0 is loaded
   ==========================

 - to start: type '?adegenet'
 - to browse the adegenet website: type 'adegenetWeb()'
 - to post questions/comments: adegenet-forum@lists.r-forge.r-project.org
 - to report bugs, request features, contribute: http://goo.gl/dZuu5X


> data(sim2pop)
> temp <- lapply(seppop(sim2pop), seploc)
> lapply(temp, lapply, Hs)
$`Pop A`
$`Pop A`$L01
 Pop A 
0.8338 

$`Pop A`$L02
  Pop A 
0.61765 

$`Pop A`$L03
  Pop A 
0.85375 

$`Pop A`$L04
 Pop A 
0.6969 

$`Pop A`$L05
  Pop A 
0.73985 

$`Pop A`$L06
  Pop A 
0.71675 

$`Pop A`$L07
  Pop A 
0.52635 

$`Pop A`$L08
  Pop A 
0.79335 
...

```

**Comment by cryptic0** [comment]
Following your example, I tried the nested lapply:

> myfst <- lapply(myseploc, lapply, pairwise.fst)

Error in dimnames(out) <- list(rownames(out), colnames(out)) :
  'dimnames' applied to non-array

**Comment by zkamvar** [comment]
Are your genind objects supposed to have severe differences in ploidy? 

```r
> tab(mygenind[[1]])[1:10, 1:10]
    L0001.1 L0001.2 L0002.2 L0002.1 L0003.2 L0003.1 L0004.2 L0004.1 L0005.2 L0005.1
001       2       4       6       0       3       3       6       0       6       0
002       2       4       6       0       3       3       6       0       6       0
003       2       0       2       0       2       0       2       0       2       0
004       2       0       2       0       1       1       2       0       2       0
005       4       0       4       0       3       1       4       0       4       0
006       1       1       2       0       1       1       2       0       2       0
007       4       0       4       0       2       2       4       0       4       0
008       4       2       6       0       2       4       6       0       6       0
009       4       2       6       0       2       4       6       0       6       0
010       2       2       4       0       2       2       4       0       4       0

> ploidy(mygenind[[1]])
  [1] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 [49] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 [97] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[145] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[193] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[241] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[289] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[337] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[385] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[433] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[481] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[529] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
[577] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
```

**Comment by cryptic0** [comment]
It's simulated data and all samples should be diploid.  Your ploidy()
output also confirms it.  Output is identical for mygenind[[2]] and
mygenind[[3]].

**Comment by zkamvar** [comment]
The ploidy output is based on the user input. The output of `tab()` shows that your samples vary widely in ploidy: 6, 6, 2, 4, ... etc.

**Comment by cryptic0** [comment]
Something very strange is happening.  I checked a random file in my simulation data.  Let's call this lnr10_2u_iter15.str which is a structure file.

mygenind <- import2genind('lnr10_2u_iter15.str', onerowperind=F, row.marknames=1, n.ind=600, n.loc=1000, col.lab=1, col.pop=2, ask=F)

> tab(mygenind[1:20,1:20])
    locus1.1 locus1.2 locus2.2 locus2.1 locus3.2 locus3.1 locus4.2 locus4.1
001        2        4        6        0        3        3        6        0
002        2        4        6        0        3        3        6        0
003        2        0        2        0        2        0        2        0
004        2        0        2        0        1        1        2        0
005        4        0        4        0        3        1        4        0
006        1        1        2        0        1        1        2        0
007        4        0        4        0        2        2        4        0
008        4        2        6        0        2        4        6        0
009        4        2        6        0        2        4        6        0
010        2        2        4        0        2        2        4        0
011        0        2        1        1        2        0        2        0
012        1        1        2        0        1        1        2        0
013        1        1        2        0        1        1        2        0
014        0        2        2        0        2        0        2        0
015        4        0        4        0        2        2        4        0
016        1        1        2        0        1        1        2        0
017        2        0        2        0        1        1        2        0
018        1        1        1        1        1        1        2        0
019        2        0        1        1        1        1        2        0
020        2        0        2        0        1        1        2        0
    locus5.2 locus5.1 locus6.1 locus6.2 locus7.1 locus7.2 locus8.1 locus8.2
001        6        0        3        3        1        5        2        4
002        6        0        3        3        1        5        2        4
003        2        0        1        1        0        2        0        2
004        2        0        1        1        0        2        0        2
005        4        0        2        2        0        4        3        1
006        2        0        2        0        1        1        0        2
007        4        0        2        2        0        4        3        1
008        6        0        5        1        0        6        2        4
009        6        0        5        1        0        6        2        4
010        4        0        1        3        0        4        3        1
011        2        0        1        1        0        2        1        1
012        2        0        1        1        0        2        0        2
013        2        0        1        1        0        2        1        1
014        2        0        1        1        0        2        2        0
015        4        0        2        2        0        4        3        1
016        2        0        1        1        0        2        0        2
017        2        0        1        1        0        2        1        1
018        2        0        2        0        0        2        0        2
019        2        0        2        0        0        2        0        2
020        2        0        1        1        0        2        0        2

However, if you look at the structure file in a text editor, you will notice that every individual is on two lines with genotype of '12', '11' or '22', representing two SNP alleles.  I can't quite comprehend why this table is showing very different information?  

FYI, I have placed the structure file here:
https://www.dropbox.com/s/j3fdjuvw89oeavz/lnr10_2u_iter15.str?dl=0

**Comment by cryptic0** [comment]
Okay, I think I may have figured it out.  This being simulated data that ran for 100 generations, some individual names have been duplicated.  For example, T99M145F157Pop8 appears more than once (there are many more example).  So while adegenet is detecting this and switching to generic names, it has already summed number of alleles from separate occurrences of this individual across several pops.  That leads to an increased ploidy.

Does that make sense?

**Comment by zkamvar** [comment]
I believe this is correct. I will open a new issue with this particular bug.

**Comment by cryptic0** [comment]
Hi Zhian,

Has the bug fix been incorporated in the main github repository yet?  I just pulled adegenet from github and this bug still exists.

**Comment by zkamvar** [comment]
Yes, it has. Using your data, I get this:

```r
> mygenind <- import2genind('~/Downloads/lnr10_2u_iter15.str', onerowperind=F, row.marknames=1, n.ind=600, n.loc=1000, col.lab=1, col.pop=2, ask=F)

 Converting data from a STRUCTURE .stru file to a genind object... 

Warning message:
In df2genind(X = X, pop = pop, ploidy = 2, sep = sep, ncode = ncode) :
  duplicate labels detected for some individuals; using generic labels
> tab(mygenind)[1:10, 1:10]
    locus1.1 locus1.2 locus2.2 locus2.1 locus3.2 locus3.1 locus4.2 locus4.1 locus5.2 locus5.1
001        2        0        2        0        2        0        2        0        2        0
002        0        2        2        0        1        1        2        0        2        0
003        2        0        2        0        2        0        2        0        2        0
004        2        0        2        0        1        1        2        0        2        0
005        2        0        2        0        1        1        2        0        2        0
006        1        1        2        0        1        1        2        0        2        0
007        2        0        2        0        1        1        2        0        2        0
008        2        0        2        0        0        2        2        0        2        0
009        1        1        2        0        2        0        2        0        2        0
010        1        1        2        0        1        1        2        0        2        0
```

I indeed get the pairwise.fst error. I traced it to populations 16 and 17. It likely has something to do with the fact that they are both fixed for the same allele:

```r
> tab(seploc(mygenind[pop(mygenind) %in% popNames(mygenind)[16:17]])[[1]])
    locus1.1 locus1.2
441        0        2
442        0        2
443        0        2
444        0        2
445        0        2
446        0        2
447        0        2
448        0        2
449        0        2
450        0        2
451        0        2
452        0        2
453        0        2
454        0        2
455        0        2
456        0        2
457        0        2
458        0        2
459        0        2
460        0        2
461        0        2
462        0        2
463        0        2
464        0        2
465        0        2
466        0        2
467        0        2
468        0        2
469        0        2
470        0        2
471        0        2
472        0        2
473        0        2
474        0        2
475        0        2
476        0        2
477        0        2
478        0        2
479        0        2
480        0        2
```

**Comment by cryptic0** [comment]
How do I pull the most up to date version?  I have been doing 
> devtools::install_github('thibautjombart/adegenet').

**Comment by zkamvar** [comment]
That is pulling the most up to date version. I haven't fixed the fst bug yet. I will reference this issue when that happens.

**Comment by zkamvar** [comment]
Hi, 

I believe I have fixed it. The issue was indeed due to the fact that both populations were fixed for the same allele at that locus. Let me know if this works for you.

**Comment by cryptic0** [comment]
Hi Zhian,

I pulled from github again and ran the pairwise.fst function.  No errors this time around.  How often does it spit out the 'deprecated function' message? I am guessing after every locus.  There are 1000 loci in each of the three list objects inside 'mygenind'. The function has been running for 638 minutes and has gone through about 1658 loci.  So it's a little over half way done.

I will another test with a smaller dataset just to get a final output.  But I don't know if it's worth your time anymore given that the function is not very efficient.  Just for comparison, the diffCalc function from diveRsity estimates pairwise per locus FSTs for a data set consisting of 1000 loci, 30 pops and 600 individuals (20 per pop) in under 60 seconds.  

That said, all the work you put in here is greatly appreciated.  I am closing this thread now.  Thanks.
