### ISSUE TITLE
Bug reported by CRAN

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/adegenet#53]
Dear maintainers,

This concerns the packages

  SASxport adegenet apex gstudio mmod qdapDictionaries

maintained by one of you, which now fail in r-devel due to

  \subsection{SIGNIFICANT USER-VISIBLE CHANGES}{
    \itemize{
      \item \code{nchar(x, *)} gains a new argument \code{keepNA} which
      governs how the result for \code{NA}s in \code{x} is determined.
      The new default \code{keepNA = NA} returns \code{NA} where
      \code{x} is \code{NA}, unless for \code{type = "width"} which still
      returns \code{2}, the formatting / printing width of \code{NA}.

      \code{nzchar(x)} gets the same new argument, with default
      \code{keepNA = FALSE} however.  Consequently \code{nzchar(x)} keeps
      returning a non-\code{NA} logical vector, back compatibly.
    }
  }

Can you please provide updates of your packages which work again under
current r-devel within the next 2 weeks?

When doing so, pls make sure you address all issues shown on your
package check pages.

Best
-k

**Comment by zkamvar** [comment]
Here's something that's readable:

## SIGNIFICANT USER-VISIBLE CHANGES

- `nchar(x, *)` gains a new argument `keepNA` which governs how the result for NAs in x is determined. The new default `keepNA = NA` returns NA where x is NA, unless for `type = "width"` which still returns 2, the formatting / printing width of NA.

- `nzchar(x)` gets the same new argument, with default `keepNA = FALSE` however. Consequently `nzchar(x)` keeps returning a non-NA logical vector, back compatibly.

**Comment by thibautjombart** [comment]
Can't reproduce that. Passing the check now anyway.
