### ISSUE TITLE
not able to install adegenet

### ISSUE THREAD

**Issue by ragavishn** [thibautjombart/adegenet#56]
Dear Authors,
I have been trying to install the package adegenet for my data analysis project. I am not able to install it successfully.  I am using R version 3.0.2.  Please let me know if i need to switch to the older version of R or you have the updated package available somewhere. I am following the tutorial from the following link. 

http://adegenet.r-forge.r-project.org/files/simGWAS/MSc-GWAS-1.1.pdf

It would be great if you can reply as soon as possible. Thanks a lot.

#####################################Error when installing adegenet################
ERROR: dependency ‘plyr’ is not available for package ‘reshape2’
* removing ‘/home/sragavi/R/x86_64-redhat-linux-gnu-library/3.0/reshape2’
Warning in install.packages :
  installation of package ‘reshape2’ had non-zero exit status
ERROR: dependency ‘plyr’ is not available for package ‘scales’
* removing ‘/home/sragavi/R/x86_64-redhat-linux-gnu-library/3.0/scales’
Warning in install.packages :
  installation of package ‘scales’ had non-zero exit status
ERROR: dependencies ‘plyr’, ‘reshape2’, ‘scales’ are not available for package ‘ggplot2’
* removing ‘/home/sragavi/R/x86_64-redhat-linux-gnu-library/3.0/ggplot2’
Warning in install.packages :
  installation of package ‘ggplot2’ had non-zero exit status
ERROR: dependency ‘ggplot2’ is not available for package ‘adegenet’
* removing ‘/home/sragavi/R/x86_64-redhat-linux-gnu-library/3.0/adegenet’
Warning in install.packages :
  installation of package ‘adegenet’ had non-zero exit status
ERROR: dependency ‘adegenet’ is not available for package ‘pegas’
* removing ‘/home/sragavi/R/x86_64-redhat-linux-gnu-library/3.0/pegas’
Warning in install.packages :
  installation of package ‘pegas’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpX10ZbU/downloaded_packages’

**Comment by zkamvar** [comment]
Try installing 'plyr' manually

**Comment by ragavishn** [comment]
I am not able to install this because I think it is not available for the R version I am using. Would you recommend going back to older version?

**Comment by zkamvar** [comment]
Is there a reason not to update your current R version? R is currently at version 3.2. Since you're on a linux system, you can install plyr from the CRAN archives:

http://cran.rstudio.com/src/contrib/Archive/plyr/

As long as you install one that is not dependent on R version 3.1, then you're okay.

**Comment by ragavishn** [comment]
Thanks a lot for your time and inputs. That worked!
