### ISSUE TITLE
Further reforms of the classes

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/adegenet#57]
I am pondering making other changes to the genind/genpop classes. 
Basically, we have dropped the generic label system. Meaning that now the slots:
- ind.names
- loc.names
- all.names
- pop.names

Can be removed. I am trying to think of cases where it will be useful to have alternative labels as an option. I think it makes sense for alleles, e.g. when using MLST-like data where an allele is a sequence of a gene. I am not sure the other should stay. 

@zkamvar @EricArcher @thierrygosselin @emmanuelparadis @jgx65 @caitiecollins 
What do you think?

**Comment by zkamvar** [comment]
ind.names and pop.names are fairly redundant and can easily be removed.

The all.names slot is useful because it makes allele calls easier to check for things like microsatellite lengths.

**Comment by thibautjombart** [comment]
I agree. And that means I only need to tweak the accessor `alleles` to add an option to get names from @tab or from @all.names
Makes sense?

**Comment by thibautjombart** [comment]
Done. 
Also changed the printing of the objects a bit.. 
```r
> microbov
/// genind object \\\

 // Basic content
   @tab:  704 x 373 matrix of allele counts
   @loc.nall: number of alleles per locus (range: 5-22)
   @loc.fac: locus factor for the 373 columns of @tab
   @all.names: list of allele names for each locus
   @ploidy: ploidy of each individual  (range: 2-2)
   @type:  codom
   @call: genind(tab = truenames(microbov)$tab, pop = truenames(microbov)$pop)

 // Optional content
   @pop:  population of each individual (group size range: 30-61)
   @strata: - empty -
   @hierarchy:  - empty -
   @other: a list containing: coun  breed  spe 

> 
```

**Comment by zkamvar** [comment]
:+1: dat meta information!

I believe there are still things to be done on this, though.

in 349edf97703dc6, you added `accessors.R` to the collate field, but removed all of the accessor functions and didn't push any new files.

**Comment by emmanuelparadis** [comment]
Hi Thibaut,
From pegas's point of view, the basic requirement is the functions df2genind and genind2df which are called to convert from/to loci. So as long as these functions are there, it's all fine for me.
Cheers,
Emmanuel

**Comment by thibautjombart** [comment]
Sorry - fixed in 75ca1212961a88dfed8fb6. 
@emmanuelparadis Yes that bit should not change. 
The following replacements will be needed for some accession:
x@loc.names => locNames(x)
x@ind.names => indNames(x)
x@pop.names => popNames(x)

**Comment by thibautjombart** [comment]
I'm closing this now, assuming all is fixed, but feel free to reopen if needed or if you have further suggestions / comments.

**Comment by thibautjombart** [comment]
I'm re-opening hopefully one last time as I have changed a slot for name consistency and added accessors.
Changed slot: 
```r
@loc.nall => @loc.n.all
```
New accessors: `nAll` (returns `@loc.n.all`) and `locFac` (returns `loc.fac`).
@zkamvar @EricArcher @I hope this won't be a problem for your packages?

**Comment by thibautjombart** [comment]
Should be okay from 6f2e9fbd4ade59329a1d42b1d7d1b5e84db99244 onwards - check passing.

**Comment by EricArcher** [comment]
No problems for me. I'm going to be finishing up modifications to strataG
in the next week or so, so now is a perfect time for this.


----

*Eric Archer, Ph.D.*
Southwest Fisheries Science Center
NMFS, NOAA
8901 La Jolla Shores Drive
La Jolla, CA 92037 USA
858-546-7121 (work)
858-546-7003 (FAX)

Marine Mammal Genetics Group: swfsc.noaa.gov/mmtd-mmgenetics
ETP Cetacean Assessment Program: swfsc.noaa.gov/mmtd-etp

"


*The universe doesn't care what you believe. The wonderful thing about
science is that it   doesn't ask for your faith, it just asks   for your
eyes.*"  - Randall Munroe

"*Lighthouses are more helpful than churches.*"
   - Benjamin Franklin

   "*...but I'll take a GPS over either one.*"
       - John C. "Craig" George

**Comment by thibautjombart** [comment]
Awesome! I can't wait to see adegenet 2.0.0 out, and see it play nicely along with other package :)

**Comment by zkamvar** [comment]
:sweat_smile: It should be fine for me. It'll probably take less than an hour of messing around in poppr to get everything synched.

**Comment by zkamvar** [comment]
I wonder, is it possible to define these methods for the gen object since both genind and genpop inherit it?

**Comment by thibautjombart** [comment]
Sorry about that. But I'm thinking if these kind of changes are to happen, it is now or never.
Yes it should be possible to define methods for 'gen' instead. Would save some coding / avoid redundancy. These are mostly cosmetic internal changes though - I'm focusing on the basics tutorial at the moment.

**Comment by zkamvar** [comment]
The changes are definitely a good thing. I'm just complaining to the wind. 


Regarding the methods for 'gen': with some testing, it seems that it is indeed possible, but requires a new man page for the accessors to the gen object :disappointed:. Nevertheless, I'm going to try to convert them and then write a new, internal man page for the gen methods.

**Comment by zkamvar** [comment]
For my own notes: Here's a document that [confirms the use of methods for virtual classes](https://www.stat.auckland.ac.nz/S-Workshop/Gentleman/S4Objects.pdf)

**Comment by thibautjombart** [comment]
It makes total sense to be able to define methods for virtual classes.. well, this is a good example really ;) 
Thanks for giving it a go. Meanwhile, once the basics tutorial is sorted, the rest should follow..

**Comment by zkamvar** [comment]
So, I've been running into the problem of old2new not working anymore because the old classes are no longer valid since they have extra slots. I think these methods just have to be converted to functions for each data type (e.g. `old2new_genind`, `old2new_genpop`, `old2new_genlight`) using underscores to avoid R thinking we want S3 methods.

**Comment by thibautjombart** [comment]
Yes I was afraid of that. I bumped into it today myself. I actually found a tweak to rename slots / remove slots / add slots to an existing genind/genpop. E.g. what I used to rename loc.nall into loc.n.all and purge all unwanted slots from the datasets (nancycats etc):
```r
  cleanGenind <- function(x){
       names(attributes(x))[4] <- "loc.n.all"
       attributes(x) <- attributes(x)[slotNames(new("genind"))]
       class(x) <- "genind"
       return(x)
   }
}
```

**Comment by romunov** [comment]
Should we provide a method for `x@all.names` slot as well?

**Comment by zkamvar** [comment]
That's the `alleles()` method.
