### ISSUE TITLE
check stops at xvalDapc

### ISSUE THREAD

**Issue by romunov** [thibautjombart/adegenet#63]
I've pushed up an experimental [exp_basicMethods](https://github.com/thibautjombart/adegenet/tree/exp_basicMethods) branch that passes summary test (using devtools `test("adegenet")`) but stop at xvalDapc. I suggest we solve the testing issues there and merge the branch into the master. Unless someone is already working on this already on the master branch?

**Comment by zkamvar** [comment]
The tests work on my machine:

```R
devtools::test()

Loading adegenet
Loading required package: ade4
Creating a generic function for ‘summary’ from package ‘base’ in package ‘adegenet’
Creating a generic function for ‘plot’ from package ‘graphics’ in package ‘adegenet’

   /// adegenet 2.0.0 is loaded ////////////

   > overview: '?adegenet'
   > tutorials/doc/questions: 'adegenetWeb()' 
   > bug reports/feature resquests: adegenetIssues()


Testing adegenet
Accessor tests : .................................................
constructor tests : ....
Genlight construction : .............
Strata methods : .................
Import Tests : .............
Repool tests : ............
subset tests : 
Summary methods : ......
xvalDapc test : .....
Test PropShared : ....

DONE 
```

**Comment by romunov** [comment]
This is what I get. Technically it's a warning, but not reassuring. :)

```
xvalDapc test : .....

Warning messages:
1: Strata must be length 1. Taking the first column. 
2: In df2genind(x, ploidy = 1) :
  duplicate labels detected for some individuals; using generic labels
3: In df2genind(x, ploidy = 1) :
  duplicate labels detected for some loci; using generic labels
```

**Comment by caitiecollins** [comment]
Hi,

Sounds like I should take a look at this and make sure everything's fine.
Thanks for letting me know.
I'll take a look at it tomorrow.

Cheers,
Caitlin.

**Comment by zkamvar** [comment]
These warnings are purposeful.

The first comes from [here](https://github.com/thibautjombart/adegenet/blob/6581619f0b03c3366a6997bd53479872460b87bb/tests/testthat/test_hierarchy.R#L15)

The other two come from [here](https://github.com/thibautjombart/adegenet/blob/master/tests/testthat/test_import.R#L40)

**Comment by thibautjombart** [comment]
Is it still a problem? Current version has been merged into newfeatures and then the master and passes the check..

**Comment by romunov** [comment]
All good then.
