### ISSUE TITLE
add explicit imports for non-base functions

### ISSUE THREAD

**Issue by zkamvar** [thibautjombart/adegenet#68]
A new policy is to be implemented from CRAN [in the current R-devel](http://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2015/06/29#n2015-06-29):

> `R CMD check --as-cran` now checks code usage (via `codetools`) with only the base package attached, so that functions from default packages other than base which are used in the package code but not imported are reported as undefined globals.

[See this twitter thread](https://twitter.com/thosjleeper/status/615446807519305729) for details on why this is so. It might be as simple as doing something like `#' @import stats` and then using something like `<pkg>::<fun>` within the code to fix it.

**Comment by thibautjombart** [comment]
Good to know! It may need to incorporate the last-minute checks before submission on Monday

**Comment by thibautjombart** [comment]
Sorted by brute force - now importing utils, grDevices, stats.
