### ISSUE TITLE
locNames(genind-class) no longer returns the same type of data

### ISSUE THREAD

**Issue by steveped** [thibautjombart/adegenet#69]
Hi,

The output from this function has changed significantly in v2.0.0 such that what was a named vector, now just returns the names without the attached values. Is this permanent, or a bug?

I did have an error message from the object saying something along the lines of "error in @loc.n.all no method exists for this object type", but I foolishly uninstalled the package & rolled back to v1.4.2 (which works perfectly) before noting the exact message.

The above, i.e. locNames(genind-class) is the line that broke my code though. My apologies for the poor question & lack of reproducible example.

Steve

**Comment by thibautjombart** [comment]
Hi Steve, 
this is not a bug. This is due to the fact that generic labels have been dropped in adegenet 2.0.0. Also, note that @loc.names is no longer part of genind objects. See the [ChangeLog](https://github.com/thibautjombart/adegenet/blob/master/ChangeLog) for an outline of all the changes.
