### ISSUE TITLE
sPCA: Error in if (nf > rank) nf <- rank message

### ISSUE THREAD

**Issue by JonathanKing2015** [thibautjombart/adegenet#70]
Hello all,

I'm attempting to recreate a similar figure to the one seen in Sarno et al. (http://www.plosone.org/article/fetchObject.action?uri=info:doi/10.1371/journal.pone.0096074&representation=PDF). To do so, I created a matrix that contains populations (rows) and Y-STR haplogroups (columns). Additionally, due to my inexperience with adegenet, I created a coordinates list. I then did the following.

Function:

```r
mydata <- genpop(HGF,ploidy=1)
```

Result:
Object created

Function:

```r
spca(mydata,xy=xy,d1=0,d2=5)
```

Result:
Plot created
[cid:image003.jpg at 01D0B4E0.1EA1AB50]

Now comes the problem.

Function:

```r
myspca<-spca(mydata,xy=xy,type=5,d1=0,d2=5)
```

Result:
No "myspca" list is created and I get the following error

```r
Error in if (nf > rank) nf <- rank :

  missing value where TRUE/FALSE needed

```

I feel that if I can obtain the eig values for the dataset the rest will be smooth sailing; however, I am unable to find any similar instances on the forum (some people have mentioned this general error in regard to clustering but not spca).

I can gladly provide supporting files if it would be of some use.

Any help is greatly appreciated. Thanks in advance. 

Jonathan King

**Comment by thibautjombart** [comment]
Hi there, 

hard to tell without checking the input data.. did you check what your connection network looks like? You can do so using chooseCN, and then pass it to the spca. 

Unrelated, but: we may end up using the issues system for general questions in the future, but for now the adegenet forum is still the preferred way for this:
http://lists.r-forge.r-project.org/cgi-bin/mailman/listinfo/adegenet-forum

**Comment by thibautjombart** [comment]
sorry - just saw this message was being held for moderation ;)

**Comment by JonathanKing2015** [comment]
Hi Jombart,

I have posted this message on the adegent forum; however, haven’t received a response and though I would try the github message board as an alternative.

I really appreciate any help you’re able to provide

Jonathan King
Research and Development Lab Manager
Institute of Applied Genetics
UNT Health Science Center
3500 Camp Bowie Blvd
Fort Worth, TX 76107
Office: 817-735-2773
Phone: 817-735-2940
Research and Development Lab<https://www.unthsc.edu/graduate-school-of-biomedical-sciences/molecular-and-medical-genetics/laboratory-faculty-and-staff/>
