### ISSUE TITLE
minor allele frequency

### ISSUE THREAD

**Issue by Carlo86** [thibautjombart/adegenet#82]
Hi all,

I would like to calculate the minor allele frequency for my data.

**Comment by thibautjombart** [comment]
Yep, should be simple enough. Will have a look.

**Comment by thibautjombart** [comment]
Something like this should work:
```r
tapply(apply(tab(x, freq=TRUE),2,mean, na.rm=TRUE), locFac(x), function(e) sort(e,decreasing=TRUE)[2])
```
with `x` being your genind

**Comment by thibautjombart** [comment]
I had forgotten that there is a `isPoly` function. Added anyway as of 
  090c99
