### ISSUE TITLE
possible bug in df2genind

### ISSUE THREAD

**Issue by juance100** [thibautjombart/adegenet#89]
There seems to be a bug in the conversion df2genind. I made the following test:
> catsdf <- genind2df(nancycats)
and then I converted the df catsdf to a genind object with
> nancycats2 <- df2genind(catsdf[,2:10], sep=NULL, ncode=3, pop=catsdf[,1], ploidy=2, type="codom")
Up to now everything seems to work fine. Indeed, summary(nancycats2) gives the expected results, however a fail occurs when trying to test HW equilibrium with hw.test(pegas):
> nancy2hw <- hw.test(nancycats2)
There were 18 warnings (use warnings() to see them)
> warnings()
Warning messages: "#sorry for the Spanish" 
1: In O - E : longitud de objeto mayor no es múltiplo de la longitud de uno menor
2: In (O - E)^2/E :
  longitud de objeto mayor no es múltiplo de la longitud de uno menor
...........

And the chi square estimates differ from those obtained using the original nancycats object:
> nancy2hw
            chi^2  df  Pr(chi^2 >) Pr.exact
fca8  46504.45655 120 0.000000e+00        0
fca23  2023.71668  55 0.000000e+00        0
fca43  7957.23992  45 0.000000e+00        0
fca45    93.25975  36 5.681616e-07        0
fca77 21636.11122  66 0.000000e+00        0
fca78  1072.03868  28 0.000000e+00        0
fca90 11361.25571  66 0.000000e+00        0
fca96   825.46134  66 0.000000e+00        0
fca37  2283.46490 153 0.000000e+00        0

Here we are the original estimates
> (nancyhw <- hw.test(nancycats))
          chi^2  df  Pr(chi^2 >) Pr.exact
fca8  395.80006 120 0.000000e+00        0
fca23 239.34221  55 0.000000e+00        0
fca43 434.33397  45 0.000000e+00        0
fca45  66.11849  36 1.622163e-03        0
fca77 270.52066  66 0.000000e+00        0
fca78 402.80002  28 0.000000e+00        0
fca90 217.19836  66 0.000000e+00        0
fca96 193.36764  66 1.965095e-14        0
fca37 291.00731 153 1.209777e-10        0

**Comment by thibautjombart** [comment]
Hi there, 
this was a documented issue with pegas (not adegenet) 
https://github.com/emmanuelparadis/pegas/issues/10
But it has been fixed now.
Thanks for the report all the same!

**Comment by juance100** [comment]
Thanks for your answer. Apparently the issue in pegas still remains, as 
I have just reinstalled pegas from github and the fail persists.
Best regards
Juan

Dr. Juan Cesar Vilardi
Depto Ecologia, Genetica y Evolucion
Fac. Ciencias Exactas y Naturales
Universidad de Buenos Aires
1428 Buenos Aires-Argentina

**Comment by thibautjombart** [comment]
Can you report this on the pegas issue?

**Comment by juance100** [comment]
Yes, I'll do it

Dr. Juan Cesar Vilardi
Depto Ecologia, Genetica y Evolucion
Fac. Ciencias Exactas y Naturales
Universidad de Buenos Aires
1428 Buenos Aires-Argentina
