### ISSUE TITLE
Bug in hybridize?

### ISSUE THREAD

**Issue by vilopr** [thibautjombart/adegenet#90]
Hello -
I am encountering problems when trying to simulate multiple generations of hybridization. In some cases, the program appears to be adding new names for the first one or two loci in the output file created by hybridize, shifting the real names along. Then I am unable to create the next generation of hybrids - instead I get the error: Error in repool(x1, x2) : markers are not the same for all objects.

See example below, the final df shows the changed locus names.

```r
Pulmanki_a <- read.loci("Pulmanki2a.txt", loci.sep ="\t", allele.sep = "/", col.loci = 2:201, row.names =1, header=T)
Pulmanki_b <- read.loci("Pulmanki2b.txt", loci.sep ="\t", allele.sep = "/", col.loci = 2:201, row.names =1, header=T)
Escapee_a <- read.loci("Escapee2a.txt", loci.sep ="\t", allele.sep = "/", col.loci = 2:201, row.names =1, header=T)
Escapee_b <- read.loci("Escapee2b.txt", loci.sep ="\t", allele.sep = "/", col.loci = 2:201, row.names =1, header=T)

Pulmanki2 <-loci2genind(Pulmanki_a)
Pulmanki3 <- loci2genind(Pulmanki_b)
Escapee2 <- loci2genind(Escapee_a)
Escapee3 <- loci2genind(Escapee_b)

 Pulmanki_Gen1 <- hybridize(Pulmanki2, Pulmanki3, n=295, pop="Wild_Gen1", hyb.label="Wild_Gen1")
 Escapee_Gen1 <- hybridize(Escapee2, Escapee3, n=44, pop="Esc_Gen1", hyb.label="Esc_Gen1")
 Pulmanki_F1 <- hybridize (Pulmanki_Gen1, Escapee_Gen1, n=58, pop="F1", hyb.label="F1")
Error in repool(x1, x2) : markers are not the same for all objects



 Pulmanki2_df <- genind2df(Pulmanki2, sep = "/", usepop = TRUE)
 Pulmanki2_df [1:6,1:3]
           AX.87615520 AX.87719422 AX.87585108 AX.87538152 AX.87729905 AX.87395847
Pulmanki50         1/1         1/1         1/1         2/2         2/2         2/2
Pulmanki51         1/1         1/1         1/1         2/2         2/1         2/2
Pulmanki52         1/1         1/1         1/1         2/2         2/2         2/2


 Pulmanki3_df <- genind2df(Pulmanki3, sep = "/", usepop = TRUE)
 Pulmanki3_df [1:6,1:3]
            AX.87615520 AX.87719422 AX.87585108 AX.87538152 AX.87729905 AX.87395847
Pulmanki250         1/2         1/1         1/1         1/2         2/2         2/2
Pulmanki251         1/1         1/1         1/1         2/2         2/2         2/2
Pulmanki252         1/1         1/1         1/1         2/2         2/2         2/2


 Escapee2_df <- genind2df(Escapee2, sep = "/", usepop = TRUE)
 Escapee2_df [1:6,1:3]
          AX.87615520 AX.87719422 AX.87585108 AX.87538152 AX.87729905 AX.87395847
Escapee50         2/2         1/2         1/2         1/1         1/2         1/2
Escapee51         2/1         2/2         2/2         1/1         1/1         2/2
Escapee52         2/1         2/2         2/2         1/1         1/2         1/2


 Escapee3_df <- genind2df(Escapee3, sep = "/", usepop = TRUE)
 Escapee3_df [1:6,1:3]
           AX.87615520 AX.87719422 AX.87585108 AX.87538152 AX.87729905 AX.87395847
Escapee250         2/2         2/2         2/2         1/1         2/2         1/2
Escapee251         2/2         2/2         2/2         1/1         1/1         1/1
Escapee252         1/1         2/1         2/2         1/1         1/1         1/2


 Escapee_Gen1_df <-  genind2df(Escapee_Gen1, sep = "/", usepop = TRUE)
 Escapee_Gen1_df [1:3,1:6]
                pop AX.86902765 AX.86903466 AX.86914366 AX.86917124 AX.86920308
Esc_Gen101 Esc_Gen1         1/1         2/2         2/2         1/2         2/2
Esc_Gen102 Esc_Gen1         1/1         1/2         2/2         2/2         2/2
Esc_Gen103 Esc_Gen1         1/2         1/2         2/2         2/2         1/2


 Pulmanki_Gen1_df <-  genind2df(Pulmanki_Gen1, sep = "/", usepop = TRUE)
 Pulmanki_Gen1_df [1:3,1:6]
                   pop   2 AX.86902765 AX.86903466 AX.86914366 AX.86917124
Wild_Gen1001 Wild_Gen1 2/2         1/2         2/2         2/2         2/2
Wild_Gen1002 Wild_Gen1 2/2         1/1         2/2         1/2         2/2
Wild_Gen1003 Wild_Gen1 2/2         1/1         2/2         1/2         2/2
```

**Comment by romunov** [comment]
Can you demonstrate the bug using one of the dataset that comes wiht `adegenet`? What exactly do you mean by "appears to be adding new names for the first one or two loci"? It may be that I'm dense right now but I can't see this in the example you provided.

**Comment by vilopr** [comment]
Hi Roman-

Check out the column headers in the last dataframe that I posted - the first one has been changed to '2' and the rest of the locus names have been shifted along. Perhaps I have been doing something dumb, but I cannot see what it is.

I will try tomorrow to see if I can replicate it with one of the adegenet datasets.

Thanks, Vicky.

**Comment by mariposa1311** [comment]
Hi, 

I had the same problem. Apparently, the problem happens when there is only one allele in a locus. It is the case neither with nancycats nor microbov where all loci are polymorphic so the bug never appears with the datasets available in the package.

It looks like the problem appears when the function does : 
"tab1 <- as.matrix(cbind.data.frame(kX1))
tab2 <- as.matrix(cbind.data.frame(kX2))"

**Comment by romunov** [comment]
Can someone provide a reproducible example, please?

**Comment by thibautjombart** [comment]
Yes, +1 to a reproducible example! :) 
Though I am told a patch might be underway.. @mariposa1311 ?

**Comment by mariposa1311** [comment]
Hi, 

I added some lines to impose column names for tab1 and tab2. It looks like it is working on my dataset even when I have only one allele for a given locus. With the modidfication, I use this function hybridize : 


hybridize <- function(x1, x2, n, pop="hybrid",
                      res.type=c("genind","df","STRUCTURE"),
                      file=NULL, quiet=FALSE, sep="/", hyb.label="h"){
  ## checks
  if(!is.genind(x1)) stop("x1 is not a valid genind object")
  if(!is.genind(x2)) stop("x2 is not a valid genind object")
  if(!all(ploidy(x1)==ploidy(x1)[1])) stop("varying ploidy (in x1) is not supported for this function")
  if(!all(ploidy(x2)==ploidy(x2)[1])) stop("varying ploidy (in x2) is not supported for this function")
  if(ploidy(x1)[1] %% 2 != 0) stop("not implemented for odd levels of ploidy")
  if(ploidy(x1)[1] != ploidy(x2)[1]) stop("x1 and x2 have different ploidy")
  checkType(x1)
  checkType(x2)
  
  ## store a few variables
  n <- as.integer(n)
  ploidy <- ploidy(x1)[1]
  res.type <- match.arg(res.type)
  
  ## ensure different names for pop
  popNames(x1) <- "pop1"
  popNames(x2) <- "pop2"
  
  ## repool data
  x1x2 <- repool(x1, x2)
  x1 <- x1x2[pop=1]
  x2 <- x1x2[pop=2]
  
  ## used variables
  n1 <- nInd(x1)
  n2 <- nInd(x2)
  k <- nLoc(x1)
  
  #### get frequencies for each locus
  y1 <- genind2genpop(x1,pop=factor(rep(1,n1)),quiet=TRUE)
  freq1 <- tab(y1, freq=TRUE) # get frequencies
  freq1 <- split(freq1, y1@loc.fac) # split by locus
  freq1 <- freq1[locNames(x1)] # ensure right order
  
  y2 <- genind2genpop(x2,pop=factor(rep(1,n2)),quiet=TRUE)
  freq2 <- tab(y2, freq=TRUE) # get frequencies
  freq2 <- split(freq2, y2@loc.fac) # split by locus
  freq2 <- freq2[locNames(x2)] # ensure right order
  
  #### sampling of gametes
  ## kX1 / kX2 are lists of tables of sampled gametes
  kX1 <- lapply(freq1, function(v) t(rmultinom(n,ploidy/2,v)))
  names(kX1) <- locNames(x1)

### Part with modifications added to the original hybridize function ####################
  vec.paste1<-NULL
  Vec.all1<-NULL
  for(i in 1:k) { 
    colnames(kX1[[i]]) <- alleles(x1)[[i]]
    ## Paste the alleles locus after locus
    vec.paste1<-c(vec.paste1, alleles(x1)[[i]])
    ## Paste the number of alleles, locus after locus
    Vec.all1<-c(Vec.all1, length(alleles(x1)[[i]]))
  }
  kX2 <- lapply(freq2, function(v) t(rmultinom(n,ploidy/2,v)))
  names(kX2) <- locNames(x2)
  vec.paste2<-NULL
  Vec.all2<-NULL
  for(i in 1:k) { 
    colnames(kX2[[i]]) <- alleles(x2)[[i]]
    vec.paste2<-c(vec.paste2, alleles(x2)[[i]])
    Vec.all2<-c(Vec.all2, length(alleles(x2)[[i]]))
  }
  
  
  ## construction of zygotes ##
  ## individual gamete tables
  tab1 <- as.matrix(cbind.data.frame(kX1))
  ## Force the names of the columns for tab1 and tab2 with the pattern "locNames.allele"
  colnames(tab1)<-paste(rep(locNames(x1), Vec.all1), ".",vec.paste1, sep = "")
  tab2 <- as.matrix(cbind.data.frame(kX2))
  colnames(tab2)<-paste(rep(locNames(x2), Vec.all2), ".",vec.paste2, sep = "")

####### end of the part with the modifications ################################  

  ## make empty matrix with all alleles in tab1 and tab2
  zyg.rownames <- .genlab(hyb.label,n)
  zyg.colnames <- sort(unique(c(colnames(tab1),colnames(tab2))))
  zyg <- matrix(0, nrow=n, ncol=length(zyg.colnames),
                dimnames=list(zyg.rownames, zyg.colnames))
  
  ## add in the alleles
  zyg[, colnames(tab1)] <- zyg[, colnames(tab1)] + tab1
  zyg[, colnames(tab2)] <- zyg[, colnames(tab2)] + tab2
  zyg <- zyg
  zyg <- genind(zyg, type="codom", ploidy=ploidy)
  
  ## res.type=="STRUCTURE"
  if(res.type=="STRUCTURE"){
    ## res <- paste(gam1,gam2,sep=" ") # make df for the hybrids
    ## res <- as.data.frame(matrix(res,ncol=k))
    temp <- genind2df(repool(x1,x2,zyg), usepop=FALSE, sep=" ")
    res <- unlist(apply(temp,1,strsplit," "))
    res <- as.data.frame(matrix(res, nrow=nrow(temp), byrow=TRUE))
    colnames(res) <- rep(colnames(temp),each=ploidy)
    ## df1 <- genind2df(x1,sep=" ",usepop=FALSE) # make df with parents and hybrids
    ## df2 <- genind2df(x2,sep=" ",usepop=FALSE)
    ## res <- rbind.data.frame(df1,df2,res) # rbind the three df
    res[is.na(res)] <- "-9" # this is two missing alleles for STRUCTURE
    pop <- rep(1:3,c(nrow(x1@tab), nrow(x2@tab), n)) # make a pop identifier
    res <- cbind.data.frame(pop,res, stringsAsFactors = FALSE)
    names(res)[1] <- ""
    
    if(is.null(file)) {
      file <- gsub("[[:space:]]|:","-",date())
      file <- paste("hybrid",file,sep="_")
      file <- paste(file,"str",sep=".")
    }
    write.table(res, file=file,row.names = TRUE, col.names = TRUE, quote=FALSE)
    if(!quiet) cat("\nWrote results to file", file, "\n")
    
    return(invisible())
  }
  
  
  ## res.type=="df"
  if(res.type=="df"){
    ## res <- paste(gam1,gam2,sep=sep)
    ## res <- as.data.frame(matrix(res,ncol=k), stringsAsFactors=FALSE)
    ## names(res) <- x1@loc.names
    ## row.names(res) <- .genlab(hyb.label,n)
    
    res <- genind2df(zyg, sep=sep)
    return(res)
  }
  
  
  ## res.type=="genind"
  if(res.type=="genind"){
    ## res <- paste(gam1,gam2,sep="")
    ##         res <- as.data.frame(matrix(res,ncol=k), stringsAsFactors=FALSE)
    ##         names(res) <- x1@loc.names
    ##         row.names(res) <- .genlab(hyb.label,n)
    ## if(is.null(pop)){ # if pop is not provided, merge the two parent populations
    ##     pop <- paste(deparse(substitute(x1)) , deparse(substitute(x2)), sep="-")
    ## }
    pop <- factor(rep(pop,n))
    
    res <- zyg
    pop(res) <- pop
    res@call <- match.call()
    
    return(res)
  }
  
} # end hybridize

Looks like my problem is fixed using this...

**Comment by thibautjombart** [comment]
Cool! Now the way forward is:
1) fork adegenet 
2) clone your version of adegenet onto your computer 
3) make the changes above
4) commit (git commit -a -m "fixing bla bla bla"), push onto the server (git push)
5) make a pull request
Looks complicated but I swear it's much faster/easier than it seems. PM me if problem

**Comment by thibautjombart** [comment]
(Ah, I forgot: add yourself to the contributors in DESCRIPTION too ;) )

**Comment by thibautjombart** [comment]
Sorted as of b95ee3907649ed5875c20885c69b5b4e8ff4dc66 by @mariposa1311
