### ISSUE TITLE
implementing sPCA for genlight objects ?

### ISSUE THREAD

**Issue by LaurentGentzbittel** [thibautjombart/adegenet#95]
Dear Thibault,
Thank you for all your work and awesome implementations of multivariate methods for popgen analyses.
I realize that I might request a LOT of work, yet would you envisage implementing a glsPCA method ?
I bet it will be heavily used in a very close future.
Best regards

**Comment by thibautjombart** [comment]
It is a good question, and I think Denis Laoe asked it before. The biggest problem is diagonalising the operator __X^T(0.5(L^T + L))X__ which is P x P  where P is the number of variables. This would probably be impracticable in most cases where *genlight* objects are actually useful. We could run the sPCA on the PCs of a glPca to make this computation more doable though. Can't invest much time on this now, but if you want to find a master student to do it, happy to co-supervise ;)

**Comment by thibautjombart** [comment]
I replied to the same question on the forum:
I can see two options:
#1 PCA then multispati
Run a PCA on your data first and then use ade4's equivalent of the sPCA, multispati, to get a spatial analysis; your new object won't exactly be of the same structure as a sPCA but most outputs will be
there.

#2 PCA, retain most contributing loci, then sPCA
You can do a PCA on your whole dataset and then compute the average contribution (squared loadings) of your loci over the first xxx axes. Then you can keep the xxx loci which are most informative. I think I'd prefer this option slightly, as then you still work with alleles for your sPCA and not synthetic variables, but up to you:

Here's an example to get a new dataset with the 25% most contributing loci:
```r
> library(adegenet)
> data(H3N2)

## make your PCA
> pca1 <- dudi.pca(tab(H3N2, freq=TRUE,NA.method="mean"),scannf=FALSE,scale=FALSE, nf=3)

## use loadingplot to ID most contributing loci
> toKeep <- loadingplot(pca1$c1^2, byfac=TRUE,fac=locFac(H3N2))$var.idx
> toKeep
 45  60  73 148 168 171 225 247 317 351 391 396 435 463 464 468 476 483 490 566 577 578 582 600 604 673 676 679 763 807 963
  5   7   9  16  19  20  22  25  31  35  40  41  51  53  54  55  57  58  59  68  70  71  72  77  79  91  93  94  98 100 116
> new.x <- H3N2[loc=toKeep]
> new.x
/// GENIND OBJECT /////////

 // 1,903 individuals; 31 loci; 78 alleles; size: 1.4 Mb

 // Basic content
   @tab:  1903 x 78 matrix of allele counts
   @loc.n.all: number of alleles per locus (range: 2-4)
   @loc.fac: locus factor for the 78 columns of @tab
   @all.names: list of allele names for each locus
   @ploidy: ploidy of each individual  (range: 1-1)
   @type:  codom
   @call: .local(x = x, i = i, j = j, loc = ..1, drop = drop)

 // Optional content
   @other: a list containing: x  xy  epid

> locNames(new.x)
 [1] "45"  "60"  "73"  "148" "168" "171" "225" "247" "317" "351" "391" "396" "435" "463" "464" "468" "476" "483" "490" "566" "577"
[22] "578" "582" "600" "604" "673" "676" "679" "763" "807" "963"
```
