### ISSUE TITLE
Error in constructing dist.genpop object

### ISSUE THREAD

**Issue by GigaZaur** [thibautjombart/adegenet#99]
Hi Adegenet users

I have a question regarding an error in adegent I want to run by you all. I'm trying to calculate isolation by distance using about 1600 SNP loci.

Here's the error:

> Dgen_rw <- dist.genpop(gp_rw, method = 2)
Error in out[, colnames(x@tab), drop = FALSE] : subscript out of bounds

It appears that the dimensions of my objects aren't matched? But from what I can tell the number of colnames for the object is correct given the dimensions of the object. Not sure how to solve this progle. Below is my code.
 
<code>
library(adegenet)
library(LEA)
</code>

Read in the geographic distances
<code>
xy_rw <- read.table("dist_RW.txt", header = F, sep = '\t')
</code>

Read in the genetic data
<code>
geno_rw <- read.geno("balsam_437inds_51pops_1649snp_NonCoding.geno")
</code>

Read in population names
<code>
pop_rw <-unlist(read.delim("437pop", header = FALSE))
</code>

Convert it to a genind object
<code>
gi_rw <- genind(geno_rw)
</code>

Add xy coordiantes to genind object
<code>
gi_rw$other$xy <- xy_rw
</code>

Covert data to genpop object
<code>
gp_rw <- genind2genpop(gi_rw, pop = pop_rw)
</code>

Make genetic distance object
<code>
Dgen_rw <- dist.genpop(gp_rw, method = 2)
</code>

Here are the data files neccessary for this code:
http://www.uvm.edu/~kfetter/437pop
http://www.uvm.edu/~kfetter/balsam_437inds_51pops_1649snp_NonCoding.geno
http://www.uvm.edu/~kfetter/dist_RW.txt

Thanks for your help!!!

Karl

**Comment by thibautjombart** [comment]
I tried reproducing the code but no library LEA.. 
```r
> install.packages("LEA")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning message:
package ‘LEA’ is not available (for R Under development) 
```
Also can you please post next scripts with comments (so that one can copy paste everything in one go)?

**Comment by romunov** [comment]
`LEA` appears to be from [Bioconductor](http://www.bioconductor.org/packages/release/bioc/html/LEA.html).

**Comment by romunov** [comment]
I think the error is in [line 127 of handling.R](https://github.com/thibautjombart/adegenet/blob/master/R/handling.R#L127). `out` is not a list but a matrix, so this step may be, in this case, unnecessary.

**Comment by zkamvar** [comment]
Hi,

I just looked at the data and I believe the issue might be how missing data is encoded. Here may be a few reasons why this is not working:

1. The function `read.geno()` will return a matrix with **one column per locus** with counts of minor alleles.
2. The function `genind()` expects a matrix with **one column per allele**.
3. It appears that missing data may be encoded as "9" OR that this data set is nonapolid.
```r
table(geno_rw)
## geno_rw
##      0      1      2      9 
## 570070  34440   9032 107071 
```

I'm pasting my modified code below that should alleviate this problem. @GigaZaur, please let me know if this solves your problem:

```r
library(adegenet)

# install LEA
# source("https://bioconductor.org/biocLite.R")
# biocLite("LEA")
library(LEA)

# Function for converting diploid matrix of MA counts to a matrix suitable for a genind object.
# If the 9 is really an allele count, you will need to adjust the genotypes.
prepare_gid <- function(x, missing = 9){
  res <- x
  res[x == missing] <- NA
  res[x == 0] <- "1/1" # "1/1/1/1/1/1/1/1/1" # If nonaploid...
  res[x == 1] <- "1/2" # "1/1/1/1/1/1/1/1/2"
  res[x == 2] <- "2/2" # "1/1/1/1/1/1/1/2/2"
  return(res)
}

xy_rw <- read.table(url("http://www.uvm.edu/~kfetter/dist_RW.txt"), header = F, sep = '\t') 
download.file("http://www.uvm.edu/~kfetter/balsam_437inds_51pops_1649snp_NonCoding.geno", 
              destfile = "balsam_437inds_51pops_1649snp_NonCoding.geno")
geno_rw <- read.geno("balsam_437inds_51pops_1649snp_NonCoding.geno")
geno_prep <- prepare_gid(geno_rw, missing = 9)

unlink("balsam_437inds_51pops_1649snp_NonCoding.geno")

pop_rw <-unlist(read.delim(url("http://www.uvm.edu/~kfetter/437pop"), header = FALSE)) 

###
### Here, I've changed the genind call to df2genind and added the population factor in there
###
gi_rw <- df2genind(geno_rw, sep = "/", ploidy = 2, pop = pop_rw) 

other(gi_rw)$xy <- xy_rw 

gp_rw <- genind2genpop(gi_rw) 
Dgen_rw <- dist.genpop(gp_rw, method = 2) 
```

**Comment by zkamvar** [comment]
Since I haven't heard any dissent for this, I'm going to close it. @GigaZaur, reopen this issue if you are still having problems after using the solution above.
